apache/hadoop

- hadoop-ozone/pom.xml
See: https://issues.apache.org/jira/browse/HDDS-977
> HDDS-977. Exclude dependency-reduced-pom.xml from ozone rat check.

- hadoop-ozone/datanode/pom.xml
- hadoop-ozone/dist/pom.xml
- hadoop-ozone/pom.xml
- hadoop-ozone/s3gateway/pom.xml
see: https://issues.apache.org/jira/browse/HDDS-1092
> HDDS-1092. Use Java 11 JRE to run Ozone in containers

- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBCheckpointManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBStore.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDbSnapshotServlet.java
Fixing findbugs issues caused by HDDS-1085.
> HDDS-1139 : Fix findbugs issues caused by HDDS-1085.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/token/OzoneBlockTokenIdentifier.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneTokenIdentifier.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
> Revert "HDDS-1183. Override getDelegationToken API for OzoneFileSystem. Contr…"

- hadoop-ozone/common/src/main/bin/ozone
- hadoop-ozone/dist/pom.xml
- hadoop-ozone/ozone-recon/pom.xml
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
- hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/index.html
- Create the lifecycle scripts (start/stop) for Recon Server along with Shell interface like the other components.
- Verify configurations are being picked up by Recon Server on startup.
> HDDS-1260. Create Recon Server lifecycle integration with Ozone.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java
Change-Id: I461e518ce9a4730b91a8138ad55b39e9a4b0a4b8
> HADOOP-16218. Findbugs warning of null param in Configuration with Guava update.

- hadoop-ozone/dist/src/main/compose/ozone-recon/.env
- hadoop-ozone/dist/src/main/compose/ozone-recon/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozone-recon/docker-config
Add a docker compose for Ozone deployment with Recon.
Test out Recon container key service.
> HDDS-1330 : Add a docker compose for Ozone deployment with Recon.

- hadoop-ozone/dist/src/main/compose/ozonesecure-mr/README.md
- hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config
see: https://issues.apache.org/jira/browse/HDDS-1385
This is a PR on top of  HDDS-1333
> HDDS-1385. Make the ozonesecure-mr environment definition version

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java
- hadoop-ozone/integration-test/src/test/bin/start-chaos.sh
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java
This jira adds a shell script to run MiniOzoneChaosCluster.
> HDDS-1388. Add a shell script to run MiniOzoneChaosCluster using mvn exec. Contributed by Mukul Kumar Singh.

- hadoop-ozone/integration-test/src/test/bin/start-chaos.sh
Change-Id: I4fcf39d61a7d4c4ca79cb56a6958db0f691fe971
> HDDS-1418. Move bang line to the start of the start-chaos.sh script.

- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
Some of the optimizations made in HDDS-1300 were reverted in HDDS-1333. This Jira aims to bring back those optimizations.
> HDDS-1460: Add the optmizations of HDDS-1300 to BasicOzoneFileSystem

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
> HDDS-1500 : Allocate block failures in client should print exception trace.

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
Some small checkstyle issues are accidentally committed with HDDS-700.
Trivial fixes are coming here...
See: https://issues.apache.org/jira/browse/HDDS-1598
> HDDS-1598. Fix Ozone checkstyle issues on trunk

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
https://issues.apache.org/jira/browse/HDDS-1530
Ozone: Freon: Support big files larger than 2GB and add "--bufferSize" and "--validateWrites" options.
> HDDS-1530. Freon support big files larger than 2GB and add --bufferSize and --validateWrites options.

- hadoop-hdds/common/src/main/resources/ozone-default.xml
Added REQUIRED tag on fallback property and updated description of other configs as needed.
> HDDS-1581. Atleast one of the metadata dir config property must be tagged as REQUIRED

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
https://issues.apache.org/jira/browse/HDDS-1637
> HDDS-1637. Fix random test failure TestSCMContainerPlacementRackAware.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerScrubber.java
Change-Id: I767ecfe4f27729955ca41b5f634400742a49bbbd
Add protocol message and handling to report container corruptions to the SCM.
Also add basic recovery handling in SCM.
> HDDS-1201. Reporting Corruptions in Containers to SCM

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
https://issues.apache.org/jira/browse/HDDS-1532
> HDDS-1532. Improve the concurrent testing framework of Freon.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/metrics/OzoneManagerDoubleBufferMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/metrics/package-info.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithDummyResponse.java
Added DoubleBuffer Metrics in OM:
1. totalNumOfFlushIterations
2. totalNumOfFlushedTransactions.
3. maxNumberOfTransactionsFlushedInOneIteration
> HDDS-1579. Create OMDoubleBuffer metrics.

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java
https://issues.apache.org/jira/browse/HDDS-1787?filter=-1
> HDDS-1787. NPE thrown while trying to find DN closest to client.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/bucket/S3BucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/bucket/S3BucketCreateResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/bucket/S3BucketDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerHARequestHandlerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/bucket/TestS3BucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestOMResponseUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/bucket/TestS3BucketDeleteResponse.java
This PR is dependent on HDDS-1689.
To get Jenkins run posted this along with HDDS-1689 PR.
> HDDS-1795. Implement S3 Delete Bucket request to use Cache and DoubleBuffer.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBTable.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/Table.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/TypedTable.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/utils/db/TestRDBTableStore.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/utils/db/TestTypedRDBTableStore.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
> Revert "HDDS-1829 On OM reload/restart OmMetrics#numKeys should be updated"

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCommitPartResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerHARequestHandlerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
This is dependent on HDDS-1856. 
To get CI run, posted HDDS-1856 changes + HDDS-1849  in this PR.
> HDDS-1849. Implement S3 Complete MPU request to use Cache and DoubleBuffer.

- hadoop-common-project/hadoop-auth/pom.xml
> HADOOP-15410

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
Currently `testDoubleBuffer` waits for a specific transaction count and checks `lastAppliedIndex`, which is updated last in `flushTransactions` on another thread.  I guess this may be the cause of flakiness.  By swapping the order in the test, we ensure that when the wait is over, all operations (transaction count increase, etc.) are done.
https://issues.apache.org/jira/browse/HDDS-1921
Ran `TestOzoneManagerDoubleBufferWithOMResponse` a few times.
> HDDS-1921. TestOzoneManagerDoubleBufferWithOMResponse is flaky

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardDDBRootOperations.java
Change-Id: I26f8e9bc441bd1cb7b0d9b37161984049df6bac4
> HADOOP-16481. ITestS3GuardDDBRootOperations.test_300_MetastorePrune needs to set region

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/sink/PrometheusMetricsSink.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/metrics2/sink/TestPrometheusMetricsSink.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-16495
> HADOOP-16495. Fix invalid metric types in PrometheusMetricsSink

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java
Fix issue #[HDDS-1894](https://issues.apache.org/jira/browse/HDDS-1894?focusedCommentId=16902551&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel)
> HDDS-1894. Add filter to scmcli listPipelines.

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneClientUtils.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rest/RestClient.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/handlers/BucketArgs.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerHelper.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestMultipleContainerReadWrite.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/web/client/TestBuckets.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/handlers/BucketHandler.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/handlers/BucketProcessTemplate.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/interfaces/StorageHandler.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/storage/DistributedStorageHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestBucketManagerImpl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneVolumeStub.java
(cherry picked from commit b60d93b8b500f0ba97c027125401368d22028822)
> HDDS-1913. Fix OzoneBucket and RpcClient APIS for acl.

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java
This patch fixes checkstyle errors in ListPipelinesSubcommand.java
> HDDS-1979. Fix checkstyle errors

- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/client/HttpFSFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/FSOperations.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/client/BaseTestHttpFSWith.java
> HDFS-14665. HttpFS: LISTSTATUS response is missing HDFS-specific fields

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/Node2ObjectsMap.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/Node2PipelineMap.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java
#HDDS-1577
Add pipeline placement policy
> HDDS-1577. Add default pipeline placement policy implementation.

- .github/pull_request_template.md
- pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-15184
* Updated the URL of the wiki page.
> HADOOP-15184. Add GitHub pull request template.

- LICENSE-binary
- hadoop-project/pom.xml
> HADOOP-16555. Update commons-compress to 1.19.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java
> HDDS-2126. Ozone 0.4.1 branch build issue.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
> HDDS-2117. ContainerStateMachine#writeStateMachineData times out.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/LevelDBStoreIterator.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreIterator.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/TestMetadataStore.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/utils/OzoneUtils.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFsShell.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyValidator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/S3KeyGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/SameKeyReader.java
Unfortunately checkstyle checks didn't work well from HDDS-2106 to HDDS-2119. 
This patch fixes all the issues which are accidentally merged in the mean time. 
See: https://issues.apache.org/jira/browse/HDDS-2154
> HDDS-2154. Fix Checkstyle issues

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/Mkdir.java
Change-Id: I5b0d0995cee48187aec40c06f4da1c9b3c97fcf8
> HDFS-14874. Fix TestHDFSCLI and TestDFSShell test break because of logging change in mkdir

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/pom.xml
- hadoop-ozone/pom.xml
> HDDS-2207. Update Ratis to latest snapshot.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/ActiveLock.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/LockManager.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lock/TestLockManager.java
Currently LockManager is using exclusive lock, instead we should support ReadWrite lock.
> HDDS-2223. Support ReadWrite lock in LockManager.

- hadoop-project/pom.xml
An integration/smoke test with multiple components (HDFS, HBase, Spark etc) is in progress. 
I will update the PR once done.
> HADOOP-16579 - Upgrade to Apache Curator 4.2.0 excluding ZK

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-16609
> HADOOP-16609. Add Jenkinsfile for all active branches (branch-3.2)

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheKey.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCacheImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
> HDDS-1984. Fix listBucket API.

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3Guard.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestS3Guard.java
Change-Id: I368ec8d0395dd15272a8ed718823992d472028f3
> HADOOP-16484. S3A to warn or fail if S3Guard is disabled

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/ConnectionPool.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestConnectionManager.java
> HDFS-14962. RBF: ConnectionPool#newConnection() error log wrong protocol class

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/filesystem.md
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirDeleteOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestProtectedDirectories.java
> HDFS-14802. The feature of protect directories should be used in RenameOp

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
Change-Id: I63b928ef5da425ef982dd4100a426fc23f64bac1
> HADOOP-16484. S3A to warn or fail if S3Guard is disabled - addendum: silent for S3GuardTool

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/integration/ITestS3ACommitterMRJob.java
Downgrade the checks for leftover __magic entries from fail to warn now the parallel
test runs make speculation more likely. That or we disable specex.
Change-Id: Ia4df2e90f82a06dbae69f3fdaadcbb0e0d713b38
> HADOOP-16632. Speculating & Partitioned S3A magic committers can leave pending files under __magic

- pom.xml
https://issues.apache.org/jira/browse/HADOOP-16719
> HADOOP-16719. Remove the disallowed element config within maven-checkstyle-plugin

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardFsck.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardFsckViolationHandler.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardFsck.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolDynamoDB.java
Change-Id: I9bf479170a21f47817144a778aa63fd309ea1ab9
> HADOOP-16424. S3Guard fsck: Check internal consistency of the MetadataStore

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/testing.md
https://issues.apache.org/jira/browse/HADOOP-16758
> HADOOP-16758. Refine testing.md to tell user better how to use auth-keys.xml

- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload/src/main/java/org/apache/hadoop/tools/dynamometer/workloadgenerator/audit/AuditLogDirectParser.java
> HDFS-15044. [Dynamometer] Show the line of audit log when parsing it unsuccessfully.

- dev-support/docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/YARN-10036
> YARN-10036. Install yarnpkg in Dockerfile

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/SnapshotDiffReportListing.java
https://issues.apache.org/jira/browse/HDFS-15073
> HDFS-15073. Remove the usage of curator-shaded guava in SnapshotDiffReportListing.java

- hadoop-project/pom.xml
Follow up task of HADOOP-16729, extract even more version numbers for branch-3.2.
Change-Id: I0546fc8ec8f68baa4bcfa9db0df4d8293b078913
> HADOOP-16772. Extract version numbers to head of pom.xml (addendum)

- LICENSE-binary
- hadoop-project/pom.xml
- licenses-binary/LICENSE-zstd-jni.txt
JIRA: https://issues.apache.org/jira/browse/HADOOP-15993
> HADOOP-15993. Upgrade Kafka to 2.4.0 in hadoop-kafka module.

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/FederationUtil.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15100
> HDFS-15100. RBF: Print stacktrace when DFSRouter fails to fetch/parse JMX output from NameNode.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/main/java/org/apache/hadoop/yarn/server/applicationhistoryservice/webapp/ContextFactory.java
JIRA: https://issues.apache.org/jira/browse/YARN-9743
> YARN-9743. [JDK11] TestTimelineWebServices.testContextFactory fails.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java
https://issues.apache.org/jira/browse/YARN-9696
> HADOOP-16851. Removed unused import in Configuration

- LICENSE-binary
- hadoop-project/pom.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/pom.xml
JIRA: https://issues.apache.org/jira/browse/YARN-8374
> YARN-8374. Upgrade objenesis to 2.6

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core/src/main/java/org/apache/hadoop/applications/mawo/server/common/TaskStatus.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core/src/main/java/org/apache/hadoop/applications/mawo/server/worker/WorkerId.java
JIRA: https://issues.apache.org/jira/browse/YARN-10152
> YARN-10152. Fix findbugs warnings in hadoop-yarn-applications-mawo-core module

- hadoop-project/pom.xml
https://issues.apache.org/jira/browse/HADOOP-16891
Compilation passed locally.
> HADOOP-16891. Upgrade jackson-databind to 2.9.10.3

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
Change-Id: Ie04354fa21dc90f34a0f3d5983e40f9e4096380b
> HADOOP-14936. S3Guard: remove experimental from documentation

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/io/file/tfile/TestTFile.java
- hadoop-tools/hadoop-distcp/src/main/resources/org/apache/hadoop/tools/mapred/CopyMapper_Counter.properties
- also fixes same type in unit tests
> HADOOP-16909 Typo in distcp counters

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardFsck.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardFsckViolationHandler.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardFsck.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolDynamoDB.java
Change-Id: I2cdb6601fea1d859b54370046b827ef06eb1107d
> HADOOP-16858. S3Guard fsck: Add option to remove orphaned entries

- dev-support/docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-16054
> HADOOP-16054. Update Dockerfile to use Bionic

- hadoop-project/pom.xml
Upgrades the hadoop-thirdparty shaded-protobuf_3.7 artifact to 1.0.0 released version
> HADOOP-16927. Update hadoop-thirdparty dependency version to 1.0.0

- hadoop-tools/hadoop-azure/pom.xml
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AbfsConfiguration.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/AbfsHttpConstants.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/ConfigurationKeys.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/FileSystemConfigurations.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/HttpQueryParams.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStream.java
- hadoop-tools/hadoop-azure/src/site/markdown/abfs.md
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemE2E.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsOutputStream.java
> [HADOOP-16818] ABFS: Combine append+flush calls for blockblob & appendblob

- hadoop-common-project/hadoop-auth/src/main/java/org/apache/hadoop/security/authentication/util/KerberosUtil.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-registry/src/main/java/org/apache/hadoop/registry/client/impl/zk/RegistrySecurity.java
https://issues.apache.org/jira/browse/HADOOP-16935
Thanks @aajisaka for the original work.
This is a clean backport.
Raising this PR to trigger the [precommits](https://builds.apache.org/job/hadoop-multibranch/view/change-requests/job/PR-1912/).
> HADOOP-16935. Backport HADOOP-10848. Cleanup calling of sun.security.krb5.Config

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-shuffle/src/main/java/org/apache/hadoop/mapred/ShuffleHandler.java
https://issues.apache.org/jira/browse/MAPREDUCE-7268
> MAPREDUCE-7268. Fix TestMapreduceConfigFields

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapred/TestNetworkedJob.java
JIRA: https://issues.apache.org/jira/browse/MAPREDUCE-7269
> MAPREDUCE-7269. TestNetworkedJob fails

- hadoop-project/pom.xml
- hadoop-tools/hadoop-azure/pom.xml
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/AccessTokenProvider.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/AzureADAuthenticator.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/MsiTokenProvider.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsMsiTokenProvider.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemCheckAccess.java
Backport HADOOP-16890- "ABFS: Change in expiry calculation for MSI token provider" to branch-2
> HADOOP-16933. Backport HADOOP-16890 and HADOOP-16825 to branch-2

- hadoop-project/pom.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-14836
> HADOOP-14836. Upgrade maven-clean-plugin to 3.1.0

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-16944
> HADOOP-16944. Use Yetus 0.12.0 in GitHub PR

- hadoop-project/pom.xml
https://issues.apache.org/jira/browse/HADOOP-17014
To branch-3.2
> HADOOP-17014. Upgrade jackson-databind to 2.9.10.4

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/MockDomainNameResolver.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15343
> HDFS-15343. TestConfiguredFailoverProxyProvider is failing.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/TestSocketIOWithTimeout.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNode.java
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/main/java/org/apache/hadoop/mapred/ClientServiceDelegate.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/GracefulDecommission.md
Fix typos timeout, interruped in several java files and GracefulDecommission.md
> HADOOP-17035. Fix typos timeout, interruped

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/Constants.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/HCFSMountTableConfigLoader.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/MountTableConfigLoader.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/package-info.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestHCFSMountTableConfigLoader.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFSOverloadSchemeCentralMountTableConfig.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeLocalFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFsTestSetup.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFSOverloadSchemeWithMountTableConfigInHDFS.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
HDFS-15306. Make mount-table to read from central place ( Let's say from HDFS).
> HDFS-15306. Make mount-table to read from central place ( Let's say from HDFS).

- hadoop-tools/hadoop-azure/src/site/markdown/abfs.md
ABFS: Fixing a formatting issue
> HADOOP-17004. ABFS: Fixing a formatting issue

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-17062
If this PR is merged. I'll update the config in the PreCommit-(HADOOP|HDFS|MAPREDUCE|YARN)-Build Jenkins jobs.
> HADOOP-17062. Fix shelldocs path in Jenkinsfile

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/S3ADelegationTokens.java
DT plugins will be asked for any additional token issuers,
an array can be returned, each one will be asked for tokens.
> HADOOP-17050 S3A to support multiple DTs

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/RawLocalFileSystem.java
Contributed by: Mehakmeet Singh
Tested by: mvn -T 1C -Dparallel-tests -DtestsThreadCount=8 clean verify
Region: East US, West US
> HADOOP-17020. Improving RawFileSystem Performance

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsLinkFallback.java
https://issues.apache.org/jira/browse/HDFS-15429
> HDFS-15429. mkdirs should work when parent dir is an internalDir and fallback configured.

- dev-support/docker/Dockerfile_aarch64
> HADOOP-17084 Update Dockerfile_aarch64 to use Bionic

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestNNStartupWhenViewFSOverloadSchemeEnabled.java
https://issues.apache.org/jira/browse/HDFS-15450
> HDFS-15450. Fix NN trash emptier to work in HA mode if ViewFSOveroadScheme enabled

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/Constants.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/ViewFsOverloadScheme.md
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeHdfsFileSystemContract.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestViewFileSystemOverloadSchemeWithDFSAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestViewFileSystemOverloadSchemeWithFSCommands.java
https://issues.apache.org/jira/browse/HDFS-15449
> HDFS-15449. Optionally ignore port number in mount-table name when picking from initialized uri.

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/webapps/router/explorer.js
- hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/explorer.js
https://issues.apache.org/jira/browse/HDFS-15312
> HDFS-15312. Apply umask when creating directory by WebHDFS

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/committer_architecture.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/index.md
> HADOOP-17117 Fix typos in hadoop-aws documentation

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/AbstractDelegationTokenSecretManager.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/ZKDelegationTokenSecretManager.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/metrics/RBFMetrics.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/metrics/RouterMBean.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RBFConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/security/token/ZKDelegationTokenSecretManagerImpl.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/resources/hdfs-rbf-default.xml
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/security/TestRouterSecurityManager.java
> HDFS-15447 RBF: Add top real owners metrics for delegation tokens

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
@goiri The issue HDFS-9929 forget to delete the comma.
> HDFS-15371. Nonstandard characters exist in NameNode.java

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirSnapshotOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectorySnapshottableFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestOrderedSnapshotDeletion.java
Please see https://issues.apache.org/jira/browse/HDFS-15479
> HDFS-15479. Ordered snapshot deletion: make it a configurable feature

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsOverloadSchemeListStatus.java
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/ViewFsOverloadScheme.md
https://issues.apache.org/jira/browse/HDFS-15478
> HDFS-15478: When Empty mount points, we are assigning fallback link to self. But it should not use full URI for target fs.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/HdfsServerConstants.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirXAttrOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/AbstractINodeDiffList.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectorySnapshottableFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/FSImageFormatPBSnapshot.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/Snapshot.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotDeletionGc.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestOrderedSnapshotDeletion.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestOrderedSnapshotDeletionGc.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestSnapshotDeletion.java
Please see https://issues.apache.org/jira/browse/HDFS-15481
> HDFS-15481. Ordered snapshot deletion: garbage collect deleted snapshots

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestSnapshotManager.java
please see https://issues.apache.org/jira/browse/HDFS-15497.
> HDFS-15497. Make snapshot limit on global as well per snapshot root directory configurable

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestUGILoginFromKeytab.java
> HADOOP-17164 UGI loginUserFromKeytab doesn't set the last login time

- Jenkinsfile
https://issues.apache.org/jira/browse/HADOOP-17184
> HADOOP-17184. Add --mvn-custom-repos parameter to yetus calls

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-17185
> HADOOP-17185. Set MAVEN_OPTS in Jenkinsfile

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/ListingOperationCallbacks.java
> HADOOP-17186 fixing javadoc in ListingOperationCallbacks

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystem.java
Adding debug log for ABFS rename failures.
> HADOOP-17163. ABFS: Adding debug log for rename failures

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15512
> HDFS-15512. Remove smallBufferSize in DFSClient.

- hadoop-project/src/site/site.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17182
After:
> HADOOP-17182. Remove breadcrumbs from web site

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FsConstants.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/InodeTree.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFSOverloadSchemeWithMountTableConfigInHDFS.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystemContract.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystemWithMountLinks.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestCacheDirectives.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestCacheDirectivesWithViewDFS.java
https://issues.apache.org/jira/browse/HDFS-15533
> HDFS-15533: Provide DFS API compatible class, but use ViewFileSystemOverloadScheme inside.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestFSImageWithOrderedSnapshotDeletion.java
please see https://issues.apache.org/jira/browse/HDFS-15542.
> HDFS-15542. Add identified snapshot corruption tests for ordered snapshot deletion

- .gitignore
> YARN-10407. Add phantomjsdriver.log to gitignore.

- hadoop-project/pom.xml
> HADOOP-17254. Upgrade hbase to 1.4.13 on branch-2.10.

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterRpcClient.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15555
> HDFS-15555. RBF: Refresh cacheNS when SocketException occurs.

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-17262
> HADOOP-17262. Switch to Yetus main branch.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/InodeTree.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestViewfsFileStatus.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFsBaseTest.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsLinkFallback.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystemWithMountLinks.java
https://issues.apache.org/jira/browse/HDFS-15578
> HDFS-15578: Fix the rename issues with fallback fs enabled

- hadoop-common-project/hadoop-common/src/site/markdown/CommandsManual.md
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs-tests/test_libhdfs_mini_stress.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/include/hdfspp/uri.h
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/uriparser2/uriparser2/uriparser/UriFile.c
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/utils/ConsistentHashRing.java
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/WebHDFS.md
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask/src/main/native/src/NativeTask.h
- hadoop-yarn-project/hadoop-yarn/conf/container-executor.cfg
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/DockerContainers.md
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/Federation.md
> HADOOP-17277. Correct spelling errors for separator

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/main/java/org/apache/hadoop/mapreduce/v2/app/job/impl/JobImpl.java
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/test/java/org/apache/hadoop/mapreduce/v2/app/job/impl/TestJobImpl.java
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/Job.java
> MAPREDUCE-7294. Only application master should upload resource to Yarn Shared Cache.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15598
> HDFS-15598: ViewHDFS#canonicalizeUri should not be restricted to DFS only API.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/tracing/TestTracing.java
> HDFS-15577. Refactor TestTracing.

- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/HdfsDataNodeAdminGuide.md
> HDFS-15604. Fix Typo for HdfsDataNodeAdminGuide doc

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/ReflectionUtils.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/util/TestReflectionUtils.java
https://issues.apache.org/jira/browse/HADOOP-17287
This PR provide possibility to new instance by non default constructor through ReflectionUtils
> HADOOP-17287. Support new Instance by non default constructor by ReflectionUtils

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/CallerContext.java
- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestCallerContext.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAuditLogger.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/metrics/TimelineServiceV1Publisher.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/metrics/TimelineServiceV2Publisher.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/records/impl/pb/ApplicationStateDataPBImpl.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMAuditLogger.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17276
> HADOOP-17276. Extend CallerContext to make it include many items

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-17297
Use https://github.com/apache/yetus/tree/6ab19e71eaf3234863424c6f684b34c1d3dcc0ce
> HADOOP-17297. Use Yetus before YETUS-994 to enable adding comments to GitHub

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterClientProtocol.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterAdminCLI.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15613
Manually tested in the real cluster.
> HDFS-15613. RBF: Router FSCK fails after HDFS-14442.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
> HDFS-15253 Default checkpoint transfer speed, 50mb per second

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/CallerContext.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterRpcClient.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterRpc.java
…d client ip to NamenodeRpcServer
> HDFS-13293. RBF: The RouterRPCServer should transfer client IP via CallerContext to NamenodeRpcServer

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestNNStartupWhenViewFSOverloadSchemeEnabled.java
https://issues.apache.org/jira/browse/HDFS-15625
> HDFS-15625: Namenode trashEmptier should not init ViewFs on startup

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHDFS.java
> HDFS-15626 TestWebHDFS.testLargeDirectory failing

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
https://issues.apache.org/jira/browse/HDFS-15633
> HDFS-15633. Avoid redundant RPC calls for getDiskStatus.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/TouchCommands.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFsShellTouch.java
https://issues.apache.org/jira/browse/HADOOP-17310
> HADOOP-17310. Touch command with -c option is broken.

- hadoop-tools/hadoop-sls/src/main/html/js/thirdparty/jquery.js
jQuery is upgraded from 3.3.1 to 3.5.1 at 
hadoop/hadoop-tools/hadoop-sls/src/main/html/js/thirdparty
> HADOOP-17302. Upgrade to jQuery 3.5.1 in hadoop-sls.

- start-build-env.sh
If a username includes a backslash, `mvn clean install` fails in an environment started by start-build-env.sh.
The causes of this problem are as follows:
1. start-build-env.sh sets the home directory in the Docker container to /home/${USER_NAME}. 
2. Maven does not support path names such as "/home/CORP\name/". This type of path names appears in Amazon WorkSpaces. 
Therefore, I have made it possible for users to change their home directory in the Docker container.
I have tested this patch in Amazon WorkSpaces.
> HADOOP-17298. Backslash in username causes build failure in the environment started by start-build-env.sh.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/fs/Hdfs.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
> HDFS-15639. [JDK 11] Fix Javadoc errors in hadoop-hdfs-client.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSClientRetries.java
> HDFS-15461. TestDFSClientRetries testGetFileChecksum fails.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestHAAppend.java
> HDFS-9776. TestHAAppend#testMultipleAppendsDuringCatchupTailing is flaky

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/NNThroughputBenchmark.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNNThroughputBenchmark.java
> HDFS-15652. Make block size from NNThroughputBenchmark configurable

- hadoop-project/pom.xml
This PR aims to upgrade `commons-codec` to 1.15. 
- https://commons.apache.org/proper/commons-codec/changes-report.html#a1.15
> HADOOP-17341. Upgrade commons-codec to 1.15

- dev-support/docker/Dockerfile
This reverts https://github.com/apache/hadoop/commit/931adbaa1412dcf8dc8679a8305c5146a4fe2821.
> Revert "HADOOP-17224. Install Intel ISA-L library in Dockerfile. (#2243)"

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java
https://issues.apache.org/jira/browse/HADOOP-17360
> HADOOP-17360. Log the remote address for authentication success

- dev-support/bin/hadoop.sh
JIRA: https://issues.apache.org/jira/browse/HADOOP-17352
Update the link to the new Confluence wiki.
> HADOOP-17352. Update PATCH_NAMING_RULE in the personality file.

- hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/DistCp.java
> HDFS-15608. Rename variable DistCp#CLEANUP.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/CallQueueManager.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/DecayRpcScheduler.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RPC.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/UserIdentityProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/SecurityUtil.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/authorize/ServiceAuthorizationManager.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestDecayRpcScheduler.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestRPC.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestRpcBase.java
> HADOOP-17346. Fair call queue is defeated by abusive service principals

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/HarFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestHarFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestHarFileSystemBasics.java
> HADOOP-17362. reduce RPC calls doing ls on HAR file

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask/pom.xml
https://issues.apache.org/jira/browse/HADOOP-17390
checked by `mvn --batch-mode -fn apache-rat:check`
> HADOOP-17390. Skip license check on lz4 code files

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestGetBlocks.java
> HDFS-15695. NN should not let the balancer run in safemode

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Client.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetUtils.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestSaslRPC.java
> HADOOP-17392. Remote exception messages should not include the exception class

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/top/metrics/TopMetrics.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/top/window/RollingWindow.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/top/window/RollingWindowManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/top/window/TestRollingWindowManager.java
> HDFS-15707. NNTop counts don't add up as expected.

- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
updated to a more precise definition to dfs.datanode.handler.count description
https://issues.apache.org/jira/browse/HDFS-15728
> HDFS-15728. Update description of dfs.datanode.handler.count in hdfs-default.xml

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestDeleteRace.java
> HDFS-15704. Mitigate lease monitor's rapid infinite loop.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/Text.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/io/TestText.java
https://issues.apache.org/jira/browse/HADOOP-17430
> HADOOP-17430. Add clear bytes logic for hadoop Text

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/SecurityUtil.java
- hadoop-common-project/hadoop-registry/src/main/java/org/apache/hadoop/registry/server/dns/RegistryDNS.java
- hadoop-common-project/hadoop-registry/src/main/java/org/apache/hadoop/registry/server/dns/SecureableZone.java
- hadoop-common-project/hadoop-registry/src/test/java/org/apache/hadoop/registry/server/dns/TestRegistryDNS.java
- hadoop-project/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17317
> HADOOP-17317. [JDK 11] Upgrade dnsjava to remove illegal access warnings
