apache/hadoop

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs.robot
- hadoop-ozone/dist/src/main/smoketest/test.sh
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/VolumeManagerImpl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestRootList.java
Unfortunately as the previous two big commits (error handling HDDS-1068, checkstyle HDDS-1103) are committed in the same time a few new errors are introduced during the rebase.
This patch will fix the remaining 5 issues (+ a type in the acceptance test executor) 
See: https://issues.apache.org/jira/browse/HDDS-1114
> HDDS-1114. Fix findbugs/checkstyle/accepteance errors in Ozone

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/chillmode/TestSCMChillModeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithDatanodeFastRestart.java
As I wrote in the description of the parent Jira I propose to disable (@Ignore) the unit tests which are failing while we are fixing them to get clean Jira response from the PreCommit builds.
All the tests are tracked in a separated jira.
See: https://issues.apache.org/jira/browse/HDDS-1161
> HDDS-1161. Disable failing test which are tracked by a separated jira

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
Fixes failing test TestOzoneManagerHA#testTwoOMNodesDown()
> HDDS-1158. TestOzoneManagerHA.testTwoOMNodesDown is failing with ratis error.

- hadoop-project/pom.xml
Excludes the junit and hamcrest dependencies where they are out of date
Tested: locally
Change-Id: If95b12b223770b057041f99f0f8fd8ba370c377f
> HADOOP-16149 hadoop-mapreduce-client-app build not converging

- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js
Fields like below are empty
Node Manager: Minimum chill mode nodes 
Node Manager: Out-of-node chill mode 
Node Manager: Chill mode status 
Node Manager: Manual chill mode
Please see attached screenshot !Screen Shot 2018-10-10 at 4.19.59 PM.png!
See: https://issues.apache.org/jira/browse/HDDS-623
> HDDS-623. On SCM UI, Node Manager info is empty

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerActionsHandler.java
It's failed multiple times during the CI builds:
{code}
Error Message
Wanted but not invoked:
closeContainerEventHandler.onMessage(
#1,
org.apache.hadoop.hdds.server.events.EventQueue@3d3fcdb0
);
-> at org.apache.hadoop.hdds.scm.container.TestContainerActionsHandler.testCloseContainerAction(TestContainerActionsHandler.java:64)
Actually, there were zero interactions with this mock.
{code}
The fix is easy: we should call queue.processAll(1000L) to wait for the processing of all the events.
See: https://issues.apache.org/jira/browse/HDDS-1219
> HDDS-1219. TestContainerActionsHandler.testCloseContainerAction has an intermittent failure

- hadoop-ozone/dist/src/main/smoketest/commonlib.robot
- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PlainTextMultipartUploadReader.java
S3 Multi-Part-Upload (MPU) is implemented recently in the Ozone s3 gateway. We have extensive testing with using 'aws s3api' application which is passed.
But it turned out that the more simple `aws s3 cp` command fails with _405 Media type not supported error_ message
The root cause of this issue is the JAXRS implementation of the multipart upload method:
{code}
@POST
@Produces(MediaType.APPLICATION_XML)
public Response multipartUpload(
@PathParam("bucket") String bucket,
@PathParam("path") String key,
@QueryParam("uploads") String uploads,
@QueryParam("uploadId") @DefaultValue("") String uploadID,
CompleteMultipartUploadRequest request) throws IOException, OS3Exception {
if (!uploadID.equals("")) {
//Complete Multipart upload request.
return completeMultipartUpload(bucket, key, uploadID, …
> HDDS-1213. Support plain text S3 MPU initialization request

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractSeekTest.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/contract/s3a/ITestS3AContractSeek.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestConstants.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
Nobody gets seek right. No matter how many times they think they have.
Reproducible test from: Dave Christianson
Fixed seek() logic: Steve Loughran
Change-Id: I39b87f3d5daa98f65de2c0a44e348821a4930573
> HADOOP-16109. Parquet reading S3AFileSystem causes EOF

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/ozShell/TestOzoneShell.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/s3/GetS3SecretHandler.java
"ozone sh s3 getsecret" command throws a Null Pointer Exception.
This patch fixes it by showing the following message:
```
hadoop@fa14f2633ba4:~$ ozone sh s3 getsecret
This command is not supported in unsecure clusters.
```
> HDDS-1265. "ozone sh s3 getsecret" throws Null Pointer Exception for unsecured clusters

- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone-filesystem-lib-legacy-0.4.0-SNAPSHOT.jar can't work any more together with older hadoop version, after the change of HDDS-1183.
{code}
2019-03-13 13:48:51 WARN  FileSystem:3170 - Cannot load filesystem: java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.ozone.OzoneFileSystem could not be instantiated
2019-03-13 13:48:51 WARN  FileSystem:3174 - java.lang.NoClassDefFoundError: org/apache/hadoop/hdds/conf/OzoneConfiguration
2019-03-13 13:48:51 WARN  FileSystem:3174 - java.lang.ClassNotFoundException: org.apache.hadoop.hdds.conf.OzoneConfiguration
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hdds/conf/OzoneConfiguration
at java.lang.Class.forName0(Native Method)
at …
> HDDS-1259. OzoneFS classpath separation is broken by the token validation

- hadoop-ozone/s3gateway/src/main/resources/webapps/static/index.html
S3 gateway has a default web page to display a generic message if you open the endpoint in the browser:
http://localhost:9878/static/
It also contains a simple example to use the endpoint:
{code}
This is an endpoint of Apache Hadoop Ozone S3 gateway. Use it with any AWS S3 compatible tool with setting this url as an endpoint
For example with aws-cli:
aws s3api --endpoint http://localhost:9878/static/ create-bucket --bucket=wordcount
For more information, please check the documentation. 
{code}
Unfortunately the endpoint is wrong here, the static should be removed from the url.
The trivial fix is to move the ) in the js code>  
See: https://issues.apache.org/jira/browse/HDDS-1283
> HDDS-1283. Fix the dynamic documentation of basic s3 client usage

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
As of now we have a following algorithm to handle node failures:
1. In case of a missing node the leader of the pipline or the scm can detected the missing heartbeats.
2. SCM will start to close the pipeline (CLOSING state) and try to close the containers with the remaining nodes in the pipeline
3. After 5 minutes the pipeline will be destroyed (CLOSED) and a new pipeline can be created from the healthy nodes (one node can be part only one pipwline in the same time).
While this algorithm can work well with a big cluster it doesn't provide very good usability on small clusters:
Use case1:
Given 3 nodes, in case of a service restart, if the restart takes more than 90s, the pipline will be moved to the CLOSING state. For the next 5 minutes (ozone.scm.pipeline.destroy.timeout) the container …
> HDDS-1284. Adjust default values of pipline recovery for more resilient service restart

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/SCMContainerManager.java
"ozone scmcli list --start=1" lists containers starting from container ID 2.
There is no way to list the container with containerID 1.
This PR fixes this behavior.
> HDDS-1263. SCM CLI does not list container with id 1

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
S3AFileSystem#innerMkdirs currently does not create parent directories. The code checks for the existence of the parent directories and if they do not exist, it adds them to metadataStoreDirs list. But this list is not used and therefore the parent directories are never created. Only the given directory path is created.
> HADOOP-16201: S3AFileSystem#innerMkdirs builds needless lists

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/SCMContainerManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
This PR aims to avoid the contradiction with JavaDoc after the fix in HDDS-1263.
https://issues.apache.org/jira/browse/HDDS-1302
> HDDS-1302. Fix SCM CLI does not list container with id 1

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/MarshalledCredentials.java
S3A MarshalledCredentials.toString() doesn't print full date/time of expiry
Change-Id: I4f1bdd2be0d5760c5501dce6edb6122499108b53
> HADOOP-16195 MarshalledCredentials toString

- hadoop-ozone/tools/pom.xml
Add `jaxb-core` to `hadoop-ozone-tools` dependencies to make `ozone genconf` work again.
https://issues.apache.org/jira/browse/HDDS-1351
```
$ mvn -Phdds -DskipTests -Dmaven.javadoc.skip=true -Pdist -Dtar -DskipShade -am -pl :hadoop-ozone-dist clean package
$ cd $(git rev-parse --show-toplevel)/hadoop-ozone/dist/target/ozone-*-SNAPSHOT/compose/ozones3
$ docker-compose run datanode ozone genconf /tmp
ozone-site.xml has been generated at /tmp
```
> [HDDS-1351] NoClassDefFoundError when running ozone genconf

- hadoop-ozone/common/src/main/bin/ozone
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/ozShell/TestOzoneShell.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/OzoneShell.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/Shell.java
Let's check the potential subcommands of ozone sh:
{code}
[hadoop@om-0 keytabs]$ ozone sh
Incomplete command
Usage: ozone sh [-hV] [--verbose] [-D=<String=String>]... [COMMAND]
Shell for Ozone object store
--verbose   More verbose output. Show the stack trace of the errors.
-D, --set=<String=String>
-h, --help      Show this help message and exit.
-V, --version   Print version information and exit.
Commands:
volume, vol  Volume specific operations
bucket       Bucket specific operations
key          Key specific operations
token        Token specific operations
{code}
This is fine, but for ozone s3:
{code}
[hadoop@om-0 keytabs]$ ozone s3
Incomplete command
Usage: ozone s3 [-hV] [--verbose] [-D=<String=String>]... [COMMAND]
Shell for S3 specific operations
--verbose   More verbose output. …
> HDDS-1357. ozone s3 shell command has confusing subcommands

- hadoop-hdds/docs/pom.xml
Maven build fails to create HDDS docs due to the following hugo error in `hadoop-hdds-docs`:
```
$ mvn -Phdds -pl :hadoop-hdds-docs clean compile
...
[INFO] --- exec-maven-plugin:1.6.0:exec (default) @ hadoop-hdds-docs ---
Error: unknown command "0.5.0-SNAPSHOT" for "hugo"
Run 'hugo --help' for usage.
...
[INFO] BUILD SUCCESS
```
`generate-site.sh` passes all arguments to `hugo`, which expects commands, not HDDS version number and target directory.  I think these two parameters are unnecessary, hence the patch removes them.
https://issues.apache.org/jira/browse/HDDS-1322
With the fix docs can be generated using Maven:
```
$ mvn -Phdds -pl :hadoop-hdds-docs clean compile
...
[INFO] --- exec-maven-plugin:1.6.0:exec (default) @ hadoop-hdds-docs ---
Building sites …
...
| EN …
```
> HDDS-1322. Hugo errors when building Ozone

- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/filesystem.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractOpenTest.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileStatus.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/contract/s3a/ITestS3AContractOpen.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/auth/delegation/AbstractDelegationIT.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/auth/delegation/ITestDelegatedMRJob.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/mapreduce/filecache/TestS3AResourceScope.java
This is needed to fix up some confusion about caching of job.addCache() handling of S3A paths; all parent dirs -the files are downloaded by the NM without  using the DTs of the user submitting the job. This means that when you submit jobs to an EC2 cluster with lower IAM permissions than the user, cached resources don't get downloaded and the job doesn't start.
Production code changes:
* S3AFileStatus Adds "true" to the superclass's encrypted flag during construction.
Tests
* Base AbstractContractOpenTest can control whether zero byte files created in tests are encrypted. Not done via an XML attribute, just a subclass point. Thoughts?
* Verify that the filecache considers paths to not have the permissions which trigger reduce-privilege downloads
* And extend ITestDelegatedMRJob to test a …
> HADOOP-16233. S3AFileStatus to declare that isEncrypted() is always true

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/InsufficientDatanodesException.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMPipelineManager.java
There is a BackgroundPipelineCreator thread in SCM which runs in a fixed interval and tries to create pipelines. This BackgroundPipelineCreator uses IOException as exit criteria (no more pipelines can be created). In each run of BackgroundPipelineCreator we exit when we are not able to create any more pipelines, i.e. when we get IOException while trying to create the pipeline. This means that scm_pipeline_metrics_num_pipeline_creation_failed value will get incremented in each run of BackgroundPipelineCreator.
> HDDS-1353 : Metrics scm_pipeline_metrics_num_pipeline_creation_failed keeps increasing because of BackgroundPipelineCreator.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/SCMConnectionManager.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java
`testStartStopDatanodeStateMachine` is flaky, causing [occasional pre-commit build failures](https://builds.apache.org/job/hadoop-multibranch/job/PR-691/1/artifact/out/patch-unit-hadoop-hdds_container-service.txt).  [HDDS-1332](https://issues.apache.org/jira/browse/HDDS-1332) added some logging to find out more about the cause.
I think the problem is not test-specific, and is caused by the following: `SCMConnectionManager#scmMachines` is a plain `HashMap`, guarded by a `ReadWriteLock` in most places where it's used, except `getValues()`.  The method also returns the values collection without any write protection (though currently none of the callers modify it).
This is an attempt to fix the cause by acquiring the read lock and creating a read-only copy. …
> HDDS-1398. Concurrency issue in SCMConnectionManager#getValues

- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
ITestOzoneContractCreate and ITestOzoneContractMkdir are failing with FileAlreadyExistsException. The issue is around the file imported in BasicOzoneClientAdapterImpl. The class needs to import org.apache.hadoop.fs.FileAlreadyExistsException but currently imports java.nio.file.FileAlreadyExistsException.
> HDDS-1405. ITestOzoneContractCreate is failing.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java
The reason for this can be if we take more time in executing a task, and in taskAwait we will return state as RUNNING and continue, and now when we execute task again internally endPoint state can be shutdown. Below code can return null. So, we need a null check over there.
Callable<EndpointStateMachine.EndPointStates> endpointTask
= getEndPointTask(endpoint);
> HDDS-1370. Command Execution in Datanode fails becaue of NPE

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/DownloadAndImportReplicator.java
Whenever we want to replicate or copy a container from one datanode to another, we compress the container data and create a tar.gz file. This tar file is then copied from source datanode to destination datanode. In destination, we use a temporary working directory where this tar file is copied. Once the copying is complete we import the container. After importing the container we no longer need the tar file in the working directory of destination datanode, this has to be deleted.
> HDDS-1417. After successfully importing a container, datanode should delete the container tar.gz file from working directory.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/hdds/scm/HddsServerUtil.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/InitDatanodeState.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/ServerUtils.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/TestServerUtils.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ScmUtils.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtils.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/utils/OzoneUtils.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
`ozone.metadata.dirs` is a global fallback for per-component directory configurations, eg.`ozone.om.db.dirs`, `ozone.scm.db.dirs`, etc.  All of these handle only a single location, but values with multiple comma-separated paths (eg. `/data/dir1,/data/dir2`) are treated in different ways:
* rejected for the specific configs
* used as a single value for the fallback config
The goal of this change is to reject comma-separated paths for `ozone.metadata.dirs`, too, by applying the same logic that is already used for the per-component configs.
In addition, the following minor fixes are included:
1. Fix error message in `ServerUtils#getDirectoryFromConfig`, which referenced the component name (eg. `SCM`) instead of the config item name (eg. `ozone.om.db.dirs`) as "configuration setting".
2. Move …
> [HDDS-1363] ozone.metadata.dirs doesn't pick multiple dirs

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
TestMiniChaosOzoneCluster is failing with the below exception
{noformat}
[ERROR] org.apache.hadoop.ozone.TestMiniChaosOzoneCluster  Time elapsed: 265.679 s  <<< ERROR!
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at org.apache.hadoop.ozone.MiniOzoneClusterImpl.stop(MiniOzoneClusterImpl.java:350)
at org.apache.hadoop.ozone.MiniOzoneClusterImpl.shutdown(MiniOzoneClusterImpl.java:325)
at org.apache.hadoop.ozone.MiniOzoneChaosCluster.shutdown(MiniOzoneChaosCluster.java:130)
at org.apache.hadoop.ozone.TestMiniChaosOzoneCluster.shutdown(TestMiniChaosOzoneCluster.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
> HDDS-1387. ConcurrentModificationException in TestMiniChaosOzoneCluster

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
Let `TestCloseContainerCommandHandler` and `TestDatanodeStateMachine` both use random port for Ozone container, to avoid port conflict in case of parallel test execution.
First reproduced the issue using:
```
$ mvn -Phdds -pl :hadoop-hdds-container-service -Pparallel-tests test
```
Then verified that `TestDatanodeStateMachine` can be made to pass by either setting the random port or by disabling `TestCloseContainerCommandHandler` completely (using `@Ignore`).
> [HDDS-1434] TestDatanodeStateMachine is flaky

- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/hdfs/server/datanode/ObjectStoreHandler.java
When I analyzed the usages of the available RPC protocols in Ozone I found that the ScmBlockLocationProtocol is not used in ObjectStore at all.
I would propose to remove it...
See: https://issues.apache.org/jira/browse/HDDS-1402
> HDDS-1402. Remove unused ScmBlockLocationProtocol from ObjectStoreHandler

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DataStreamer.java
Signed-off-by: Eason Lu <luystu@gmail.com>
> HDFS-14433. Remove the extra empty space in the DataStreamer logging.

- hadoop-hdds/common/pom.xml
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchema.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchemaLoader.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchemaManager.java
- hadoop-hdds/common/src/main/resources/network-topology-default.yaml
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNodeSchemaLoader.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestYamlSchemaLoader.java
- hadoop-hdds/common/src/test/resources/networkTopologyTestFiles/good.yaml
- hadoop-hdds/common/src/test/resources/networkTopologyTestFiles/middle-leaf.yaml
- hadoop-hdds/common/src/test/resources/networkTopologyTestFiles/multiple-root.yaml
- hadoop-hdds/container-service/pom.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerDataYaml.java
This is a early stage patch to support load HDFS schema from a YAML file. 
It should need more unit tests.
> HDDS-976: Parse network topology from yaml file

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
cc: @nandakumar131 
I was able to get this work as expected by stopping the HB processing then closing the container, restarting SCM and making sure the close event is fired. 
Some ugly reflection had to be used since in general, we do not use test friendly things like dependency injection etc. :)
> HDDS-1411. Add unit test to check if SCM correctly sends close commands for containers in closing state after a restart.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneClientUtils.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/utils/OzoneUtils.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/storage/DistributedStorageHandler.java
Increasing the number of client retries to 100 and adding sleep of 500ms between retries
> HDDS-1403. KeyOutputStream writes fails after max retries while writing to a closed container

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/crypto/CryptoInputStream.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/ByteBufferPositionedReadable.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/ByteBufferReadable.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FSDataInputStream.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/StreamCapabilities.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/CryptoStreamsTestBase.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreams.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreamsForLocalFS.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreamsNormal.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs-tests/hdfs_test.h
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs-tests/test_libhdfs_ops.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestByteBufferPread.java
[HDFS-3246](https://issues.apache.org/jira/browse/HDFS-3246): First several iterations of this patch are posted on the JIRA. This PR is a continuation of this work, it was created to make the code more reviewable. The version of the patch posted here fixes a few minor issues reported by Yetus, and added some more Javadocs to the changes in `CryptoInputStream` to make the code easier to understand.
> HDFS-3246: pRead equivalent for direct read path

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/DatanodeIdYaml.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
cc: @arp7 Human readable version of the dn details will now be written out like this::
`!!org.apache.hadoop.ozone.container.common.helpers.DatanodeIdYaml$DatanodeDetailsYaml {
certSerialId: '8689088562908158976',
hostName: localhost,
ipAddress: 155.217.19.151,
portDetails: {
RATIS: 0,
REST: 0,
STANDALONE: 1
},
uuid: 74737b50-7b2b-448b-8a72-f2c6c6c77e4a
}`
> HDDS-1473. DataNode ID file should be human readable.

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneClientUtils.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
+ @hanishakoneru 
KeyOutputStream correctly does the handleWrite() from inside the retry so only the correct setting for the fixed delay between retries needs to be set appropriately.
> HDDS-1464. Client should have different retry policies for different exceptions.

- hadoop-ozone/common/src/main/bin/ozone
We use GRPC protocol for rpc communication in Ratis. By default thread caches are generated even for non-netty threads. This Jira aims to add a default JVM parameter for disabling thread caches for non-netty threads in datanode ratis server.
> HDDS-1503. Reduce garbage generated by non-netty threads in datanode ratis server

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/jni_helper.c
Fixes a bug in `jni_helper.c` `getJNIEnv` introduced by HDFS-14304. After HDFS-14304, the `getJNIEnv` would call `getGlobalJNIEnv` and pass the result to `jclasses.c` without first checking if the result of `getGlobalJNIEnv` is `NULL`.
Testing:
* Ran all libhdfs tests locally, they all pass.
> HDFS-14482: Crash when using libhdfs with bad classpath

- hadoop-ozone/dev-support/intellij/install-runconfigs.sh
- hadoop-ozone/dev-support/intellij/log4j.properties
- hadoop-ozone/dev-support/intellij/ozone-site.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/Datanode.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/FreonStandalone.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/OzoneManager.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/OzoneManagerInit.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/OzoneShell.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/Recon.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/S3Gateway.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/StorageContainerManager.xml
- hadoop-ozone/dev-support/intellij/runConfigurations/StorageContainerManagerInit.xml
Sometimes I need to start ozone cluster from intellij to debug issues. It's possible but it requires to create many runConfiguration object inside my IDE.
I propose here to share the intellij specific runtimeConfigs to make it easy for anybody (who uses intellij) to run full ozone cluster from the IDE (1 datanode only).
See: https://issues.apache.org/jira/browse/HDDS-1522
> HDDS-1522. Provide intellij runConfiguration for Ozone components

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
The modification here is to load id file as yaml and if that fails, log the exception and load as protobuf.
The case where yaml file is corrupted, we would still throw an exception after trying to load protobuf with the error in the log file.
> HDDS-1527. HDDS Datanode start fails due to datanode.id file read error

- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBStore.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rest/RestClient.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFileStatus.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/fs/OzoneManagerFS.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
- hadoop-ozone/ozonefs/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java
- hadoop-ozone/ozonefs/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
Currently in listStatus we make multiple getFileStatus calls. This can be optimized by converting to a single rpc call for listStatus.
Also currently listStatus has to traverse a directory recursively in order to list its immediate children. This happens because in OzoneManager all the metadata is stored in rocksdb sorted on keynames. The Jira also aims to fix this by using seek api provided by rocksdb.
> HDDS-1461. Optimize listStatus api in OzoneFileSystem

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/ContainerCache.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueBlockIterator.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerReader.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerHelper.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java
https://issues.apache.org/jira/browse/HDDS-1449
The JVM exit was happening because the db instance was being closed while the other thread was adding a key to the db.
> HDDS-1449. JVM Exit in datanode while committing a key. Contributed by Mukul Kumar Singh.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocolPB/SCMSecurityProtocolClientSideTranslatorPB.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocolPB/SCMSecurityProtocolServerSideTranslatorPB.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
- hadoop-hdds/common/src/main/proto/SCMSecurityProtocol.proto
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/CertificateClientTestImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
(cherry picked from commit 7254bf06e66deaf4dd9d00e65fc8894bd869a797)
> HDDS-1065. OM and DN should persist SCM certificate as the trust root. Contributed by Ajay Kumar.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/helpers/DoubleBufferEntry.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/helpers/package-info.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMBucketCreateResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMBucketDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMClientResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMVolumeCreateResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMVolumeDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/package-info.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithDummyResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
1. In this Jira added double buffer implementation. (Not integrated to OM, this will be done in further jira's)
2. Added a few response classes to give an idea, how this will be integrated with OM.
> HDDS-1512. Implement DoubleBuffer in OzoneManager.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
As rocksdb - db.delete(key) when the key does not exist does nothing, it does not throw an exception.
First we should get and then call delete. 
As now for every block delete, we do two 2 db operations. get and then delete. If we want to avoid get(), we can directly call delete, and remove this test. But with this approach, deleteBlock can be called with some randomBlockId's and the user will not know whether this block exists, and we deleted it. (As we don't throw an exception.) So, not taken this approach.
> HDDS-1602. Fix TestContainerPersistence#testDeleteBlockTwice.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java
The test fails intermittently. The link to the test report can be found below.
https://builds.apache.org/job/PreCommit-HDDS-Build/2582/testReport/
```
java.lang.AssertionError: Container is not replicated to the destination datanode
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:621)
at org.apache.hadoop.ozone.container.TestContainerReplication.testContainerReplication(TestContainerReplication.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
> HDDS-1341. TestContainerReplication#testContainerReplication fails intermittently

- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/RocksDBStore.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/RocksDBStoreMBean.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/DBStoreBuilder.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBStore.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/utils/TestRocksDBStoreMBean.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/PrometheusMetricsSink.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/TestPrometheusMetricsSink.java
RocksDB statistics need to sinked to hadoop-metrics2 for Ozone Manager to understand how OM behaves under heavy load.
Example: "rocksdb.bytes.written"
> HDDS-1568 : Add RocksDB metrics to OM.

- hadoop-ozone/dist/src/main/compose/ozone-mr/.env
- hadoop-ozone/dist/src/main/compose/ozone-mr/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozone-mr/docker-config
- hadoop-ozone/dist/src/main/compose/ozone-mr/test.sh
- hadoop-ozone/dist/src/main/smoketest/createmrenv.robot
- hadoop-ozone/dist/src/main/smoketest/mapreduce.robot
We had multiple problems earlier with the classpath separation and the internal ozonefs classloader. Before fixing all the issues I propose to create a smoketest to detect if the classpath separation is broken again .
As a first step I created an smoketest/ozone-mr environment (based on the  work of [~xyao], which is secure) and a smoketest 
Possible follow-up works:
* Adapt the test.sh for the ozonesecure-mr
* Include test runs with older hadoop versions 
See: https://issues.apache.org/jira/browse/HDDS-1607
> HDDS-1607. Create smoketest for non-secure mapreduce example

- hadoop-ozone/dist/pom.xml
Ozone tar file creation is a very time consuming step. I propose to make it optional and create the tar file only if the dist profile is enabled (-Pdist)
The tar file is not required to test ozone as the same content is available from hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT which is enough to run docker-compose pseudo clusters, smoketests. 
If it's required, the tar file creation can be requested by the dist profile.
On my machine (ssd based) it can cause 5-10% time improvements as the tar size is ~500MB and it requires a lot of IO.
See: https://issues.apache.org/jira/browse/HDDS-1629
> HDDS-1629. Tar file creation can be optional for non-dist builds

- hadoop-ozone/dist/src/main/compose/ozone/test.sh
- hadoop-ozone/dist/src/main/smoketest/auditparser/auditparser.robot
In HDDS-1518 we modified the location of the var and config files inside the container.
There are three problems with the current auditparser smokest:
1. The default audit log4j files are not part of the new config directory (fixed with HDDS-1630)
2. The smoketest is executed in scm container instead of om
3. The log directory is hard coded
The 2 and 3 will be fined in this patch. 
See: https://issues.apache.org/jira/browse/HDDS-1631
> HDDS-1631. Fix auditparser smoketests

- hadoop-ozone/csi/pom.xml
CSI server can't be started because an ClassNotFound exception.
It turned out that with using the new configuration api we got old netty jar files as transitive dependencies. (hdds-configuration depends on hadoop-common, hadoop-commons depends on the word)
We should exclude all the old netty version from the classpath of the CSI server.
See: https://issues.apache.org/jira/browse/HDDS-1641
> HDDS-1641. Csi server fails because transitive Netty dependencies

- hadoop-hdds/pom.xml
- hadoop-ozone/dist/pom.xml
- hadoop-ozone/pom.xml
1. Classpath files are plain text files which are generatede for each ozone projects. Classpath files are used to defined the classpath of a module (om, scm, etc) based on the maven classpath.
Example classpath file:
{code}
classpath=$HDDS_LIB_JARS_DIR/kerb-simplekdc-1.0.1.jar:$HDDS_LIB_JARS_DIR/hk2-utils-2.5.0.jar:$HDDS_LIB_JARS_DIR/jackson-core-2.9.5.jar:$HDDS_LIB_JARS_DIR/ratis-netty-0.4.0-fe2b15d-SNAPSHOT.jar:$HDDS_LIB_JARS_DIR/protobuf-java-2.5.0.jar:... 
{code}
Classpath files are maven artifacts and copied to share/ozone/classpath in the distribution
2. 0.4.0 was the first release when we deployed the artifacts to the apache nexus. [~ajayydv] reported the problem that the staging repository can't be closed: INFRA-18344
It turned out that the classpath files are uploaded with jar …
> HDDS-1510. Classpath files are deployed to the maven repository as pom/jar files

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
https://issues.apache.org/jira/browse/HDDS-1621
2 changes:
1. invoking a force+close on the channel inside writeData if dfs.container.chunk.write.sync is true. The force is triggered outside of the file lock, to avoid unnecessary lock contention.
2. change AsynchronousFileChannel to FileChannel for writing the file. This is the right thing to do because writeStateMachineData is already scheduling the write chunk requests asynchronously on threads from XceiverServerRatis.chunkExecutor.
> HDDS-1621. writeData in ChunkUtils should not use AsynchronousFileChannel. Contributed by Supratim Deka

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/AuditLogger.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/RequestAuditor.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java
In this Jira, we shall implement audit logging for OM HA Bucket write requests.
As now we cannot use userName,  IpAddress from Server API's as these will be null, because the requests are executed under GRPC context. So, in our AuditLogger API's we need to pass username and remoteAddress which we can get from request after HDDS-1600 and use these during audit logging.
> HDDS-1605. Implement AuditLogging for OM HA Bucket write requests.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestChunkInputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumData.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/storage/DistributedStorageHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestChunkStreams.java
Partial chunk reads and checksum verifications
> HDDS-1496. Support partial chunk reads and checksum verification

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azure/AzureNativeFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystem.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/HttpQueryParams.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/AzureADAuthenticator.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStream.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/utils/SSLSocketFactoryEx.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/AbstractAbfsIntegrationTest.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemBackCompat.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemFileStatus.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemFinalize.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemFlush.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemInitAndCreate.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemListStatus.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemMainOperation.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemRandomRead.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestWasbAbfsCompatibility.java
This chain of cherrypicked patches from trunk fills out branch-3.2 with those changes which aren't there. It doesn't (yet) include the delegation token work because that change also does some POM changes to import bouncy-castle which would create build problems unless I changed it.
As these patches are already in trunk, this PR doesn't need voting on, it's a due diligence to make sure yetus is happy, and to give people who care an opportunity to suggest changes.
> HADOOP-16353. Backport ABFS changes from trunk to branch-3.2

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/ContainerOperationClient.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestChunkInputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/StringCodec.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/TracingUtil.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerStateMachineIdempotency.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestContainerSmallFile.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestGetCommittedBlockLengthAndPutKey.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientManager.java
- hadoop-ozone/objectstore-service/src/main/java/org/apache/hadoop/ozone/web/storage/DistributedStorageHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestChunkStreams.java
Recently a new exception become visible in the datanode logs, using standard freon (STANDLAONE)
{code}
datanode_2  | 2019-06-03 12:18:21 WARN  PropagationRegistry$ExceptionCatchingExtractorDecorator:60 - Error when extracting SpanContext from carrier. Handling gracefully.
datanode_2  | io.jaegertracing.internal.exceptions.MalformedTracerStateStringException: String does not match tracer state format: 7576cabf-37a4-4232-9729-939a3fdb68c4WriteChunk150a8a848a951784256ca0801f7d9cf8b_stream_ed583cee-9552-4f1a-8c77-63f7d07b755f_chunk_1
datanode_2  | 	at org.apache.hadoop.hdds.tracing.StringCodec.extract(StringCodec.java:49)
datanode_2  | 	at org.apache.hadoop.hdds.tracing.StringCodec.extract(StringCodec.java:34)
datanode_2  | 	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExt …
> HDDS-1636. Tracing id is not propagated via async datanode grpc call

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
Change-Id: Idf91e6367cf1a6e27986034e13cf34f59e79fc25
Redundant toString() call for variable metadataPath at:
https://github.com/apache/hadoop/blob/trunk/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java#L284
> HDDS-1655. Redundant toString() call for metaDataPath in KeyValueContainerCheck

- hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
- hadoop-ozone/dist/src/main/dockerbin/entrypoint.sh
- hadoop-ozone/dist/src/main/dockerbin/envtoconf.py
- hadoop-ozone/dist/src/main/dockerbin/transformation.py
During an offline discussion with [~eyang] and [~arp], Eric suggested to maintain the source of the docker specific start images inside the main ozone branch (trunk) instead of the branch of the docker image.
With this approach the ozone-runner image can be a very lightweight image and the entrypoint logic can be versioned together with the ozone itself.
An other use case is a container creation script. Recently we [documented|https://cwiki.apache.org/confluence/display/HADOOP/Ozone+Docker+images] that hadoop-runner/ozone-runner/ozone images are not for production (for example because they contain development tools).
We can create a helper tool (similar what Spark provides) to create Ozone container images from any production ready base image. But this tool requires the existence of the …
> HDDS-1635. Maintain docker entrypoint and envtoconf inside ozone project

- hadoop-ozone/dist/src/main/smoketest/auditparser/auditparser.robot
When I tried to reproduce a problem which is reported by [~eyang], I found that the auditparser robot test uses the /opt/hadoop directory as a working directory to generate the audit.db export.
/opt/hadoop is may or may not be writable, it's better to use /tmp instead.
See: https://issues.apache.org/jira/browse/HDDS-1677
> HDDS-1677. Auditparser robot test shold use a world writable working directory

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java
I started to execute all the unit tests continuously (in kubernetes with argo workflow).
Until now I got the following failures (number of failures / unit test name):
```
1 org.apache.hadoop.fs.ozone.contract.ITestOzoneContractMkdir
1 org.apache.hadoop.fs.ozone.contract.ITestOzoneContractRename
3 org.apache.hadoop.hdds.scm.container.placement.algorithms.TestSCMContainerPlacementRackAware
31 org.apache.hadoop.ozone.container.common.TestDatanodeStateMachine
31 org.apache.hadoop.ozone.container.common.volume.TestVolumeSet
1 org.apache.hadoop.ozone.freon.TestDataValidateWithSafeByteOperations
```
TestVolumeSet is also failed locally:
{code}
2019-06-13 14:23:18,637 ERROR volume.VolumeSet (VolumeSet.java:initializeVolumeSet(184)) - Failed to parse the storage location: …
> HDDS-1680. Create missing parent directories during the creation of HddsVolume dirs

- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerKeyService.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ContainerDBServiceProvider.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ContainerDBServiceProviderImpl.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerKeyService.java
This PR adds support for limit query param to limit the results of /api/containers and /api/containers/{id} endpoints. This will help the UI to load and show results faster with infinite scrolling.
> HDDS-1670. Add limit support to /api/containers and /api/containers/{id} endpoints

- hadoop-hdds/common/pom.xml
In RocksDb 6.0.1, some useful tuning features were brought into the JNI API. We need to upgrade the version in ozone to pick those up.
https://github.com/facebook/rocksdb/pull/4833
> Update RocksDB version to 6.0.1

- hadoop-ozone/ozone-recon/pom.xml
Currently, hadoop-ozone-recon node_modules folder is copied to target folder and this takes a lot of time while building hadoop-ozone project. 
This PR reduces the build time by excluding node_modules folder. With this patch it only takes approximately ~10 seconds to compile Recon.
> HDDS-1702. Optimize Ozone Recon build time

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
https://issues.apache.org/jira/browse/HDDS-1454
Problem:
In a MiniOzoneChaosCluster run it was observed that events like GC pauses or any other pauses in SCM can mark all the datanodes as stale in SCM. This will trigger multiple pipeline destroy and will render the system unusable.
Solution:
Added a timestamp check in NodeStateManager. If the heartbeat task detects a long scheduling delay since the last time it ran, then the task skips doing health checks and node state transitions in the current iteration.
Test:
The unit test simulates a JVM pause by simply pausing the iterations of the health check task. Once the health check task is "unpaused", the system condition will be similar to a JVM pause. The test asserts that any node with heartbeats should not transition to Stale or Dead …
> HDDS-1454. GC other system pause events can trigger pipeline destroy for all the nodes in the cluster. Contributed by Supratim Deka

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
While testing out ozone with long running clients which continuously write data, it was noted ratis logs were rolled 1-2 times every second. This adds unnecessary overhead to the pipeline thereby affecting write throughput. Increasing the size of the log segment to 1MB will decrease the overhead.
> HDDS-1719 : Increase ratis log segment size to 1MB.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/shortcircuit/ShortCircuitCache.java
…lementException
Signed-off-by: sunlisheng <sunlisheng@xiaomi.com>
> HDFS-14541. When evictableMmapped or evictable size is zero, do not throw NoSuchElementException

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/LockManager.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLockUtil.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/package-info.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/package-info.java
Thank You @anuengineer for offline discussion and help during the code of using Short and bit manipulation, instead of BitSet.
If someone is interested in how the code looks like with BitSet, refer below link.
https://github.com/bharatviswa504/hadoop-1/blob/bhcode-anucode/hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock1.java
> HDDS-1723. Create new OzoneManagerLock class.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLockUtil.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
In this Jira, we shall use generate Resourcename from actual resource names like volume/bucket/user/key inside OzoneManagerLock. In this way, users using these locking API's no need to worry of calling these additional API of generateResourceName in OzoneManagerLockUtil. And this also reduces code during acquiring locks in OM operations.
> HDDS-1727. Use generation of resourceName for locks in OzoneManagerLock.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/RDBTable.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/utils/db/TestRDBStore.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManager.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java
RDBTable#isExist can use Rocksdb#keyMayExist, this avoids the cost of reading the value for the key.
Please refer, 
https://github.com/facebook/rocksdb/blob/7a8d7358bb40b13a06c2c6adc62e80295d89ed05/java/src/main/java/org/rocksdb/RocksDB.java#L2184
> HDDS-1691 : RDBTable#isExist should use Rocksdb#keyMayExist

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/federation/policies/AbstractConfigurableFederationPolicy.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/federation/policies/amrmproxy/LocalityMulticastAMRMProxyPolicy.java
There are some typo in LocalityMulticastAMRMProxyPolicy.java and AbstractConfigurableFederationPolicy.java
> YARN-9661. Fix typos in LocalityMulticastAMRMProxyPolicy and AbstractConfigurableFederationPolicy

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineUtils.java
RaftClient references are being leaked while removing pipeline.
> HDDS-1616. ManagedChannel references are being leaked in while removing RaftGroup. Contributed by Mukul Kumar Singh.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
This patch adds key deletion and replication manager capability to MiniOzoneChaosCluster.
> HDDS-1758. Add replication and key deletion tests to MiniOzoneChaosCluster. Contributed by Mukul Kumar Singh.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSImageFormatProtobuf.java
Signed-off-by: sunlisheng <sunlisheng@xiaomi.com>
> HDFS-13694. Making md5 computing being in parallel with image loading.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/CSMMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
This jira adds metrics around leaders latency for pipeline operations.
> HDDS-1728. Add metrics for leader's latency in ContainerStateMachine. Contributed by Mukul Kumar Singh.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStore.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3Guard.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestAuthoritativePath.java
This addresses whitespace nits from Gabor's review of https://github.com/apache/hadoop/pull/1043, and allows non-qualified paths to be specified in the config.
> HADOOP-16409. Allow authoritative mode on non-qualified paths.

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineMetrics.java
This Jira aims to add block allocation metrics for pipelines in SCM. This would help in determining the distribution of block allocations among various pipelines in SCM.
> HDDS-1750. Add block allocation metrics for pipelines in SCM

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/container-service/src/main/proto/StorageContainerDatanodeProtocol.proto
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
https://issues.apache.org/jira/browse/HDDS-1603
The scope of this jira is to build on https://issues.apache.org/jira/browse/RATIS-573
and define the handling for Ratis log append failure in Ozone Container State Machine.
1. Enqueue pipeline unhealthy action to SCM, add a reason code to the message.
2. Trigger immediate heartbeat to SCM
Ratis-573 is not available in trunk. So this patch starts with an entry point in XceiverServerRatis which will be hooked up to notifyLogFailed() callback defined in StateMachine as part of RATIS-573.
Notify Ratis volume unhealthy to the Datanode is not implemented in this patch
> HDDS-1603. Handle Ratis Append Failure in Container State Machine. Contributed by Supratim Deka

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
https://issues.apache.org/jira/browse/HDDS-1748
Added logs to print pipeline id, block id and datanode addresses when 3 way commit failure is encountered
in watchForCommit.
> HDDS-1748. Error message for 3 way commit failure is not verbose. Contributed by Supratim Deka

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Container.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerScrubber.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scrubber/TestDataScrubber.java
The previous patch for this jira did not implement the logic completely. Also there was no integration test to verify end-to-end functionality. Both these issues have been fixed as part of this change.
> [HDDS-1201] Reporting corrupted containers info to SCM

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
`SCMNodeManager` sets the HostName and IpAddress to the response of register command, but that is being ignored in `SCMDatanodeProtocolServer` while sending the response back to the datanode.
> HDDS-1784. Missing HostName and IpAddress in the response of register command.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
https://issues.apache.org/jira/browse/HDDS-1754
DeadNodeHandler can clean up the pipeline while containers are still in CLOSING state.
modified getContainerWithPipeline() to refer the pipeline only if the container is in OPEN state.
In CLOSING state, the read pipeline will be constructed from the Replicas known to SCM - this is already existing behavior for CLOSED state.
> HDDS-1754. getContainerWithPipeline fails with PipelineNotFoundException. Contributed by Supratim Deka

- hadoop-ozone/dev-support/checks/acceptance.sh
- hadoop-ozone/dev-support/checks/author.sh
- hadoop-ozone/dev-support/checks/build.sh
- hadoop-ozone/dev-support/checks/checkstyle.sh
- hadoop-ozone/dev-support/checks/findbugs.sh
- hadoop-ozone/dev-support/checks/integration.sh
- hadoop-ozone/dev-support/checks/isolation.sh
- hadoop-ozone/dev-support/checks/rat.sh
- hadoop-ozone/dev-support/checks/shellcheck.sh
- hadoop-ozone/dev-support/checks/unit.sh
hadoop-ozone/dev-support/checks directory contains multiple helper script to execute different type of testing (findbugs, rat, unit, build).
They easily define how tests should be executed, with the following contract:
 * The problems should be printed out to the console
 * in case of test failure a non zero exit code should be used
 
The tests are working well (in fact I have some experiments with executing these scripts on k8s and argo where all the shell scripts are executed parallel) but we need some update:
 1. Most important: the unit tests and integration tests can be separated. Integration tests are more flaky and it's better to have a way to run only the normal unit tests
 2. As HDDS-1115 introduced a pom.ozone.xml it's better to use them instead of the magical "am pl …
> HDDS-1735. Create separate unit and integration test executor dev-support script

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
The last applied term index wasn't updated as the method is called by multiple executors and the method was not synchronized.
> HDDS-1766. ContainerStateMachine is unable to increment lastAppliedTermIndex. Contributed by  Mukul Kumar Singh.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
We set size as below
final long size = args.getDataSize() >= 0 ?
args.getDataSize() : scmBlockSize;
and create OmKeyInfo with below size set. But when allocating Block for openKey, we use as below.
allocateBlockInKey(keyInfo, args.getDataSize(), currentTime);
I feel here, we should use size which is set above so that we allocate at least a block when the openKey call happens.
Current Code also works fine, but for readability I believe this should be good.
> HDDS-1666. Issue in openKey when allocating block.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
This change will make delete container an idempotent operation in datanode.
> HDDS-1756. DeleteContainerCommandHandler fails with NPE.

- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
Currently BasicOzoneFileSystem#mkdir does not have the optimizations made in HDDS-1300. The changes for this function were missed in HDDS-1460.
> HDDS-1481: Cleanup BasicOzoneFileSystem#mkdir

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
Currently ContainerStateMachine uses the executors provided by XceiverServerRatis for executing applyTransaction calls. This would result in two or more ContainerStateMachine to share the same set of executors. Delay or load in one ContainerStateMachine would adversely affect the performance of other state machines in such a case. It is better to have separate set of executors for each ContainerStateMachine.
> HDDS-1767: ContainerStateMachine should have its own executors for executing applyTransaction calls

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMCommonPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java
NPE is caused by base `chooseDatanodes` not checking for `excludedNodes` being `null`.  Default placement policy is now random (HDDS-1801), but `TestContainerPlacementFactory#testDefaultPolicy` still reflects rack-aware policy.  Adding the `null` check makes the test fail instead of erroring out with NPE.
Changed the test to only check default policy being returned, not its behavior (since that should be verified in the specific policy's unit test).
https://issues.apache.org/jira/browse/HDDS-1822
Unit test.
> HDDS-1822. NPE in SCMCommonPolicy.chooseDatanodes

- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/fsdatainputstreambuilder.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/performance.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/troubleshooting_s3a.md
This PR fixes a typo in the Hadoop documentation: `fs.s3a.experimental.fadvise` should be `fs.s3a.experimental.input.fadvise` (the `.input` was missing previously).
> HADOOP-16437 documentation typo fix: fs.s3a.experimental.fadvise -> fs.s3a.experimental.input.fadvise

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/package-info.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3InitiateMultipartUploadResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/package-info.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerHARequestHandlerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/package-info.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3InitiateMultipartResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3InitiateMultipartUploadResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/package-info.java
First commit is S3 DeleteBucket request.
Posted for initial CI, once HDDS-1795 gets in, will rebase this.
> HDDS-1805. Implement S3 Initiate MPU request to use Cache and DoubleBuffer.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerHAProtocol.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OzoneManagerSnapshotProvider.java
> HDDS-1649. On installSnapshot notification from OM leader, download checkpoint and reload OM state

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Currently the list of nodes returned by SCM are static and are returned in the same order to all the clients. Ideally these should be sorted by the network topology and then returned to client.
However even when network topology in not available, then SCM/client should randomly sort the nodes before choosing the replica's to connect.
> HDDS-1749 : Ozone Client should randomize the list of nodes in pipeline for reads

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
https://issues.apache.org/jira/browse/HDDS-1864.
> HDDS-1864. Turn on topology aware read in TestFailureHandlingByClient.

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
[WARNING] /Users/xx/tmp/idea/hadoop-3.2.0-src/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c:3033:/Users/xx/tmp/idea/hadoop-3.2.0-src/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c:3033:4949::  warningwarning: : incompatible pointer types passing 'tOffset *' (aka 'long long *') to parameter of type 'jlong *' (aka 'long *') [-Wincompatible-pointer-types]incompatible pointer types passing 'tOffset *' (aka 'long long *') to parameter of type 'jlong *' (aka 'long *') [-Wincompatible-pointer-types]
> HDFS-14425:Native build fails on macos due to jlong in hdfs.c

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneObjInfo.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
Let ACL check allow access for non-existent parent key instead of failing with "key not found".  Since the key does not exist, no ACL can be associated.  Actual access right will be determined based on volume, bucket and prefix ACLs.
https://issues.apache.org/jira/browse/HDDS-1834
Ran `ozonesecurity` and `ozonefs` smoketests in `ozonesecure` environment.
> HDDS-1834. parent directories not found in secure setup due to ACL check

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
ContainerStateMachine should limit number of pending apply transactions in order to avoid excessive heap usage by the pending transactions.
> HDDS-1816: ContainerStateMachine should limit number of pending apply transactions

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/HttpServer2.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/PrometheusServlet.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/sink/PrometheusMetricsSink.java
- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/metrics2/sink/TestPrometheusMetricsSink.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/BaseHttpServer.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-16398
> HADOOP-16398. Exports Hadoop metrics to Prometheus

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
https://issues.apache.org/jira/browse/HDDS-1882
> HDDS-1882. TestReplicationManager failed with NPE in ReplicationManager

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/JsonUtil.java
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/WebHDFS.md
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestJsonUtil.java
Added a unit test for `JsonUtil#toJsonString(ContentSummary)`.
Amended WebHDFS doc.
Tested locally.
When the ecPolicy is empty, the request would just return empty string, i.e. `ecPolicy: ""`.
> HDFS-14683. WebHDFS: Add erasureCodingPolicy field to GETCONTENTSUMMARY response

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/JsonUtilClient.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/client/HttpFSFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/FSOperations.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/client/BaseTestHttpFSWith.java
Modified existing unit test to verify the validity of the fix. Without the fix, the modified unit test WILL fail. Tested locally.
> HDFS-14686. HttpFS: HttpFSFileSystem#getErasureCodingPolicy always returns null

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/resourceplugin/fpga/FpgaDiscoverer.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/resourceplugin/gpu/GpuDiscoverer.java
Recreated a PR, hope this time yetus will pick it up.
The change is straightforward, check [upstream jira](https://issues.apache.org/jira/browse/YARN-9375).
> YARN-9375. Use Configured in GpuDiscoverer and FpgaDiscoverer

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Fix checkstyle error due to too long line.
Unfortunately at 71 characters `DFS_CONTAINER_RATIS_STATEMACHINE_MAX_PENDING_APPLY_TRANSACTIONS_DEFAULT` is too long for the 80-char limit even with static imports, so it has to be shortened.  I figured that `RATIS` would be the least useful part, implied by `STATEMACHINE`, so I removed that.
https://issues.apache.org/jira/browse/HDDS-1878
```
$ mvn -Phdds -DskipTests -am -pl :hadoop-hdds-container-service clean package
$ ./hadoop-ozone/dev-support/checks/checkstyle.sh
```
> HDDS-1878. checkstyle error in ContainerStateMachine

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineActionHandler.java
> HDDS-1832 : Improve logging for PipelineActions handling in SCM and datanode.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/LocalMetadataStore.java
Moved the setter and addAncestors to synchronized
Untested! Let's see what findbugs says first
> HADOOP-16472. findbugs warning on LocalMetadataStore.ttlTimeProvider sync

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-image/docker-krb5/Dockerfile-krb5
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-image/docker-krb5/Dockerfile-krb5
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ConfigurationProvider.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ReconControllerModule.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
Recon fails to come up in a secure cluster with the following error:
```
Failed startup of context o.e.j.w.WebAppContext@2009f9b0{/,file:///tmp/jetty-0.0.0.0-9888-recon-_-any-2565178148822292652.dir/webapp/,UNAVAILABLE}{/recon} javax.servlet.ServletException: javax.servlet.ServletException: Principal not defined in configuration at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.init(KerberosAuthenticationHandler.java:188) at
```
This patch addresses this issue and enables Recon to come up in clusters secured by kerberos. I have manually tested the patch by creating the recon jar and replacing an old jar in a live secure CM deployed cluster and verified that Recon starts successfully and is able to login successfully with the kerberos ticket. Also updated …
> HDDS-1788. Fix kerberos principal error in Ozone Recon

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/PrometheusMetricsSink.java
1. Fix `ConcurrentModification` due to plain `HashMap`
2. Improve string building a bit
https://issues.apache.org/jira/browse/HDDS-1870
Ran freon in `ozoneperf` env.  Checked `/prom` endpoints.  Verified that no CME appears in logs.
> HDDS-1870. ConcurrentModification at PrometheusMetricsSink

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/CSMMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
https://issues.apache.org/jira/browse/HDDS-1798
unit test is pending. Will add the infra required for testing this change as part of https://issues.apache.org/jira/browse/HDDS-1818
writeStateMachineData() currently returns a future to Ratis. The scope of this jira is to signal any errors or failures encountered as part of the operation - WriteChunk / handleWriteChunk() to Ratis via this future. As of now, the future does not track failures.
This change is required to complete the failure handling done in HDDS-1603.
> HDDS-1798. Propagate failure in writeStateMachineData to Ratis. Contributed by Supratim Deka

- hadoop-ozone/dev-support/checks/integration.sh
- hadoop-ozone/dev-support/checks/unit.sh
Run `hadoop-ozone-tools` tests as part of `integration.sh`, not `unit.sh`.
https://issues.apache.org/jira/browse/HDDS-1918
```
$ ./hadoop-ozone/dev-support/checks/unit.sh
...
(no Ozone Tools here)
...
$ ./hadoop-ozone/dev-support/checks/integration.sh
...
[INFO] Reactor Build Order:
[INFO]
[INFO] Apache Hadoop Ozone Integration Tests                              [jar]
[INFO] Apache Hadoop Ozone FileSystem                                     [jar]
[INFO] Apache Hadoop Ozone Tools                                          [jar]
...
```
> HDDS-1918. hadoop-ozone-tools has integration tests run as unit

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementPolicyFactory.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
https://issues.apache.org/jira/browse/HDDS-1865
Change log,
1. change property name from dfs.network.topology.aware.read.enable to ozone.network.topology.aware.read
2. add  "optional bool sortDatanodes = 14;" in KeyArgs definition in OzoneManagerProtocol.proto
3. refine unit tests 
4. add more logs for future debug
> HDDS-1865. Use "ozone.network.topology.aware.read" to control both RPC client and server side logic

- hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh
- hadoop-ozone/dist/src/main/compose/testlib.sh
- hadoop-ozone/dist/src/main/smoketest/basic/basic.robot
- hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot
- hadoop-ozone/dist/src/main/smoketest/commonlib.robot
- hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
- hadoop-ozone/dist/src/main/smoketest/s3/webui.robot
Obtain Kerberos ticket for HTTP before web requests and use it for `curl`.  (Unfortunately it works only on the same host, eg. `scm` cannot make request to `om` using its own HTTP keytab.)
https://issues.apache.org/jira/browse/HDDS-1925
Ran both secure and unsecure acceptance tests.  (Some of them timed out locally...)
> HDDS-1925. ozonesecure acceptance test broken by HTTP auth requirement

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
Use random port for SCM for the test cases where it is started in `TestSecureOzoneCluster`.
https://issues.apache.org/jira/browse/HDDS-1934
```
$ cd hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone
$ docker-compose up -d
$ cd -
$ mvn -Phdds -pl :hadoop-ozone-integration-test test -Dtest=TestSecureOzoneCluster
...
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.32 s - in org.apache.hadoop.ozone.TestSecureOzoneCluster
```
> HDDS-1934. TestSecureOzoneCluster may fail due to port conflict

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ARetryPolicy.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/index.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/troubleshooting_s3a.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AConfiguration.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ADelayedFNF.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AInconsistency.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ARemoteFileChanged.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3GuardOutOfBandOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/staging/TestStagingCommitter.java
-exponential retry policy used
-retry interval = 1s
-retry attempts = 8
-docs updated
tested s3 ireland
Change-Id: I48b17af34a50b7291f2c360ee74dbce7540556b4
> HADOOP-16499. S3A retry policy to be exponential

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/package-info.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/ObjectParser.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/OMKeyAclResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/package-info.java
This patch is dependent on HDDS-1884.
Posted this PR on top of HDDS-1884.
2nd commit is the actual changes for this PR.
> HDDS-1895. Support Key ACL operations for OM HA.

- hadoop-ozone/ozone-recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/UtilizationSchemaDefinition.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerKeyService.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/api/UtilizationService.java
- hadoop-ozone/ozone-recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/AbstractOMMetadataManagerTest.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestUtilizationService.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestUtilizationSchemaDefinition.java
- hadoop-ozone/ozone-recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestFileSizeCountTask.java
- hadoop-ozone/ozone-recon/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> HDDS-1366. Add ability in Recon to track the number of small files in an Ozone Cluster

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java
Multi-block writes tests are failing most of the time because Ratis leader election timeout is about the same length as the client retry timeout (5 times 1 second).  This frequently caused an entire pipeline to be excluded (by `KeyOutputStream.handleException`) just because client gives up before leader is elected.  There are only 6 nodes in TestMultiBlockWritesWithDnFailures test, 2 of which is shut down as part of the test.  Thus, if this happens, subsequent write fails because new block cannot be allocated.
This change decreases leader election timeout and increases client retries.  It is basically an extension of [HDDS-1780](https://issues.apache.org/jira/browse/HDDS-1780).
Additional changes:
* move `testMultiBlockWritesWithIntermittentDnFailures` to …
> HDDS-1908. TestMultiBlockWritesWithDnFailures is failing

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/S3ADelegationTokens.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/SessionTokenBinding.java
Contributed by steve loughran.
Change-Id: Ifafc15f32791911976d7ebc36fb6e8853f59ed41
> HADOOP-16500 S3ADelegationTokens to only log at debug on startup

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneObj.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java
- hadoop-ozone/integration-test/src/test/resources/log4j2.properties
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
@xiaoyuyao , @ajayydv - Request you to please review this PR. Thank you.
> HDDS-1768. Audit xxxAcl methods in OzoneManager

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
prepareToEnterState in HAState is called without the context being locked.
But in NameNode#NameNode, prepareToEnterState is after haContext.writeLock()
``` java
try {
haContext.writeLock();
state.prepareToEnterState(haContext);
state.enterState(haContext);
} finally {
haContext.writeUnlock();
}
```
Is it OK?
I move `state.prepareToEnterState(haContext);` out
> HDFS-14456:HAState#prepareToEnterState neednt a lock

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/PrefixManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAddAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixRemoveAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixSetAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/package-info.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/prefix/OMPrefixAclResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/prefix/package-info.java
(cherry picked from commit 3906b7d233cd276901fc86b24d7d26d676ff985b)
> HDDS-1911. Support Prefix ACL operations for OM HA.

- hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/mapred/CopyCommitter.java
- hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/mapred/RetriableFileCopyCommand.java
- hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/util/DistCpUtils.java
- hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/mapred/TestCopyCommitter.java
- hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/util/TestDistCpUtils.java
- hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/util/TestDistCpUtilsWithCombineMode.java
[HADOOP-16158](https://issues.apache.org/jira/browse/HADOOP-16158)
Copying blocks in parallel (enabled when blocks per chunk > 0) is a great DistCp improvement that can hugely speed up copying big files. 
But its checksum validation is skipped, e.g. in `RetriableFileCopyCommand.java`
```
// isSplit() here is introduced by HADOOP-11794 and 
// used to indicate if the source data to copy is only a chunk of it 
// (consists of one or more blocks, not all).
if (!source.isSplit()) {
compareCheckSums(sourceFS, source.getPath(), sourceChecksum,
targetFS, targetPath);
}
```
and this could result in checksum/data mismatch without notifying developers/users (e.g. HADOOP-16049).
I'd like to provide a patch to add the checksum validation.
> HADOOP-16158. DistCp to support checksum validation when copy blocks in parallel

- hadoop-ozone/dist/src/main/compose/ozones3-haproxy/.env
- hadoop-ozone/dist/src/main/compose/ozones3-haproxy/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozones3-haproxy/docker-config
- hadoop-ozone/dist/src/main/compose/ozones3-haproxy/haproxy-conf/haproxy.cfg
- hadoop-ozone/dist/src/main/compose/ozones3-haproxy/test.sh
Tested it on my laptop:
```
$ docker-compose up
Creating network "ozones3-haproxy_default" with the default driver
Creating ozones3-haproxy_s3-proxy_1 ... done
Creating ozones3-haproxy_s3g3_1     ... done
Creating ozones3-haproxy_scm_1      ... done
Creating ozones3-haproxy_s3g1_1     ... done
Creating ozones3-haproxy_om_1       ... done
Creating ozones3-haproxy_s3g2_1     ... done
Creating ozones3-haproxy_datanode_1 ... done
Attaching to ozones3-haproxy_s3-proxy_1, ozones3-haproxy_om_1, ozones3-haproxy_datanode_1, ozones3-haproxy_s3g3_1, ozones3-haproxy_s3g1_1, ozones3-haproxy_scm_1, ozones3-haproxy_s3g2_1
s3-proxy_1  | [NOTICE] 226/212303 (1) : New worker #1 (6) forked
```
```
$ aws s3api --endpoint http://localhost:8081 create-bucket --bucket b12346
{
"Location": …
```
> HDDS-1972. Provide example ha proxy with multiple s3 servers back end.

- hadoop-hdfs-project/hadoop-hdfs/src/main/proto/fsimage.proto
There is a minor spell mistake on line number 100, where future is misspelled as "futute" under "message AclFeatureProto" section.
Here is code snippet:
message AclFeatureProto {
/**
* An ACL entry is represented by a 32-bit integer in Big Endian
* format. The bits can be divided in four segments:
* [0:2) || [2:26) || [26:27) || [27:29) || [29:32)
*
* [0:2) -- reserved for future uses.
* [2:26) -- the name of the entry, which is an ID that points to a
* string in the StringTableSection.
* [26:27) -- the scope of the entry (AclEntryScopeProto)
* [27:29) -- the type of the entry (AclEntryTypeProto)
* [29:32) -- the permission of the entry (FsActionProto)
*
*/
repeated fixed32 entries = 2 [packed = true];
}
message AclFeatureProto {
/**
* An ACL entry is represented by a 32-bit integer in …
> Minor spell mistake in comment : Line number 101

- hadoop-hdds/server-scm/src/main/resources/webapps/scm/index.html
- hadoop-ozone/dist/src/main/smoketest/basic/basic.robot
- hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/index.html
- hadoop-ozone/s3gateway/src/main/resources/browser.html
- hadoop-ozone/s3gateway/src/main/resources/webapps/static/index.html
Update bootstrap/jquery version references in SCM/OM/S3G and in acceptance test.
https://issues.apache.org/jira/browse/HDDS-1999
Ran `basic.robot` in `ozones3` compose folder.
Checked SCM/OM/S3G web UI visually.
> HDDS-1999. Basic acceptance test and SCM/OM web UI broken by Bootstrap upgrade

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSImage.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSImageFormatPBINode.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSImageFormatProtobuf.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/FSImageFormatPBSnapshot.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/FSImageTestUtil.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSImage.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSImageWithSnapshot.java
Initial code I used to perform my benchmarks for the above change. There are two parts to the change:
1) The code used to write the sub-sections to the image, which is fairly simple.
2) The code used to process the sub-sections in parallel. As much as possible this reuses the original code in multiple threads, but the inodeDirectory code needed to be moved around a bit to avoid synchronization issues.
The only sections with parallel loading so far are inode and inodeDirectory.
So far, there are no new tests for this feature. That is something I need to look into further if we agree this is a good change to move forward with.
> HDFS-14617 - Improve fsimage load time by writing sub-sections to the fsimage index

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java
* Increase timeout of the test cases (both of them are prone to intermittent timeout).  Rationale: (1) there is already a timeout on `waitForPipelines()`, which was increased in `0d62753da96` without increasing overall test timeout, (2) test timeout needs to account for mini cluster startup.
* Fix typo in class name.
https://issues.apache.org/jira/browse/HDDS-1808
Ran the test several times.  It passed in all cases.  It took as long as 77 seconds in one case, so one of the two test cases would have failed with the original 30 second timeout.
> HDDS-1808. TestRatisPipelineCreateAndDestory times out

- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/HeaderPreprocessor.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayHttpServer.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/VirtualHostStyleFilter.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestAbortMultipartUpload.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestInitiateMultipartUpload.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestListParts.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java
This problem is reported offline by [~shanekumpf@gmail.com].
When aws-sdk-go is used to access to s3 gateway of Ozone it sends the Multi Part Upload initialize message with "application/octet-stream" Content-Type. 
This Content-Type is missing from the aws-cli which is used to reimplement s3 endpoint.
The problem is that we use the same rest endpoint for initialize and complete Multipart Upload request. For the completion we need the CompleteMultipartUploadRequest parameter which is parsed from the body.
For initialize we have an empty body which can't be serialized to CompleteMultipartUploadRequest.
The workaround is to set a specific content type from a filter which help up to create two different REST method for initialize and completion message.
Here is an example to test (using bogus …
> HDDS-1948. S3 MPU can't be created with octet-stream content-type 

- hadoop-common-project/hadoop-auth/src/main/java/org/apache/hadoop/security/authentication/server/KerberosAuthenticationHandler.java
- hadoop-common-project/hadoop-auth/src/test/java/org/apache/hadoop/security/authentication/server/TestKerberosAuthenticationHandler.java
- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-16527
> HADOOP-16527. Add a whitelist of endpoints to skip Kerberos authentication

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SimpleContainerDownloader.java
Remove unused executor from `SimpleContainerDownloader`.
https://issues.apache.org/jira/browse/HDDS-1941
> HDDS-1941. Unused executor in SimpleContainerDownloader

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNode.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/metrics/DataNodePeerMetrics.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDataNodePeerMetrics.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/metrics/TestDataNodeOutlierDetectionViaMetrics.java
Signed-off-by: sunlisheng <sunlisheng@xiaomi.com>
> HDFS-14748. Make DataNodePeerMetrics#minOutlierDetectionSamples configurable

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
Add `hdds.container.chunk.persistdata` as an exception in `TestOzoneConfigurationFields` to fix its [failure](https://github.com/elek/ozone-ci/blob/master/trunk/trunk-nightly-20190830-rr75b/integration/hadoop-ozone/integration-test/org.apache.hadoop.ozone.TestOzoneConfigurationFields.txt).
https://issues.apache.org/jira/browse/HDDS-2061
```
$ mvn -am -Phdds -pl :hadoop-ozone-integration-test -DfailIfNoTests=false clean test -Dtest=TestOzoneConfigurationFields
...
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.36 s - in org.apache.hadoop.ozone.TestOzoneConfigurationFields
```
> HDDS-2061. Add hdds.container.chunk.persistdata as exception to TestOzoneConfigurationFields

- hadoop-assemblies/src/main/resources/assemblies/hadoop-src.xml
- pom.xml
When we do source package of hadoop, it should not contain submarine project/code.
> HADOOP-16534. Exclude submarine from hadoop source build.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
…on.critical.threshold and hdds.datanode.storage.utilization.warning.threshold are not reasonable.
https://issues.apache.org/jira/browse/HDDS-2069?filter=-1
> HDDS-2069. Default values of properties hdds.datanode.storage.utilization.{critical | warning}.threshold are not reasonable

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
- hadoop-hdds/pom.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
- hadoop-ozone/pom.xml
Right now, if a pipeline is destroyed by SCM, all the container on the pipeline are marked as quasi closed when datanode received close container command. SCM while processing these containers reports, marks these containers as closed once majority of the nodes are available.
This is however not a sufficient condition in cases where the raft log directory is missing or corrupted. As the containers will not have all the applied transaction. 
To solve this problem, we should QUASI_CLOSE the containers in datanode as part of ratis groupRemove. If a container is in OPEN state in datanode without any active pipeline, it will be marked as Unhealthy while processing close container command.
> HDDS-1561: Mark OPEN containers as QUASI_CLOSED as part of Ratis groupRemove

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementPolicyFactory.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementCapacity.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRandom.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMPlacementMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/placement/TestContainerPlacement.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMContainerPlacementPolicyMetrics.java
https://issues.apache.org/jira/browse/HDDS-1553.
Initial patch
> HDDS-1553. Add metrics in rack aware container placement policy.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerFactory.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
We have a hard-coded config key in the ChunkManagerFactory.java.
```
boolean scrubber = config.getBoolean(
"hdds.containerscrub.enabled",
false);
```
This patch fixes the hard coded config key by referring to it from a constant.
> HDDS-2087. Remove the hard coded config key in ChunkManager

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AsyncChecker.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolumeChecker.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/ThrottledAsyncChecker.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolumeChecker.java
HddsVolumeChecker should use java optional in place of Guava optional as Guava Optional is marked as unstable.
> HDDS-2102. HddsVolumeChecker should use java optional in place of Guava optional. Contributed by Mukul Kumar Singh.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
Currently container state checks during state transition are not lock protected in KeyValueHandler. These can cause invalid state transitions.
> HDDS-2048: State check during container state transition in datanode should be lock protected

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java
Change `TestContainerReplication` to close the container directly via client.
https://issues.apache.org/jira/browse/HDDS-2103
Ran the changed unit test - passes, no other code changed.  Checkstyle passes.
> HDDS-2103. TestContainerReplication fails due to unhealthy container

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
Apply tracing to `OzoneManagerProtocol` instead of `OzoneManagerProtocolPB`.  The latter only has a single public method, and no other `*ProtocolPB` interface is traced.
https://issues.apache.org/jira/browse/HDDS-2075
Verified operation hierarchy in Jaeger UI.
> HDDS-2075. Tracing in OzoneManager call is propagated with wrong parent

- pom.ozone.xml
The build fails with the {{dist}} profile. Details in a comment below.
See: https://issues.apache.org/jira/browse/HDDS-2129
> HDDS-2129. Using dist profile fails with pom.ozone.xml as parent pom

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNode.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNodeImpl.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopology.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNetworkTopologyImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
https://issues.apache.org/jira/browse/HDDS-1879
> HDDS-1879.  Support multiple excluded scopes when choosing datanodes in NetworkTopology

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
Fix unit tests recently broken by new `Preconditions.checkNotNull` in `KeyValueContainerUtil#parseKVContainerData` (added in fe8cdf0ab846df9c2f3f59d1d4875185633a27ea for [HDDS-2076](https://issues.apache.org/jira/browse/HDDS-2076)).
https://issues.apache.org/jira/browse/HDDS-2132
https://issues.apache.org/jira/browse/HDDS-2133
```
$ mvn -am -Phdds -pl :hadoop-hdds-container-service clean test
...
[INFO] Apache Hadoop HDDS ................................. SUCCESS [  2.527 s]
[INFO] Apache Hadoop HDDS Config .......................... SUCCESS [  3.223 s]
[INFO] Apache Hadoop HDDS Common .......................... SUCCESS [01:53 min]
[INFO] Apache Hadoop HDDS Server Framework ................ SUCCESS [ 18.258 s]
[INFO] Apache Hadoop HDDS Container Service ............... SUCCESS [01:13 min] …
```
> HDDS-2132. TestKeyValueContainer is failing

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java
* Fix wrong call to increment `AbortMultipartUploadFails`
* Add missing call to increment `AbortMultipartUploads`
https://issues.apache.org/jira/browse/HDDS-2142
Ran `ozones3` acceptance test, verified OM metrics page.
> HDDS-2142. OM metrics mismatch (abort multipart request)

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
Rename metric member variables for block allocation count and its failures to have the same prefix to ensure that they appear in the same chart.  I think `BlockAllocations` is both a bit simpler than `BlockAllocateCalls` and more consistent with other metrics.
https://issues.apache.org/jira/browse/HDDS-2136
Ran acceptance tests, checked OM Metrics web page.
> HDDS-2136. OM block allocation metric not paired with its failures

- pom.ozone.xml
The following Ozone dependencies have known security vulnerabilities. We should update them to newer/ latest versions.
- Apache Common BeanUtils version 1.9.3
- Fasterxml Jackson version 2.9.5
> HDDS-2139. Update BeanUtils and Jackson Databind dependency versions.

- hadoop-ozone/ozonefs-lib-current/pom.xml
We need a shaded Ozonefs jar that does not include Hadoop ecosystem components (Hadoop, HDFS, Ratis, Zookeeper).
A common expected use case for Ozone is Hadoop clients (3.2.0 and later) wanting to access Ozone via the Ozone Filesystem interface. For these clients, we want to add Ozone file system jar to the classpath, however we want to use Hadoop ecosystem dependencies that are `provided` and already expected to be in the client classpath.
Note that this is different from the legacy jar which bundles a shaded Hadoop 3.2.0.
See: https://issues.apache.org/jira/browse/HDDS-2121
> HDDS-2121. Create a shaded ozone filesystem (client) jar

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProvider.java
With this patch, able to run the map-reduce job on a secure cluster.
This was caused by HDDS-2018, which has changed the return/computed value of delegationTokenService. Thank You @xiaoyuyao for helping in this issue.
> HDDS-2144. MR job failing on secure Ozone cluster.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
Remove byte data from container command request before logging it (applicable to `PutSmallFile` and `WriteChunk`).
https://issues.apache.org/jira/browse/HDDS-2151
Set root log level to DEBUG in `ozone-shell-log4j.properties`.  Created small and large keys via `ozone sh`.  Verified that `ozone-shell.log` contains detailed request without actual `data`.
> HDDS-2151. Ozone client logs the entire request payload at DEBUG level

- hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop27/docker-config
- hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop31/docker-config
- hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop32/docker-config
- hadoop-ozone/ozonefs-lib-current/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
- hadoop-ozone/ozonefs-lib-legacy/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
Ozone did not have a filesystem provider in META-INF and this PR adds a filesystem provider for both ozonefs-lib-legacy and ozonefs-lib-current.
Testing done: 
I tested the map reduce robot tests for Hadoop27 and Hadoop32 after removing `fs.o3fs.impl=org.apache.hadoop.fs.ozone.OzoneFileSystem` and `fs.o3fs.impl=org.apache.hadoop.fs.ozone.BasicOzoneFileSystem` from the docker configs and verified that the tests pass.
> HDDS-2101. Ozone filesystem provider doesn't exist

- hadoop-ozone/dev-support/checks/checkstyle.sh
Remove project root from filenames in `checkstyle.sh` output.  Also, make script slightly more readable by breaking long sed command.
https://issues.apache.org/jira/browse/HDDS-2157
Introduced some checkstyle errors, then ran check:
```bash
$ git revert --no-commit 126ef77a810
$ hadoop-ozone/dev-support/checks/checkstyle.sh
...
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java
88: Line is longer than 80 characters (found 91).
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreIterator.java
29: Line is longer than 80 characters (found 90).
46: Line is longer than 80 characters (found 105).
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/LevelDBStoreIterator.java
28: Line is longer than 80 characters (found 90). …
```
> HDDS-2157. checkstyle: print filenames relative to project root

- dev-support/docker/Dockerfile
- hadoop-project/pom.xml
Make protoc 3.7.1 as default in Dockerfile.
> HADOOP-16589. [pb-upgrade] Update docker image to make 3.7.1 protoc as default

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKey.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKeyDetails.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
This patch adds replication factor to the output of list keys.
```
bash-4.2$ ozone sh key list /vol1/bucket1
{
"volumeName" : "vol1",
"bucketName" : "bucket1",
"name" : "dockerfile",
"dataSize" : 876,
"creationTime" : 1569022651963,
"modificationTime" : 1569022654752,
"replicationType" : "RATIS",
"replicationFactor" : 1
}
```
> HDDS-2163. Add 'Replication factor' to the output of list keys

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AUtils.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/SignerManager.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/STSClientFactory.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/SessionTokenBinding.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBClientFactory.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AConfiguration.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ATemporaryCredentials.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestSignerManager.java
This is very similar to the original patch.
In terms of testing - have run tests against a bucket in us-east-1 (including with the patch posted on HADOOP-16477). Struggling a bit with failures though, which seem completely unrelated to the patch. Still trying to get my test configuration file to a state where tests pass.
> HADOOP-16445. Allow separate custom signing algorithms for S3 and DDB

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/Mkdir.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemCLI.java
Change-Id: I2f637865c871e400b95fe7ddaa24bf99fa192023
> HADOOP-16138. hadoop fs mkdir / of nonexistent abfs container raises NPE

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmVolumeArgs.java
- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeCreateRequest.java
This patch proposes to add object ID and update ID when a volume is created.
> HDDS-2170. Add Object IDs and Update ID to Volume Object

- hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/bucket/S3BucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetOwnerRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestOMResponseUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeCreateResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeSetOwnerResponse.java
https://issues.apache.org/jira/browse/HDDS-2180
Adds Object ID and Update ID to VolumeList object.
> HDDS-2180. Add Object ID and update ID on VolumeList Object.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/crypto/CryptoInputStream.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/ByteBufferPositionedReadable.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FSDataInputStream.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/CryptoStreamsTestBase.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreams.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreamsForLocalFS.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestCryptoStreamsNormal.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs-tests/test_libhdfs_ops.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/include/hdfs/hdfs.h
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/tests/hdfs_shim.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/tests/libhdfs_wrapper_defines.h
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/tests/libhdfs_wrapper_undefs.h
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/tests/libhdfspp_wrapper_defines.h
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestByteBufferPread.java
[HDFS-14564](https://issues.apache.org/jira/browse/HDFS-14564): Add libhdfs APIs for readFully; add readFully to ByteBufferPositionedReadable
* Adds `readFully` to `ByteBufferPositionedReadable` and exposes it via libhdfs
* Exposes `PositionedReadable#readFully` via libhdfs
* Like `hdfsPread` and `hdfsRead` if the underlying stream supports `ByteBuffer` reads, the `ByteBuffer` APIs will be used
* Add unit tests, and did a bit of javadoc / code cleanup
> HDFS-14564: Add libhdfs APIs for readFully; add readFully to ByteBufferPositionedReadable

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/SCMContainerManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/metrics/SCMContainerManagerMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java
> HDDS-1146. Adding container related metrics in SCM.

- hadoop-project/pom.xml
Compiled locally on my Mac. Confirmed that it uses 2.9.10 jars for `jackson-core`, `jackson-annotations`, `jackson-databind`, etc.:
```
$ cd hadoop-dist/target/hadoop-3.3.0-SNAPSHOT
$ find . -name "*jackson*"
./share/hadoop/yarn/lib/jackson-jaxrs-json-provider-2.9.10.jar
./share/hadoop/yarn/lib/jackson-jaxrs-base-2.9.10.jar
./share/hadoop/yarn/lib/jackson-module-jaxb-annotations-2.9.10.jar
./share/hadoop/common/lib/jackson-jaxrs-1.9.13.jar
./share/hadoop/common/lib/jackson-xc-1.9.13.jar
./share/hadoop/common/lib/jackson-core-2.9.10.jar
./share/hadoop/common/lib/jackson-core-asl-1.9.13.jar
./share/hadoop/common/lib/jackson-annotations-2.9.10.jar
./share/hadoop/common/lib/jackson-databind-2.9.10.jar
./share/hadoop/common/lib/jackson-mapper-asl-1.9.13.jar …
```
> HADOOP-16619. Upgrade jackson and jackson-databind to 2.9.10

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/GDPRSymmetricKey.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestGDPRSymmetricKey.java
https://issues.apache.org/jira/browse/HDDS-2227
The SecureRandom can be used for the symetric key for GDPR. While GDPR is not a security feature, this is a good to have optional feature.
I want to thank Jonathan Leitschuh, for originally noticing this issue and reporting it.
How tested: ran unit.sh, had one failure in TestSCMContainerPlacementRackAware
> HDDS-2227. GDPR key generation could benefit from secureRandom.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCacheImpl.java
> HDDS-2224. Fix loadup cache for cache cleanup policy NEVER.

- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneServiceProvider.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/OzoneS3Util.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/util/TestOzoneS3Util.java
Need some work on server-side for adding secure-om-s3-ha docker-compose cluster, as some fields like keytab are still not supporting parameter with serviceid and node id.
> HDDS-2019. Handle Set DtService of token in S3Gateway for OM HA.

- BUILDING.txt
- dev-support/docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-16620
> HADOOP-16620. [pb-upgrade] Remove protocol buffers 3.7.1 from requirements in BUILDING.txt

- hadoop-tools/hadoop-azure-datalake/src/test/java/org/apache/hadoop/fs/adl/live/TestAdlSdkConfiguration.java
Fixing testcase testSSLChannelModeConfig, which is supposed to be skipped when no test creds are provided. 
Without test creds set: 
INFO] Results:
[INFO] 
[WARNING] Tests run: 788, Failures: 0, Errors: 0, Skipped: 767
With test creds set:
[INFO] 
[WARNING] Tests run: 882, Failures: 0, Errors: 0, Skipped: 3
> HADOOP-16605: Fix testcase testSSLChannelModeConfig

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
https://issues.apache.org/jira/browse/HDDS-2226
The S3 token generation under ozone should use a strong RNG.
I want to thank Jonathan Leitschuh, for originally noticing this issue and reporting it.
How tested: Ran Unit.sh
> HDDS-2226. S3 Secrets should use a strong RNG.

- hadoop-ozone/dist/src/main/compose/test-all.sh
- hadoop-ozone/dist/src/main/compose/testlib.sh
1. Collect docker logs if environment fails to start up (previously it was collected only after actual test run)
2. Copy docker logs to aggregate result directory
3. Fail fast if datanodes cannot be started
4. Avoid [ANSI codes in output](https://github.com/elek/ozone-ci-q4/blob/f700ebb2254527527960593496f15008245094d6/trunk/trunk-nightly-extra-20190930-74rp4/acceptance/output.log#L3774)
5. Sort test cases for consistent run ordering (Robot summary table is already sorted)
https://issues.apache.org/jira/browse/HDDS-2211
Ran `acceptance.sh` locally.  Also simulated failure during datanode startup, verified that docker log is saved.
> HDDS-2211. Collect docker logs if env fails to start

- hadoop-ozone/pom.xml
Make RAT check ignore `ozone-recon-web/build` directory.
During `ozone-recon` to `recon` rename ([HDDS-2044](https://issues.apache.org/jira/browse/HDDS-2044)) the directory ignored by RAT was [changed to `recon-web/build`](https://github.com/apache/hadoop/blob/0e026cb0cefcadcfe404cd5d542f081f3b8ab69b/hadoop-ozone/pom.xml#L294), but the real directory is still [`ozone-recon-web`](https://github.com/apache/hadoop/tree/trunk/hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web).
The mismatch is not a problem for CI because it doesn't build anything before the RAT check, so the `build` directory is not present.
https://issues.apache.org/jira/browse/HDDS-2234
```
$ mvn -f pom.ozone.xml -Dmaven.javadoc.skip=true -DskipTests clean package
...
[INFO] BUILD SUCCESS
$ ls …
```
> HDDS-2234. rat.sh fails due to ozone-recon-web/build files

- hadoop-ozone/dist/src/main/compose/test-single.sh
Restore pre-[HDDS-2185](https://issues.apache.org/jira/browse/HDDS-2185) behavior of `test-single.sh` by explicitly creating `result` directory.
https://issues.apache.org/jira/browse/HDDS-2231
```
$ cd hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone
$ docker-compose up -d --scale datanode=3
$ ../test-single.sh scm basic/basic.robot
$ ls result
robot-ozone-ozone-basic-scm.xml
```
> HDDS-2231. test-single.sh cannot copy results

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
There are cases where SCM can be stuck in safemode for ever if it considers containers in CLOSING state for coming out of safemode
* If there are 5 containers in OPEN state inside SCM
* Out of 5, 3 containers are created in datanodes by the client.
* 2 containers are yet to be created in datanodes
* Due to some pipeline issue, pipeline close action is sent.
* All 5 container's state are changed from OPEN to CLOSING in SCM.
* Eventually , 3 container's state moves from CLOSING to CLOSED in SCM as the datanodes closes those containers.
* 2 of the containers are still in CLOSING state.
* SCM is restarted.
* SCM will never gets container reports for the containers which were in CLOSING state as those containers were never created in datanodes.
* SCM will remain in safemode.
> HDDS-2198. SCM should not consider containers in CLOSING state to come out of safemode.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyDeletingService.java
1. OzoneManager starts KeyManager
2. KeyManager starts KeyDeletingService
3. KeyDeletingService uses OzoneManager.isLeader()
4. OzoneManager.isLeader() uses omRatisServer
5. omRatisServer can be null (bumm)
 
Now the initialization order in OzoneManager:
 
new KeymanagerServer() *Includes start()!!!!*
omRatisServer initialization
start() (includes KeyManager.start())
 
The solution seems to be easy: start the key manager only from the OzoneManager.start() and not from the OzoneManager.instantiateServices()
See: https://issues.apache.org/jira/browse/HDDS-2237
> HDDS-2237. KeyDeletingService throws NPE if it's started too early

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/web/utils/JsonUtils.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/ObjectPrinter.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/AddAclBucketHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/GetAclBucketHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/RemoveAclBucketHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/SetAclBucketHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/AddAclKeyHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/GetAclKeyHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/RemoveAclKeyHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/SetAclKeyHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/token/GetTokenHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/token/PrintTokenHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/AddAclVolumeHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/GetAclVolumeHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/RemoveAclVolumeHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/SetAclVolumeHandler.java
JsonUtils#toJsonStringWithDefaultPrettyPrinter() does not validate the Json String  before serializing it which could result in Json Injection.
This method is mostly used along with JsonUtils#toJsonString() by first converting to String and then back to object. This can be avoided by directly writing the object through PrettyPrinter.
> HDDS-2158. Fixing Json Injection Issue in JsonUtils.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBuffer.java
Fix these checkstyle issues 
```
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBuffer.java
84: Inner assignments should be avoided.
85: Inner assignments should be avoided.
101: 'case' child has incorrect indentation level 8, expected level should be 6.
102: 'case' child has incorrect indentation level 8, expected level should be 6.
103: 'case' child has incorrect indentation level 8, expected level should be 6.
104: 'case' child has incorrect indentation level 8, expected level should be 6.
105: 'case' child has incorrect indentation level 8, expected level should be 6.
106: 'case' child has incorrect indentation level 8, expected level should be 6.
107: 'case' child has incorrect indentation level 8, expected level should be 6.
108: 'case' child has …
```
> HDDS-2257. Fix checkstyle issues in ChecksumByteBuffer

- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
Make sure context classloader is restored to avoid NPE during shutdown.
https://issues.apache.org/jira/browse/HDDS-2239
Ran `TestOzoneFsHAUrls` in IDE.
> HDDS-2239. Fix TestOzoneFsHAUrls

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/VolumeManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/bucket/S3BucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/bucket/S3BucketDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3GetSecretRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetOwnerRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetQuotaRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAclRequest.java
Use new ReadWriteLock added in HDDS-2223.
Existing tests should cover this.
Ran a few Integration tests.
Not removed Old methods in OzoneManagerLock, as it is used in Old write requests in VolumeManagerImpl/BucketManagerImpl/KeyManagerImpl. Marked those methods as deprecated.
> HDDS-2244. Use new ReadWrite lock in OzoneManager.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/ActiveLock.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/LockManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/PooledLockFactory.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java
https://issues.apache.org/jira/browse/HDDS-2269
Provide config in OzoneManager Lock for fair/non-fair for OM RW Lock.
> HDDS-2269. Provide config for fair/non-fair for OM RW Lock.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java
> HDDS-1986. Fix listkeys API.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStore.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStoreTableHandler.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStoreTableManager.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/PathMetadataDynamoDBTranslation.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTableAccess.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestDynamoDBMetadataStore.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestDynamoDBMetadataStoreScale.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolDynamoDB.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestDynamoDBMiscOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestPathMetadataDynamoDBTranslation.java
The following should be included: HADOOP-16349. DynamoDBMetadataStore.getVersionMarkerItem() to log at info/warn on retry. 
Notes:
- Why there's no ITestDynamoDBMetadataStoreTableHandler if there's ITestDynamoDBMetadataStore, and why do I added the tests there?
For readability and to avoid duplication. DynamoDBMetadataStoreTableHandler is just basically parts factored out from DynamoDBMetadataStore, and some helper methods.
- Why there's only testTableVersioning->checkVerifyVersionMarkerCompatibility to cover the full functionality of the version marker checking and recovery with dynamo, and not 6 different methods?
Creating and deleting tables takes a *lot* of time. Minutes. I use the same table during the test and add/remove the version tag and item to cover all combinations.
- Why …
> HADOOP-16520 dynamodb ms version race refactor. 

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-tools/hadoop-fs2img/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSTreeWalk.java
- hadoop-tools/hadoop-fs2img/src/main/java/org/apache/hadoop/hdfs/server/namenode/SingleUGIResolver.java
- hadoop-tools/hadoop-fs2img/src/main/java/org/apache/hadoop/hdfs/server/namenode/TreePath.java
- hadoop-tools/hadoop-fs2img/src/main/java/org/apache/hadoop/hdfs/server/namenode/TreeWalk.java
- hadoop-tools/hadoop-fs2img/src/main/java/org/apache/hadoop/hdfs/server/namenode/UGIResolver.java
- hadoop-tools/hadoop-fs2img/src/test/java/org/apache/hadoop/hdfs/server/namenode/RandomTreeWalk.java
- hadoop-tools/hadoop-fs2img/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSTreeWalk.java
- hadoop-tools/hadoop-fs2img/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSingleUGIResolver.java
Addresses https://issues.apache.org/jira/browse/HDFS-14856. 
If configuration `dfs.namenode.mount.acls.enabled` is set (true), `FsTreeWalk` will fetch ACLs of files on the external storage system provided at the time of mount.
> HDFS-14856. Fetch file ACLs while mounting external store.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java
> HDFS-14910. Rename Snapshot with Pre Descendants Fail With IllegalArgumentException

- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-blockgen/src/main/bash/generate-block-lists.sh
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra/src/main/bash/start-dynamometer-cluster.sh
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload/src/main/bash/start-workload.sh
> HDFS-14638. [Dynamometer] Fix scripts to refer to current build structure.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStoreTableManager.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/auth/ITestAssumeRole.java
Change-Id: I4990e61dcf1baa7ddb593ac9a2195e9338060539
> HADOOP-16653. S3Guard DDB overreacts to no tag access

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestRenameWithSnapshots.java
When we do rename operation for directory,
if the src directory or any of its descendant is snapshottable
and the dst directory or its any of its ancestors is snapshottable,
we consider this as nested snapshot, which should be denied.
V2:
1. reduce duplicate code
2. take `directory rename overwrite` into consideration
Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>
> HDFS-14925. Rename operation should check nest snapshot

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-router/src/main/java/org/apache/hadoop/yarn/server/router/clientrm/FederationClientInterceptor.java
When we enable kerberos in YARN-Federation mode, we can not get new app since it will throw kerberos exception below.Which should be handled!
`
2019-07-22,18:43:25,523 WARN org.apache.hadoop.ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
2019-07-22,18:43:25,528 WARN org.apache.hadoop.yarn.server.router.clientrm.FederationClientInterceptor: Unable to create a new ApplicationId in SubCluster xxx
java.io.IOException: DestHost:destPort xxx , LocalHost:localPort xxx. Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials …
> YARN-9689: Support proxy user for Router to support kerberos

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
Unify logging style in UserGroupInformation class.
- Remove superfluous logging guards
- Remove superfluous String.format
- Simplify
- Other
https://issues.apache.org/jira/browse/HADOOP-16691
> HADOOP-16691: Unify Logging in UserGroupInformation

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
Change-Id: I38fdba2fa70e534d78b15e61de19368912588b0c
Tested: azure wales
> HADOOP-16707. NPE in UGI.getCurrentUser in ITestAbfsIdentityTransformer setup.

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemCLI.java
Fixing the testcase by allowing the setup and teardown to handle creation and deletion of filesystems as expected. Moving the config to prevent filesystem creation inside the testcase which issues request to a non-existing filesystem.
> Hadoop 16687: Fix testcase added for HADOOP-16138 for namespace enabled account

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractGetFileStatusTest.java
[HADOOP-16685](https://issues.apache.org/jira/browse/HADOOP-16685): FileSystem#listStatusIterator does not check if given path exists
Changed `DirListingIterator` so that the constructor makes the first call to `listStatusBatch`. This is similar to what `FileSystem#listFiles` does. Added a contract test in `AbstractContractGetFileStatusTest.java` to validate that `listStatusIterator` throws a FNF exception if the given `Path` does not exist.
> HADOOP-16685: FileSystem#listStatusIterator does not check if given path exists

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/ContainerExecutor.java
https://issues.apache.org/jira/browse/YARN-9958
ContainerExecutor has ReadLock and WriteLock. These used to call get/put method of ConcurrentMap. Due to the ConcurrentMap providing thread safety and atomicity guarantees, so we can remove the lock.
> YARN-9958. Remove the invalid lock in ContainerExecutor

- hadoop-project/pom.xml
To be able to easily replace third-party dependency version numbers it
would be useful to collect their version numbers at the top of the pom.xml.
For many third-parties (e.g. slf4j, jetty, etc.) this is already done,
but I would need the same for others. The change doesn't have any effect
on the code or the build, no version numbers would be changed.
> HADOOP-16729. Extract version numbers to head of pom.xml

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/security/token/ZKDelegationTokenSecretManagerImpl.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15043
* Logging IOException.
> HDFS-15043. RBF: The detail of the Exception is not shown in ZKDelegationTokenSecretManagerImpl

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/security/RouterSecurityManager.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/security/MockNotRunningSecretManager.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/security/TestRouterSecurityManager.java
> HDFS-15040. RBF: Secured Router should not run when SecretManager is not running.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/test/HadoopTestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/MetadataStoreTestBase.java
https://issues.apache.org/jira/browse/HADOOP-16757
> HADOOP-16757. Increase timeout unit test rule for MetadataStoreTestBase

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/ITestS3ACommitterFactory.java
Change-Id: Ifb9771a73a07f744e4ed5f5e6be72473179db439
Tested: S3 Ireland, in both a sequential and a parallel test run
> HADOOP-16450. ITestS3ACommitterFactory to not use useInconsistentClient.

- hadoop-project/pom.xml
Gradle behaves differently than Maven when processing exclude rules through transitive
dependencies. This causes gradle projects (e.g. in Kudu) that are using Hadoop MiniCluster
to fail because different Guava version come to the classpath through Curator. In this
fix we make sure that ZooKeeper, SLF4J and Gradle gets always excluded from Curator Client
even if they would come through other Curator dependencies transitively.
> HADOOP-16765. Fix curator dependencies for gradle projects using hadoop-minicluster.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/README.md
We don't need to manually install package managers such as yarn and bower as described in README.md since frontend-maven-plugin was introduced by YARN-6278.
https://issues.apache.org/jira/browse/YARN-10020
> YARN-10020. Fix build instruction of hadoop-yarn-ui.

- hadoop-common-project/hadoop-common/pom.xml
> HADOOP-16774. TestDiskChecker and TestReadWriteDiskValidator fails when run with -Pparallel-tests

- dev-support/docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/YARN-10054
> YARN-10054. Upgrade yarn to 1.21.1 in Dockerfile.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/yarn.lock
Closes #1741
Closes #1742 
Closes #1743 
Closes #1744
JIRA: https://issues.apache.org/jira/browse/YARN-10057
Ran the following commands to update yarn.lock file:
```
$ ./start-build-env.sh
$ cd hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp
$ bower install
$ yarn upgrade
$ yarn install
$ yarn run build
```
> YARN-10057. Upgrade the dependencies managed by yarnpkg.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/src/test/java/org/apache/hadoop/yarn/csi/client/TestCsiClient.java
As the issue described, it is easy to exceed the UNIX_PATH_MAX limit if
we create the CSI test socket file under the test code dicrectory.
> YARN-10041. Create tmp socket file under /tmp for CSI tests

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/site/markdown/MapReduceTutorial.md
Fix for typo in MapReduce documentation example (https://issues.apache.org/jira/browse/MAPREDUCE-7255)
> MAPREDUCE-7255: fix typo in MapReduce documentaion example

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/DurationInfo.java
This moves the import of a java module to the preferred place in the import ordering.
I know this is minor but it's good to at least try to keep imports under control. If I'd noticed the problem earlier I'd have done the reordering during the commit process.
Change-Id: I1a594e3d954554a72c2b71c954eda0ae940a8f70
> HADOOP-16751. Followup: move java import.

- dev-support/bin/create-release
- dev-support/docker/Dockerfile_aarch64
- hadoop-hdfs-project/hadoop-hdfs/pom.xml
- start-build-env.sh
Added a Dockerfile, which will be used by scripts during build and test in aarch64 platform.
-----
* CMake 3.1.0 compilation from source as no binary package readily available for aarch64
* Skips installation of ghc package which does not have any package for aarch64 from repo.
* Skips installation of hadolint as no package is available for aarch64
* x86_64 specific packages were replaced with aarch64 specific packages.
* phantomjs is being installed from prebuilt package and made available in the system path to avoid failure during maven build.
* Updated the *dev-support/bin/createrelease* and *start-build-env.sh* script to load platform specific docker files.
* Updated *dev-support/bin/createrelease* to make use of gpg-agent for signing artifacts.
* Yes, Tested well!!
Verified creation …
> HADOOP-16797. Add Dockerfile for ARM builds

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/PartialListing.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFilterFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestHarFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/dev-support/findbugsExcludeFile.xml
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/BatchedDirectoryListing.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsPartialListing.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelperClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/ClientNamenodeProtocol.proto
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/hdfs.proto
- hadoop-hdfs-project/hadoop-hdfs-client/src/test/java/org/apache/hadoop/hdfs/protocol/TestReadOnly.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterClientProtocol.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/ListingBenchmark.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestBatchedListDirectories.java
One of the dominant workloads for external metadata services is listing of partition directories. This can end up being bottlenecked on RTT time when partition directories contain a small number of files. This is fairly common, since fine-grained partitioning is used for partition pruning by the query engines.
A batched listing API that takes multiple paths amortizes the RTT cost. Initial benchmarks show a 10-20x improvement in metadata loading performance.
> HDFS-13616. Batch listing of multiple directories

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/TestAuxServices.java
JIRA: https://issues.apache.org/jira/browse/YARN-9512
> YARN-9512. [JDK11] TestAuxServices#testCustomizedAuxServiceClassPath fails because of ClassCastException.

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs/src/site/markdown/HistoryServerRest.md
The Job Attempts API http://history-server-http-address:port/ws/v1/history/mapreduce/jobs/{jobid}/jobattempts document, In http://hadoop.apache.org/docs/current/hadoop-mapreduce-client/hadoop-mapreduce-client-hs/HistoryServerRest.html#Job_Attempts_API, change The job attempt id‘s datatype from string to int.
> MAPREDUCE-7247. Change the job attempt id‘s datatype from string to int in HistoryServerRest.html

- hadoop-common-project/hadoop-common/dev-support/findbugsExcludeFile.xml
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ProtobufHelper.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/Credentials.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/Token.java
- hadoop-hdfs-project/hadoop-hdfs-client/dev-support/findbugsExcludeFile.xml
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelperClient.java
```
/**
* Construct a Token from a TokenProto.
* @param tokenPB the TokenProto object
*/
public Token(TokenProto tokenPB){
...
}
/**
* Construct a TokenProto from this Token instance.
* @return a new TokenProto object holding copies of data in this instance
*/
public TokenProto toTokenProto() {
...
}
```
> HADOOP-16621. [pb-upgrade] Remove Protobuf classes from signatures of Public APIs.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/ChecksumFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/DelegateToFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileContext.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FilterFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FilterFs.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FutureDataInputStreamBuilder.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/impl/FutureDataInputStreamBuilderImpl.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/impl/OpenFileParameters.java
- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/filesystem.md
- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/fsdatainputstreambuilder.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractOpenTest.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ARemoteFileChanged.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3GuardOutOfBandOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/select/ITestS3Select.java
* Enhanced builder + FS spec
* s3a FS to use this to skip HEAD on open
* and to use version/etag when opening the file
works with S3AFileStatus FS and S3ALocatedFileStatus
Change-Id: If80f73137643fd50a969a92ad5794d0d09e3aee6
> HADOOP-16759. Filesystem openFile() builder to take a FileStatus param

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestHarFileSystem.java
This is a regression caused by HADOOP-16759.
The test TestHarFileSystem uses introspection to verify that HarFileSystem
Does not implement methods to which there is a suitable implementation in
the base FileSystem class. Because of the way it checks this, refactoring
(protected) FileSystem methods in an IDE do not automatically change
the probes in TestHarFileSystem.
The changes in HADOOP-16759 did exactly that, and somehow managed
to get through the build/test process without this being noticed.
This patch fixes that failure.
Caused by and fixed by Steve Loughran.
> HADOOP-16827. TestHarFileSystem.testInheritedMethodsImplemented broken.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFileUtil.java
> HADOOP-16811: Use JUnit TemporaryFolder Rule in TestFileUtils

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/Options.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/SwapBlockListOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSwapBlockList.java
This is the first patch HDFS-14989 for the In Place Erasure Coding Feature HDFS-14978.
Work Done
The swapBlockList takes two parameters, a source file and a destination file. This operation swaps the blocks belonging to the source and the destination atomically.
The namespace metadata of interest is the INodeFile class. A file (INodeFile) contains a header composed of PREFERRED_BLOCK_SIZE, BLOCK_LAYOUT_AND_REDUNDANCY and STORAGE_POLICY_ID. In addition, an INodeFile contains a list of blocks (BlockInfo[]). The operation will swap BLOCK_LAYOUT_AND_REDUNDANCY header bits and the block lists. But it will not touch other fields. To avoid complication, this operation will abort if either file is open (isUnderConstruction() == true)
Note : This patch is intentionally not exposing the client side …
> HDFS-14989. Add a 'swapBlockList' operation to Namenode.

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/testing.md
> HADOOP-16832 Update S3Guard testing doc.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestGroupsCaching.java
The test `testNegativeGroupCaching` can fail if the iteration order of HashSet changes. In detail, the method `assertEquals` (line 331) compares `groups.getGroups(user)` with an ArrayList `myGroups`. The method `getGroups` converts `allGroups` (a HashSet) to a list and it calls iterator in HashSet. However, the iteration is non-deterministic.
This PR proposes to modify HashSet to LinkedHashSet for a deterministic order.
> HADOOP-16847. Test can fail if HashSet iterates in a different order

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterFsck.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterFsckServlet.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterHttpServer.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterFsck.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/DfsServlet.java
JIRA: https://issues.apache.org/jira/browse/HDFS-13989
01 patch plus:
* Rebased and refactor the code
* (hopefully) support https
* Add end-to-end unit test
Note that RouterFsck does not consider the mount table for now. The request is always forwarded to all the active downstream namenodes. The path of the fsck arguments is not changed when forwarding the request.
> HDFS-13989. RBF: Add FSCK to the Router

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
Followup to the main openFile().withStatus() patch.
It turns out that this broke the hive builds, which
was not well appreciated.
This patch lists places to review in the hadoop codebase,
and external projects where changes may cause problems.
> HADOOP-16759. FileSystem Javadocs to list what breaks.

- hadoop-project/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-16869
> HADOOP-16869. Upgrade findbugs-maven-plugin to 3.0.5 to fix mvn findbugs:findbugs failure

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/contracts/services/AzureServiceErrorCode.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestClientUrlScheme.java
Adds a new service code to recognise accounts without HTTP support; catches
that and considers that a successful validation of the ability of the
client to switch to http when the test parameters expect that.
Tested: Azure cardiff, with a storage account which doesn't support HTTP
> HADOOP-16706. ITestClientUrlScheme fails for accounts which don't support HTTP

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractUnbufferTest.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStream.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/contract/ITestAbfsContractUnbuffer.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/ITestAbfsUnbuffer.java
- hadoop-tools/hadoop-azure/src/test/resources/abfs.xml
Added two unit tests: `ITestAbfsUnbuffer` and `ITestS3AContractUnbuffer`
Ran ABFS tests against "East US 2"; the following tests failed:
```
ITestGetNameSpaceEnabled.testNonXNSAccount
ITestAbfsRestOperationException.testRequestRetryConfig
ITestAzureBlobFileSystemAuthorization.testSetOwnerAuthorized
ITestAzureBlobFilesystemAcl.testEnsureAclOperationWorksForRoot
```
I've seen most of these failures before and they all seem to be account related issues. I haven't seen `ITestAbfsRestOperationException#testRequestRetryConfig` before, but it looks like it was recently added and uses a custom token provider, so my guess is the failure is account related as well.
> HADOOP-16859: ABFS: Add unbuffer support to ABFS connector

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3GuardOutOfBandOperations.java
Tested s3 ireland with/without change.detection.source = versionid
> HADOOP-16853. ITestS3GuardOutOfBandOperations failing on versioned S3 buckets

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/Federation.md
`be complaint to` should be `be compliant with` on the context.
> YARN-10156: Fix a typo 'complaint' which means quite different in Federation.md

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java
Catch Exception instead of IOException in closeStream() to handle exceptions such as SdkClientException properly.
Jira Issue: https://issues.apache.org/jira/browse/HADOOP-16767
> HADOOP-16767 Handle non-IO exceptions in reopen()

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/AbstractS3ATestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/AbstractTestS3AEncryption.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/EncryptionTestUtils.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AEncryptionSSEKMSDefaultKey.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AEncryptionWithDefaultS3Settings.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/AbstractSTestS3AHugeFiles.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/ITestS3AHugeFilesEncryption.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/test/ExtraAssertions.java
Debugging details:
When a put operation is performed without -d parameter is used, it happens in two steps. First is copying to a temporary file and then copying the temp file to the right location. The is issue is durning the copy step as an extra header "x-amz-server-side-encryption: aws:kms" is set. 
When -d parameter is used, the file is uploaded directly and in that api call this kms header is not set. 
Solution: Removing the kms header from the ClonedObjectMetatData.
Testing: Tested by compiling the complete hadoop distribution and invoking the hadoop shell command locally. 
Bucket used : https://mthakur-data.s3.ap-south-1.amazonaws.com/file2
Please suggest how to write testcases for this. Thanks
> HADOOP-16794 S3 Encryption keys not propagating correctly during copy operation

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/ReflectionUtils.java
This PR aims to solve the issue here: https://issues.apache.org/jira/browse/HADOOP-16897
The fix is to sort the fields returned by getDeclaredFields() so that the non-deterministic behaviour can be eliminated completely. In this way, the test becomes more stable and it will not suffer from the failure any more.
> HADOOP-16897. Sort fields in ReflectionUtils.java

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/shell/TestCopy.java
Followup to HADOOP-16885: Encryption zone file copy failure leaks a temp file
#1859
Moving the delete() call broke a mocking test.
(sorry; somehow missed this test failure. It's trivial enough to fix that I'm not going to revert the main patch)
> HADOOP-16885. Followup to fix test failure of encryption zone file copy

- hadoop-client-modules/hadoop-client-runtime/pom.xml
- hadoop-project/pom.xml
> HADOOP-16905. Update jackson-databind to 2.10.3 to relieve us from the endless CVE patches.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/PathMetadataDynamoDBTranslation.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AMiscOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/AbstractS3GuardToolTestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardFsShell.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestPathMetadataDynamoDBTranslation.java
path qualification in s3a fs strips any trailing / ; with tests
> HADOOP-15430. hadoop fs -mkdir -p path-ending-with-slash/ fails with s3guard

- hadoop-project/pom.xml
Manually verified with 
`mvn clean install -Dhbase.profile=2.0 -Dhbase.two.version=2.2.0 -Dmaven.javadoc.skip=true -DskipTests
`
> YARN-10195. Dependency divergence building Timeline Service on HBase 2.2.0 and above.

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/resources/mapred-default.xml
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-shuffle/src/main/java/org/apache/hadoop/mapred/ShuffleHandler.java
Nowadays the ShuffleHandler#Shuffle#pathCache's related parameters is hard coding. We should support config these.
> MAPREDUCE-7237. Supports config the shuffle's path cache related parameters

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/http/TestSSLHttpServer.java
TLS 1.3 is supported in Hadoop 3.3.0 with the update of Jetty 9.4 and Java 11 Runtime.
This patch doesn't add any new capability. It simply adds a new test case to verify TLSv1.3 is enabled on Java 11.
Verified manually by:
```
JAVA_HOME=`/usr/libexec/java_home -v 11` mvn test -Dtest=TestSSLHttpServer#testIncludedProtocols
JAVA_HOME=`/usr/libexec/java_home -v 1.8` mvn test -Dtest=TestSSLHttpServer#testIncludedProtocols
```
> HADOOP-16661. Support TLS 1.3

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/testing.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AMiscOperations.java
Thiis ben roling's patch #836 as applied to trunk
tested: not yet
> HADOOP-16319 skip invalid tests when default encryption enabled

- hadoop-hdfs-project/hadoop-hdfs/src/test/resources/log4j.properties
Verified manually by running TestEncryptionZonesWithKMS.
Change-Id: I7abeaf4b65e2a4758356aa69ab8930f7e993077d
> HDFS-15208. Supress bogus AbstractWadlGeneratorGrammarGenerator in KMS stderr in hdfs

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/gmock-1.7.0/gmock/gmock.h
JIRA: https://issues.apache.org/jira/browse/HDFS-15232
> HDFS-15232. Fix libhdfspp test failures with GCC 7.

- dev-support/docker/Dockerfile
This reverts commit 367833cf41753f5b1c996f9a2a9c1f20e2011173.
The precommit job fails to add comments to JIRA and GitHub after the upgrade of the build image. Revert the upgrade to see if the precommit job can add comment to GitHub.
> Revert "HADOOP-16054. Update Dockerfile to use Bionic."

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DataStreamer.java
> HDFS-15219. DFS Client will stuck when ResponseProcessor.run throw Error

- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/index.md
It's very handy, and people are [already using it](https://stackoverflow.com/q/50242843/877069). It would be good to document it.
> HADOOP-16930. Add hadoop-aws documentation for ProfileCredentialsProvider

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/client/DefaultNoHARMFailoverProxyProvider.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/client/RMProxy.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/ResourceManagerHA.md
Adds the following improvements: 
https://issues.apache.org/jira/browse/HADOOP-16938
> HADOOP-16938. Make non-HA proxy providers pluggable

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AUtils.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3Guard.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestAuthoritativePath.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestAuthoritativePath.java
add unit test, new ITest and then fix the issue: different schema, bucket == skip
factored out the underlying logic for unit testing; also moved
maybeAddTrailingSlash to S3AUtils (while retaining/forwarnding existing method
in S3AFS).
tested: london, sole failure is
testListingDelete[auth=true](org.apache.hadoop.fs.s3a.ITestS3GuardOutOfBandOperations)
...filed HADOOP-16853
Change-Id: I4b8d0024469551eda0ec70b4968cba4abed405ed
> HADOOP-16939. fs.s3a.authoritative.path should support multiple FS URIs

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystem.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStream.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStream.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/AbstractAbfsTestWithTimeout.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsStreamStatistics.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemOauth.java
Contributed by Mehakmeet Singh
> HADOOP-16910: ABFS Streams to update FileSystem.Statistics counters on IO.

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterFsck.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15258
Add a message to show that the feature is unstable. The APIs are already marked as `@Private` so I didn't touch them.
> HDFS-15258. RBF: Mark Router FSCK unstable.

- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
JIRA: https://issues.apache.org/jira/browse/HADOOP-16949
> HADOOP-16949. pylint fails in the build environment

- hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/util/DistCpUtils.java
- hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/util/TestDistCpUtils.java
Strips out all the attributes which have already been processed,
before deciding whether or not to query the far end for the status of the file.
This will avoid 404 caching-related issues in S3, and save time and a bit of IO
everywhere.
> HADOOP-16932. distcp copy calls getFileStatus() needlessly and can fail against S3

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3GuardOutOfBandOperations.java
Removed the failing probe and replacing with two probes which will fail
on both versioned and unversioned buckets.
> HADOOP-16941. ITestS3GuardOutOfBandOperations.testListingDelete failing on versioned bucket

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AFileOperationCost.java
Optimize S3AFileSystem.listLocatedStatus() to perform list
operations directly and then fallback to head checks for file
Ran test in ap-south-1 bucket with command:
mvn clean verify -Ds3guard -Ddynamo  -Dparallel-tests -DtestsThreadCount=8
There are two failures. I am looking at them.
> HADOOP-16465 listLocatedStatus() optimisation

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
Since it is a test only change, no new tests were added. 
Ran all s3a integration tests in both auth/non-auth mode with ap-south-1. All good.
> HADOOP-16979 set auth mode to false by default for s3 ITs

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3Guard.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/s3guard.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestS3Guard.java
Contributed by Steve Loughran
* change name of config option
* default -> silent
* javadocs
* site docs s3guard.md
* error text is a string to pass throught string.format so consistent
in logs and exceptions
* raises ExitException(49 + text) on no s3guard, this will result in
exit code 49 in the s3guard tools and other apps. That can be tested
in system tests.
> HADOOP-16953. tuning s3guard disabled warnings

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/FederationTestUtils.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterFaultTolerant.java
JIRA: https://issues.apache.org/jira/browse/HDFS-14742
The root cause: 
There are 2 routers in the test. When submitting a request to create a mount point to a router, the mount table of the other router is not refreshed. That's why the requests fail if destination of the requests is the other router.
How to fix:
Refresh the other router's mount table.
> HDFS-14742. RBF: TestRouterFaultTolerant tests are flaky

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AbfsConfiguration.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/AbfsHttpConstants.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/ConfigurationKeys.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/FileSystemConfigurations.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsClient.java
HADOOP-16922. Changing User-Agent header.
- Add more inforrmation to the User-Agent header like cluster name, cluster type, java vendor etc.
- Add APN/1.0 in the begining
At present the User-Agent header would look like:
Azure Blob FS/3.4.0-SNAPSHOT (JavaJRE 1.8.0_241; Linux 5.3.0-46-generic; SunJSSE-1.8) MSFT
With this PR it would be:
APN/1.0 Azure Blob FS/3.4.0-SNAPSHOT (OracleCorporation JavaJRE 1.8.0_241; Linux 5.3.0-46-generic/amd64; SunJSSE-1.8; UNKNOWN/UNKNOWN) MSFT
> HADOOP-16922. ABFS: Change User-Agent header

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStream.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStreamContext.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStreamStatistics.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStreamStatisticsImpl.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/AbstractAbfsIntegrationTest.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsOutputStreamStatistics.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsStreamStatistics.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/TestAbfsOutputStreamStatistics.java
Change-Id: Ie976f23c6c3e2f5cf9167794357cfc669a232c80
> HADOOP-16914 Adding Output Stream Counters in ABFS

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/pom.xml
JIRA: https://issues.apache.org/jira/browse/YARN-10223
> YARN-10223. Duplicate jersey-test-framework-core dependency in yarn-server-common

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AbfsConfiguration.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/ConfigurationKeys.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/FileSystemConfigurations.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/contracts/exceptions/TrileanConversionException.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/enums/Trilean.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/enums/package-info.java
- hadoop-tools/hadoop-azure/src/site/markdown/abfs.md
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestGetNameSpaceEnabled.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/TrileanTests.java
Each time an FS instance is created a Getacl call is made. If the call fails with 400 Bad request, the account is determined to be a non-HNS account.
Recommendation is to create a config and be able to avoid store calls to determine account HNS status,
If config is available, use that to determine account HNS status. If config is not present in core-site, default behaviour will be calling getAcl.
**Driver test results using accounts in Central India**
mvn -T 1C -Dparallel-tests=abfs -Dscale -DtestsThreadCount=8 clean verify
**Account with HNS Support**
[INFO] Tests run: 56, Failures: 0, Errors: 0, Skipped: 0
[WARNING] Tests run: 421, Failures: 0, Errors: 0, Skipped: 66
[WARNING] Tests run: 206, Failures: 0, Errors: 0, Skipped: 24
**Account without HNS support**
[INFO] Tests run: 56, …
> HADOOP-17002. ABFS: Adding config to determine if the account is HNS enabled or not

- hadoop-common-project/hadoop-common/pom.xml
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/ftp/FTPFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/ftp/FtpTestServer.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/ftp/TestFTPFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/ftp/TestFtpServer.java
- Making sure an underlying outputstream is successfully created by apache-commons FTPClient before wrapping it with FSDataOutputStream.  
- Gracefully release resources when a destination file can't be created due to lack of permissions.
> HDFS-1820. FTPFileSystem attempts to close the outputstream even when it is not initialised.

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
statfs function in hdfs-fuse is not working. It gives error like:
could not find method org/apache/hadoop/fs/FsStatus from class org/apache/hadoop/fs/FsStatus with signature getUsed
hdfsGetUsed: FsStatus#getUsed error:
NoSuchMethodError: org/apache/hadoop/fs/FsStatusjava.lang.NoSuchMethodError: org/apache/hadoop/fs/FsStatus
Problem: Incorrect passing of parameters in invokeMethod function.
invokeMethod(env, &jVal, INSTANCE, fss, JC_FS_STATUS,
HADOOP_FSSTATUS,"getUsed", "()J");
> HDFS-15301. statfs function in hdfs-fuse not working - fixed.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/HostRestrictingAuthorizationFilter.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/common/TestHostRestrictingAuthorizationFilter.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15320
In HostRestrictingAuthorizationFitler, if there is a request to invalid URI, return 404 response code instead of throwing an exception and logging the stacktrace.
> HDFS-15320. StringIndexOutOfBoundsException in HostRestrictingAuthorizationFilter

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/os/posix/thread_local_storage.c
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/os/windows/thread_local_storage.c
OpenJ9 JVM properly terminates the thread before hdfsThreadDestructor is
invoked. JNIEnv is a mirror of J9VMThread in OpenJ9. After proper thread
termination, accessing JNIEnv in hdfsThreadDestructor (*env)->GetJavaVM,
yields a SIGSEGV since *env is NULL after thread cleanup is performed.
The main purpose of hdfsThreadDestructor is to invoke
DetachCurrentThread, which performs thread cleanup in OpenJ9. Since
OpenJ9 performs thread cleanup before hdfsThreadDestructor is invoked,
hdfsThreadDestructor should account for *env == NULL and skip
DetachCurrentThread.
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>
> HDFS-15270. Account for *env == NULL in hdfsThreadDestructor

- hadoop-minicluster/pom.xml
Ozone has split into independent repo, but the invalid exclusions (kubernetes client) that minicluster dependency on HDFS is kept.
https://issues.apache.org/jira/browse/HDFS-15331
> HDFS-15331. Remove invalid exclusions that minicluster dependency on HDFS

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
This fix is verified with Ranger.
> HDFS-15334. INodeAttributeProvider's new API checkPermissionWithContext not getting called in for authorization.

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/AbstractS3GuardToolTestBase.java
Tested against Tokyo region with the following options. (with the fix of #1950 applied.)
```
$ mvn verify -Ds3guard -Ddynamo -Dtest=x -Dit.test='ITestS3GuardTool*'
```
> HADOOP-17025. Fix invalid metastore configuration in S3GuardTool tests.

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsStreamStatistics.java
In some cases, ABFS-prefetch thread runs in the background which returns some bytes from the buffer and gives an extra readOp. Thus, making readOps values arbitrary and giving intermittent failures in some cases. Hence, readOps values of 2 or 3 are seen in different setups.
test runs: 
- mvn -T 1C -Dparallel-tests=abfs clean verify
- mvn -T 1C -Dparallel-tests=abfs clean verify -Dtest=none -Dit.test=ITestAbfsStreamStatistics
Region: East US, West US
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 165.964 s - in …
```
> HADOOP-17018. Intermittent failing of ITestAbfsStreamStatistics in ABFS

- hadoop-project/pom.xml
The patch compiles. I haven't done any tests beyond making sure it compiles.
> HADOOP-17033. Update commons-codec from 1.11 to 1.14.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsClientConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestObserverReadProxyProvider.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15350
> HDFS-15350. Set dfs.client.failover.random.order to true as default.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/BytesWritable.java
Bounding array size to Integer.MAX_VALUE - 8 to prevent OutOfMemoryError from occurring.
> HADOOP-15524 Bounding array size in BytesWritable to Integer.MAX_VALUE - 8

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ClientContext.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsClientConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/impl/BlockReaderFactory.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/impl/DfsClientConf.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestEnhancedByteBufferAccess.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/client/impl/TestBlockReaderFactory.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/client/impl/TestBlockReaderLocal.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/shortcircuit/TestShortCircuitCache.java
Added parameter dfs.client.short.circuit.num improving HDFS-client's massive reading performance by create few instances ShortCircuit caches instead of one. It helps avoid locks and lets CPU do job.
> HDFS-15202 Boost short circuit cache (rebase PR-1884)

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/InodeTree.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
[HADOOP-17024](https://issues.apache.org/jira/browse/HADOOP-17024). ListStatus on ViewFS root (ls "/") should list the linkFallBack root (configured target root).
> HADOOP-17024. ListStatus on ViewFS root should list the linkFallBack root

- hadoop-common-project/hadoop-common/src/main/bin/hadoop-functions.sh
JIRA: https://issues.apache.org/jira/browse/HDFS-15353
This PR changes privilege escalation from su to sudo in hadoop-functions.sh.
It allows launching secure DataNode by a `--disabled-login`(eg. `/sbin/nologin`) user.
> HDFS-15353. use sudo instead of su to allow nologin user for secure DataNode

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/shortcircuit/DfsClientShmManager.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/shortcircuit/ShortCircuitCache.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/ShortCircuitRegistry.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/shortcircuit/TestShortCircuitCache.java
Signed-off-by: sunlisheng <sunlisheng@xiaomi.com>
> HDFS-13639. SlotReleaser is not fast enough

- LICENSE-binary
- hadoop-common-project/hadoop-common/pom.xml
- hadoop-common-project/hadoop-common/src/main/resources/org.apache.hadoop.application-classloader.properties
- hadoop-project/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17049
Remove javax.activation-api from dependency.
> HADOOP-17049. javax.activation-api and jakarta.activation-api define overlapping classes

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ConfigUtil.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/FsGetter.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/HCFSMountTableConfigLoader.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/NflyFSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFileSystemBaseTest.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFsTestSetup.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
[HDFS-15322. Make NflyFS to work when ViewFsOverloadScheme's scheme and target uris schemes are same.](https://issues.apache.org/jira/browse/HDFS-15322)
> HDFS-15322. Make NflyFS to work when ViewFsOverloadScheme's scheme and target uris schemes are same.

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestBlockingThreadPoolExecutorService.java
The `testSubmitRunnable` expects work queue is filled and subsequent submit will be blocked for certain time. This may not be satisfiled depending on load on the test machine. We can make the situation certain by using CountDownLatch.
> HADOOP-17040. Fix intermittent failure of ITestBlockingThreadPoolExecutorService.

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsClient.java
Idempotency related tests added as part of 
https://issues.apache.org/jira/browse/HADOOP-17015
create a test AbfsClient instance. This mock instance wrongly accepts valid sharedKey and oauth token provider instance instead of only one. This leads to test failures with exception message : 
"Invalid auth type: SharedKey is being used, expecting OAuth"
> HADOOP-17054. ABFS: Fix test AbfsClient authentication instance

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AbfsConfiguration.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/TestAccountConfiguration.java
When AuthType and Auth token provider configs are set for both generic (account-agnostic) and account-specific config, as below:
// account agnostic
fs.azure.account.auth.type=CUSTOM
fs.azure.account.oauth.provider.type=ClassExtendingCustomTokenProviderAdapter
// account specific
fs.azure.account.auth.type.account_name=OAuth
fs.azure.account.oauth.provider.type.account_name=ClassExtendingAccessTokenProvider
Effective token provider for 'account_name' is expected to be ClassExtendingAccessTokenProvider.
But currently, when the token provider class is being read from the config, account-agnostic config setting is read first in the assumption that it can serve as default if account-specific config setting is absent. 
This logic leads to failure such as in above case where AuthType for …
> HADOOP-17053. ABFS: Fix Account-specific OAuth config setting parsing

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/AbfsHttpConstants.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/ConfigurationKeys.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/IdentityTransformer.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/IdentityTransformerInterface.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/LocalIdentityTransformer.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/utils/IdentityHandler.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/utils/TextFileBasedIdentityHandler.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestTextFileBasedIdentityHandler.java
ABFS driver enhancement - Allow customizable translation from AAD SPNs and security groups to Linux user and group
Integration Test results - East US2:
`Tests run: 1283, Failures: 0, Errors: 0, Skipped: 404`
> HDFS-15168: ABFS enhancement to translate AAD to Linux identities.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetUtils.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/TestNetUtils.java
> HADOOP-17052. NetUtils.connect() throws unchecked exception (UnresolvedAddressException) causing clients to abort

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFsTestSetup.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/AdminHelper.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DFSAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestViewFileSystemOverloadSchemeWithDFSAdmin.java
https://issues.apache.org/jira/browse/HDFS-15321
> HDFS-15321. Make DFSAdmin tool to work with ViewFileSystemOverloadScheme

- dev-support/bin/yetus-wrapper
- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
JIRA: https://issues.apache.org/jira/browse/HADOOP-17056
Skip GPG verification in the docker build image.
> HADOOP-17056. shelldoc fails in hadoop-common.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/FullCredentialsTokenBinding.java
Move the local loading to deployUnbonded() (where they are required) and add a safety check when a new DT is requested
Change-Id: I516368c2c4a558a2a86e8cf107f77f1e40338261
> HADOOP-16568. S3A FullCredentialsTokenBinding fails if local credentials are unset

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestFsDatasetImpl.java
…ing multiple DN's data directories
> HDFS-15386. ReplicaNotFoundException keeps happening in DN after removing multiple DN's data directories.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/TestViewfsFileStatus.java
[HADOOP-17029](https://issues.apache.org/jira/browse/HADOOP-17029). ViewFS does not return correct user/group and ACL
> HADOOP-17029. Return correct permission and owner for listing on internal directories in ViewFs

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DFSAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestViewFileSystemOverloadSchemeWithDFSAdmin.java
https://issues.apache.org/jira/browse/HDFS-15389
> HDFS-15389. DFSAdmin should close filesystem and dfsadmin -setBalancerBandwidth should work with ViewFSOverloadScheme.

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/conf/TestCommonConfigurationFields.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
https://issues.apache.org/jira/browse/HDFS-15394
> HDFS-15394. Add all available fs.viewfs.overload.scheme.target.<scheme>.impl classes in core-default.xml bydefault.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeHdfsFileSystemContract.java
https://issues.apache.org/jira/browse/HDFS-15396
> HDFS-15396. Fix TestViewFileSystemOverloadSchemeHdfsFileSystemContract#testListStatusRootDir

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/FsUsage.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemUtil.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestViewFileSystemOverloadSchemeWithFSCommands.java
https://issues.apache.org/jira/browse/HDFS-15387
> HDFS-15387. FSUsage#DF should consider ViewFSOverloadScheme in processPath.

- Jenkinsfile
- dev-support/docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-16888
* Install JDK 11 in the build image.
* Run mvninstall, compile, javac, and javadoc with JDK 8 and JDK 11. (Now javadoc with JDK 11 is broken.)
* Run the unit tests with JDK 8 only. This is because it takes too long to run unit tests with both JDK 8 and JDK 11.
After that, I'll prepare daily qbt jobs for JDK 11. The job will run full unit tests with JDK 11.
> HADOOP-16888. [JDK11] Support JDK11 in the precommit job

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/Stat.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/Delete.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ha/HAAdmin.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/lib/StaticUserWebFilter.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/util/MBeans.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/CachedDNSToSwitchMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetworkTopology.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/TableMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/CompositeGroupsMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/JniBasedUnixGroupsNetgroupMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/LdapGroupsMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/NetgroupCache.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ShellBasedIdMapping.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/web/DelegationTokenAuthenticationHandler.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/service/AbstractService.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/service/CompositeService.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/service/launcher/ServiceLauncher.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/HttpExceptionUtils.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/Shell.java
> HADOOP-17009: Embrace Immutability of Java Collections

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/InodeTree.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
https://issues.apache.org/jira/browse/HDFS-15427
> HDFS-15427. Merged ListStatus with Fallback target filesystem and InternalDirViewFS.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/AbstractDelegationTokenSecretManager.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/ZKDelegationTokenSecretManager.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/token/delegation/TestZKDelegationTokenSecretManager.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/security/token/ZKDelegationTokenSecretManagerImpl.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/security/token/TestZKDelegationTokenSecretManagerImpl.java
Summary:
This patch is targeting improving router's performance
for delegation tokens related operations.
It achieves the goal by removing watchers from router on
tokens since based on our experience. The huge number of
watches inside Zookeeper is degrading Zookeeper's performance
pretty hard. The current limit is about 1.2-1.5 million.
Specific changes:
1. Explicitly disable the watcher to tokens by not using
PathChildrenCache or any curator provided cache at all.
2. Schedule a sync task between router and Zookeeper at
a configurable interval to make routers sync with their
token information through Zookeeper.
3. For token's change, always make sure to change local cache
first instead of depending on callbacks of the watch event
when using PathChildrenCache.
The above three points are …
> HDFS-15383. RBF: Add support for router delegation token without watch

- hadoop-project/pom.xml
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azure/ITestNativeAzureFileSystemConcurrencyLive.java
HADOOP-17089: WASB: Update azure-storage-java SDK
DETAILS: WASB depends on the Azure Storage Java SDK.  There is a concurrency bug in the Azure Storage Java SDK that can cause the results of a list blobs operation to appear empty.  This causes the Filesystem listStatus and similar APIs to return empty results.  This has been seen in Spark work loads when jobs use more than one executor core. 
See https://github.com/Azure/azure-storage-java/pull/546 for details on the bug in the Azure Storage SDK.
TESTS: A new test was added to validate the fix. All tests are passing:
wasb:
mvn -T 1C -Dparallel-tests=wasb -Dscale -DtestsThreadCount=8 clean verify
Tests run: 248, Failures: 0, Errors: 0, Skipped: 11
Tests run: 651, Failures: 0, Errors: 0, Skipped: 65
abfs:
mvn -T 1C -Dparallel-tests=abfs …
> HADOOP-17089: WASB: Update azure-storage-java SDK

- dev-support/docker/Dockerfile
I aligned the versions with the one pulled by frontend-maven-plugin (used in `mvn install -Pyarn-ui`).
* https://github.com/apache/hadoop/blob/branch-3.1/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml#L146-L147
* https://github.com/apache/hadoop/blob/branch-3.1/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/package.json#L22
* https://github.com/apache/hadoop/blob/branch-3.1/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/package.json#L29
The packages installed by apt-get are optional ones for interactive debugging. While I think we should use node.js pulled by frontend-maven-plugin along with the doc added by YARN-10020 (#1750), removing the packages here would surprise existing users of the env.
> HADOOP-17097. start-build-env.sh fails in branch-3.1.

- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml
JIRA: https://issues.apache.org/jira/browse/YARN-10331
Ran `mvn install -DskipTests -Pyarn-ui` locally and it passed.
> YARN-10331. Upgrade node.js to 10.21.0.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/AbstractS3ACommitter.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/Tasks.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/staging/PartitionedStagingCommitter.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/staging/StagingCommitter.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/TestTasks.java
Fixes a condition which can cause job commit to fail if a task was
aborted < 60s before the job commit commenced: the task abort
will shut down the thread pool with a hard exit after 60s; the
job commit POST requests would be scheduled through the same pool,
so be interrupted and fail. At present the access is synchronized,
but presumably the executor shutdown code is calling wait() and releasing
locks.
Task abort is triggered from the AM when task attempts succeed but
there are still active speculative task attempts running. Thus it
only surfaces when speculation is enabled and the final tasks are
speculating, which, given they are the stragglers, is not
unheard of.
The fix copies and clears the threadPool field in a synchronized block,
then shuts it down; …
> HADOOP-16798. S3A Committer thread pool shutdown problems.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/viewfs/ViewFileSystemBaseTest.java
[HADOOP-17032](https://issues.apache.org/jira/browse/HADOOP-17032). Handle an internal dir in viewfs having multiple children mount points pointing to different filesystems
> HADOOP-17032. Fix getContentSummary in ViewFileSystem to handle multiple children mountpoints pointing to different filesystems

- Jenkinsfile
JIRA: https://issues.apache.org/jira/browse/HADOOP-17090
> HADOOP-17090. Increase precommit job timeout from 5 hours to 20 hours.

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStream.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStreamContext.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStreamStatistics.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStreamStatisticsImpl.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsInputStreamStatistics.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/TestAbfsInputStreamStatistics.java
Test run by: mvn -T 1C -Dparallel-tests=abfs clean verify
Region: East US, West US
```
[INFO]
[INFO] Tests run: 77, Failures: 0, Errors: 0, Skipped: 0
```
```
[INFO]
[WARNING] Tests run: 443, Failures: 0, Errors: 0, Skipped: 70
```
```
[INFO]
[WARNING] Tests run: 206, Failures: 0, Errors: 0, Skipped: 29
```
Relates to #1946
> Hadoop 16961. ABFS: Adding metrics to AbfsInputStream

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsLinkFallback.java
https://issues.apache.org/jira/browse/HDFS-15430
> HDFS-15430. create should work when parent dir is internalDir and fallback configured.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/impl/MetricsSystemImpl.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/metrics2/impl/TestMetricsSystemImpl.java
What changed
- The sink registration starts the adapter if it doesn't exists.
> HADOOP-17081. MetricsSystem doesn't start the sink adapters on restart

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterRpcServer.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/java/org/apache/hadoop/hdfs/server/federation/router/RouterWebHdfsMethods.java
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterRpc.java
https://issues.apache.org/jira/browse/HDFS-15417
> HDFS-15417. RBF: Get the datanode report from cache for federation WebHDFS operations

- dev-support/docker/Dockerfile
Since [isort 5.x does not support Python 2](https://github.com/timothycrosley/isort/blob/master/CHANGELOG.md#500-penny---july-4-2020), I pinned the version of isort to the latest of 4.x.
> HADOOP-17120. Fix failure of docker image creation due to pip2 install error.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/pom.xml
JIRA: https://issues.apache.org/jira/browse/YARN-10344
Before:
```
[INFO] --- maven-dependency-plugin:3.0.2:tree (default-cli) @ hadoop-yarn-csi ---
[INFO] org.apache.hadoop:hadoop-yarn-csi:jar:3.3.0
[INFO] +- com.google.guava:guava:jar:20.0:compile
[INFO] +- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO] +- io.netty:netty-all:jar:4.1.50.Final:compile
[INFO] +- io.grpc:grpc-core:jar:1.26.0:compile
[INFO] |  +- io.grpc:grpc-api:jar:1.26.0:compile (version selected from constraint [1.26.0,1.26.0])
[INFO] |  |  +- io.grpc:grpc-context:jar:1.26.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.3:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] |  +- …
```
> YARN-10344. Sync netty versions in hadoop-yarn-csi.

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/conf/TestCommonConfigurationFields.java
https://issues.apache.org/jira/browse/HDFS-15462
HDFS-15394 added existing FS implementations in core-default.xml except ofs. Let's add ofs to core-default as well.
> HDFS-15462. Add fs.viewfs.overload.scheme.target.ofs.impl to core-default.xml

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AFileOperationCost.java
S3AFS does not support symlinks, so attempting to resolve
symlinks in globStatus causes wasted S3 calls and worse
performance. Removing it will speed up some calls to
globStatus.
JIRA link: https://issues.apache.org/jira/browse/HADOOP-17105
> HADOOP-17105: S3AFS - Do not attempt to resolve symlinks in globStatus

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapreduce/lib/input/TestCombineFileInputFormat.java
JIRA: https://issues.apache.org/jira/browse/MAPREDUCE-7284
> MAPREDUCE-7284. TestCombineFileInputFormat#testMissingBlocks fails

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java
Testing: Not sure what all specific test suites to run but I ran some tests which uses this method directly or transitively and they ran fine.
> HADOOP-17130 Configuration.getValByRegex() shouldn't be updating the results while fetching

- hadoop-project/pom.xml
We are using spotbufs 3.1.0-RC1. Newer released versions could be available now. The changes described on the [migration guide](https://spotbugs.readthedocs.io/en/stable/migration.html) seems to be not so disruptive.
> HADOOP-16866. Upgrade spotbugs to 4.0.6.

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/lib/common/async_stream.h
The executor_ member of the AsyncStream class is public, but there is a getter get_executor() that returns this executor_ member. This member should be private.
> HDFS-15476 Make AsyncStream executor private

- hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs
- hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs.cmd
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/EditLogInputStream.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FsImageValidation.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeReference.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeReferenceValidation.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsImageValidation.java
Please see https://issues.apache.org/jira/browse/HDFS-15463
> HDFS-15463. Add a tool to validate FsImage.

- hadoop-tools/hadoop-azure/pom.xml
tested: ireland
ran with 
1.  -Dparallel-tests=both 
1.  -Dparallel-tests=abfs
1.   -Dparallel-tests=wasb
all profiles worked as far as launching tests without showing errors and running all unit tests in parallel. I'm not 100% sure
> HADOOP-17107. hadoop-azure parallel tests not working on recent JDKs

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/ITestS3ADirectoryPerformance.java
Re ran the failed test. It is passing now.
> HADOOP-17136 ITestS3ADirectoryPerformance.testListOperations failing because of HADOOP-17022

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsRestOperation.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemDelete.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemRename.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsClient.java
Trigger to call the idempotent code introduced in https://issues.apache.org/jira/browse/HADOOP-17015 is incomplete. 
When a request fails at the AbfsRestOperation, an exception is thrown from the REST response handling code . HADOOP-17015 was failing to catch it before checking the AbfsRestOperation instance status code.
The request retry count was also getting set to 1 even when request wasnt re-tired. That has been fixed too.
Tests are added by setting final fields in AbfsClient by reflection and mimicking the idempotency check return values to ensure that the trigger handles all scenarios.
> Hadoop 17132. ABFS: Fix Rename and Delete Idempotency check trigger

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStream.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStreamStatistics.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStreamStatisticsImpl.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsInputStreamStatistics.java
tested by: mvn -T 1C -Dparallel-tests=abfs clean verify
Region: East US, West US
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:11 min (Wall Clock)
[INFO] Finished at: 2020-07-20T20:39:21+05:30
```
> HADOOP-17113. Adding ReadAhead Counters in ABFS

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/HdfsServerConstants.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirSnapshotOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirXAttrOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestOrderedSnapshotDeletion.java
Please see https://issues.apache.org/jira/browse/HDFS-15480
> HDFS-15480. Ordered snapshot deletion: record snapshot deletion in XAttr

- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
JIRA: https://issues.apache.org/jira/browse/YARN-10367
Install the latest 10.x version of nodejs in the docker image.
> YARN-10367. Failed to get nodejs 10.21.0 when building docker image

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/lib/MultipleOutputFormat.java
In org.apache.hadoop.mapred.lib.MultipleOutputFormat, there is a typo for the java doc of getInputFileBasedOutputFileName method. 
"the outfile name based on a given anme and the input file name" should be "the outfile name based on a given name and the input file name"
> MAPREDUCE-7051. Fix typo in MultipleOutputFormat

- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/CMakeLists.txt
libhdfspp.{a,so} are missed in dist-package.
This patch fixed this by copying these libs to the right directory
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
> HDFS-14950. fix missing libhdfspp lib in dist-package

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/SnapshotStatus.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelperClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/hdfs.proto
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestListSnapshot.java
please see https://issues.apache.org/jira/browse/HDFS-15498
> HDFS-15498. Show snapshots deletion status in snapList cmd.

- Jenkinsfile
- hadoop-common-project/hadoop-common/pom.xml
- hadoop-hdfs-project/hadoop-hdfs-client/pom.xml
- hadoop-hdfs-project/hadoop-hdfs-rbf/pom.xml
- hadoop-hdfs-project/hadoop-hdfs/pom.xml
- hadoop-project/pom.xml
- hadoop-tools/hadoop-aws/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17091
* Set javadoc goals to "process-sources javadoc:javadoc-no-fork" to replace `com.google.protobuf.*` with `org.apache.hadoop.thirdparty.protobuf.*` before running javadoc.
* Use Yetus master to include https://issues.apache.org/jira/browse/YETUS-972
* Fix the following error by setting the source version to 8. Reference: https://bugs.openjdk.java.net/browse/JDK-8212233
* Skip failing modules in jdk11 for now.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project hadoop-annotations: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: warning - You have specified the HTML version as HTML 4.01 by using the -html4 option.
[ERROR] The …
```
> HADOOP-17091. [JDK11] Fix Javadoc errors

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/markdown/YarnCommands.md
I have found the "YARN-10366." Fix Yarn rmadmin help message,but the markdown document(YarnCommands.md) unsynchronized changes,so I fix it.
> YARN-10383. Fix Yarn rmadmin Markdown document

- hadoop-project/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17179
Skip Java API link detection
> HADOOP-17179. [JDK 11] Fix javadoc error in Java API link detection

- hadoop-hdfs-project/hadoop-hdfs-httpfs/pom.xml
This was based on discussion that we need to update the s3 to bundle for dependencies after HADOOP-14040. However, when I checked it now, I did not find `aws-java-sdk-s3` included in the httpfs module
```
$ mvn clean dependency:tree -Dverbose | grep aws
$ echo $?
1
$
```
The reason is that, hadoop-common and hadoop-hdfs modules do not include this aws s3 sdk any longer. So this PR is to clean that up to avoid confusion.
> HDFS-15499. Clean up httpfs/pom.xml to remove aws-java-sdk-s3 exclusion

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestUGILoginFromKeytab.java
See #2178 for related change for Hadoop 3.x
> HADOOP-17164. UGI loginUserFromKeytab doesn't set the last login time

- hadoop-mapreduce-project/hadoop-mapreduce-examples/src/test/java/org/apache/hadoop/examples/pi/math/TestLongLong.java
In the testRightShift method is not implements the right verify operations.
https://issues.apache.org/jira/browse/MAPREDUCE-7288
> MAPREDUCE-7288. Fix TestLongLong#testRightShift

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/FileSystemConfigurations.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemCheckAccess.java
ABFS: Enabling checkaccess API
**With checkaccess test configs**
**SharedKey**
**Account without HNS support**
[ERROR] Errors: 
[ERROR]   ITestAbfsInputStreamStatistics.testReadAheadCounters:346 » TestTimedOut test t...
[INFO] 
[ERROR] Tests run: 451, Failures: 0, Errors: 1, Skipped: 244
[WARNING] Tests run: 207, Failures: 0, Errors: 0, Skipped: 16
**Account with HNS support**
[ERROR] Errors: 
[ERROR]   ITestAbfsInputStreamStatistics.testReadAheadCounters:346 » TestTimedOut test t...
[ERROR]   ITestGetNameSpaceEnabled.testFailedRequestWhenCredentialsNotCorrect:160->AbstractAbfsIntegrationTest.getFileSystem:254 » KeyProvider
[INFO] 
[ERROR] Tests run: 451, Failures: 0, Errors: …
> HADOOP-17183. ABFS: Enabling checkaccess on ABFS

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeReference.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeSymlink.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeWithAdditionalFields.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectoryWithSnapshotFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/visitor/NamespacePrintVisitor.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/visitor/NamespaceVisitor.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/visitor/package.html
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSImageWithSnapshot.java
https://issues.apache.org/jira/browse/HDFS-15520
> HDFS-15520 Use visitor pattern to visit namespace tree

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
https://issues.apache.org/jira/browse/HDFS-15515
> HDFS-15515: mkdirs on fallback should throw IOE out instead of suppressing and returning false

- hadoop-common-project/hadoop-common/HadoopCommon.cmake
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/CMakeLists.txt
- hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/CMakeLists.txt
* Passing C/C++ standard flags -std is
not cross-compiler friendly as not all
compilers support all values.
* Thus, we need to make use of the
appropriate flags provided by CMake in
order to specify the C/C++ standards.
> HADOOP-17196 Fix C/C++ standard warnings

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/visitor/NamespacePrintVisitor.java
See https://issues.apache.org/jira/browse/HDFS-15523
> HDFS-15523. Fix findbugs warnings.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
Fixed String operationName = ListSnapshot.
Link: [https://issues.apache.org/jira/browse/HDFS-15518](https://issues.apache.org/jira/browse/HDFS-15518)
> HDFS-15518. Fixed String operationName = ListSnapshot.

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/ITestS3AHugeFilesSSECDiskBlocks.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/S3AScaleTestBase.java
Disabling caching of configuration object in test.
Re ran the failing test using ap-south-1 bucket. Succeeding now. 
CC @steveloughran
> HADOOP-17192 Fixing ITestS3AHugeFilesSSECDiskBlock

- BUILDING.txt
`mvn site` fails without python2.
```
[INFO] --- exec-maven-plugin:1.3.1:exec (shelldocs) @ hadoop-common ---
/usr/bin/env: ‘python2’: No such file or directory
```
shelldocs.py and releasedocmaker.py requires python2.
```
$ grep -r python2 patchprocess
patchprocess/apache-yetus-0.10.0/lib/shelldocs/shelldocs/__init__.py:#!/usr/bin/env python2
patchprocess/apache-yetus-0.10.0/lib/shelldocs/shelldocs.py:#!/usr/bin/env python2
patchprocess/apache-yetus-0.10.0/lib/releasedocmaker/releasedocmaker/__init__.py:#!/usr/bin/env python2
patchprocess/apache-yetus-0.10.0/lib/releasedocmaker/releasedocmaker/utils.py:#!/usr/bin/env python2
patchprocess/apache-yetus-0.10.0/lib/releasedocmaker/releasedocmaker.py:#!/usr/bin/env python2
patchprocess/apache-yetus-0.10.0/lib/precommit/test-patch-docker/Docker …
```
> HADOOP-17206. Add python2 to required package on CentOS 8 for building documentation.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirSnapshotOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestOrderedSnapshotDeletionGc.java
please check https://issues.apache.org/jira/browse/HDFS-15524
> HDFS-15524. Add edit log entry for Snapshot deletion GC thread snapshot deletion.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FsImageValidation.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeMap.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeReferenceValidation.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/visitor/INodeCountVisitor.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsImageValidation.java
See https://issues.apache.org/jira/browse/HDFS-15519
> HDFS-15519. Check inaccessible INodes in FsImageValidation.

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
Store REST API version on the backend clusters has been upgraded to 2019-12-12. This Jira will align the Driver requests to reflect this latest API version.
Test results from accounts in East US2 region:
```
With Namespace enabled account:  
----------------------------------------
1. With Authentication Type: OAuth
[WARNING] Tests run: 451, Failures: 0, Errors: 0, Skipped: 74
[WARNING] Tests run: 207, Failures: 0, Errors: 0, Skipped: 140
2. With Authentication Type: SharedKey
[WARNING] Tests run: 451, Failures: 0, Errors: 0, Skipped: 41
[WARNING] Tests run: 207, Failures: 0, Errors: 0, Skipped: 24
With Namespace not-enabled account:  
---------------------------------------- …
```
> HADOOP-16966. ABFS: Upgrade store REST API version to 2019-12-12

- Jenkinsfile
- dev-support/bin/hadoop.sh
Currently for CI build and testing we maintain personality scripts in both Apache Yetus and Apache Hadoop. This poses problem when one needs to change both places, for example HADOOP-17125.
This proposes to move the personality file into the Hadoop repo itself, so that we can manage them in a single place. The downside for this is we may need to duplicate the scripts in every branch.
> HADOOP-17205. Move personality file from Yetus to Hadoop repository

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/web/resources/NamenodeWebHdfsMethods.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHDFS.java
https://issues.apache.org/jira/browse/HDFS-15525
Added new test `TestWebHDFS#testGetSnapshotTrashRoot`.
> HDFS-15525. Make trash root inside each snapshottable directory for WebHDFS

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/impl/MetricsConfig.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/metrics2/impl/TestMetricsConfig.java
> HADOOP-16925 MetricsConfig incorrectly loads the configuration whose value is String list in the properties file

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemRandomRead.java
HADOOP-16915. ABFS: Ignoring the test ITestAzureBlobFileSystemRandomRead.testRandomReadPerformance
ABFS accounts are primarily for customers to use with HNS property enabled. A non-HNS enabled ABFS account will not provide much value add in comparison to WASB account. The test case ITestAzureBlobFileSystemRandomRead#testRandomReadPerformance that tries to compare non-HNS to WASB performance hence isn't significant and can deviate in the perf in minor ways over time. Non-HNS not being a primary use case for ABFS, ignoring this test which currently fails randomly as it crosses test perf threshold.
> HADOOP-16915. ABFS: Ignoring the test ITestAzureBlobFileSystemRandomRead.testRandomReadPerformance

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestUGILoginFromKeytab.java
> HADOOP-17159 Ability for forceful relogin in UserGroupInformation class

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Listing.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/ListingOperationCallbacks.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/TestPartialDeleteFailures.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/ITestS3ADirectoryPerformance.java
Tested using ap-south-1 bucket. All good apart from known failures. 
https://issues.apache.org/jira/browse/HADOOP-17192
https://issues.apache.org/jira/browse/HADOOP-17190
> HADOOP-17074 Optimise s3a Listing to be fully asynchronous.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractGetFileStatusTest.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/InconsistentAmazonS3Client.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ListResult.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/DirectoryPolicy.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/DirectoryPolicyImpl.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/StatusProbeEnum.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/directory_markers.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/index.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AFileOperationCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestS3AGetFileStatus.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/TestDirectoryMarkerPolicy.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/ITestDirectoryMarkerListing.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/OperationCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/OperationCostValidator.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/AbstractS3GuardToolTestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/test/costs/HeadListCosts.java
This is a backport of part of #2149 for listing compatibility
This is only the minimal set of list changes; no intent of changing marker retention policy. It should be transparent to all clients
* list/getFileStatus changes
* backwards compatible test of new algorithm
* new tests to verify marker handling
* marker rename bug  (HADOOP-17200) surfacing in testing
It's only a subset of the main PR and critical for compat, so I'm not expecting reviews here, though if someone wants to critique my code, they are always welcome :). What is key is that unless it's backport-specific, the change should go into trunk and then be pulled in here
> HADOOP-17199. S3A Directory Marker backport to branch-3.2

- dev-support/docker/Dockerfile
> HADOOP-17224. Install Intel ISA-L library in Dockerfile.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/AbstractINodeDiffList.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DiffListByArrayList.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectoryWithSnapshotFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
See https://issues.apache.org/jira/browse/HDFS-15500
> HDFS-15500. In-order deletion of snapshots: Diff lists must be update only in the last snapshot

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClientContext.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClientContextBuilder.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsClient.java
Tested on: mvn -T 1C -Dparallel-tests=abfs clean verify
Region: East US
```
[INFO]
```
```
[INFO]
[ERROR] Errors:
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR] …
```
> HADOOP-17194. Adding Context class for AbfsClient in ABFS

- hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html
- hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.js
- hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/static/hadoop.css
This patch adds expandable rows to snapshottable directories table to view a list of snapshots under it. Also, users can now sort and filter all the columns in the tables.
https://issues.apache.org/jira/browse/HDFS-15531
> HDFS-15531. Namenode UI: List snapshots in separate table for each snapshottable directory

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestUGILoginFromKeytab.java
This is the PR for `branch-2.10`, backporting #2249
> HADOOP-17159. Make UGI support forceful relogin from keytab ignoring the last login time (branch-2.10)

- .asf.yaml
https://issues.apache.org/jira/browse/HADOOP-17234
> HADOOP-17234. Add .asf.yaml to allow Github to Jira integration.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractMultipartUploaderTest.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractMultipartUploader.java
Contributed by Steve Loughran
(Also: broken by Steve Loughran)
PR includes a minor change to the HDFS Code to ensure yetus is happy; main
change is that the eventually() clause is skipped on a consistent store,
because it is not needed.
> HDFS-15471. TestHDFSContractMultipartUploader failing

- hadoop-yarn-project/hadoop-yarn/dev-support/findbugs-exclude.xml
Please refer to the comments of [YARN-10358](https://issues.apache.org/jira/browse/YARN-10358) for description.
> YARN-10358. Fix findbugs warnings in hadoop-yarn-project on branch-2.10.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/InodeTree.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemOverloadSchemeWithHdfsScheme.java
https://issues.apache.org/jira/browse/HDFS-15529
> HDFS-15529: getChildFilesystems should include fallback fs as well

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AEncryptionWithDefaultS3Settings.java
Tested by running this test only against ap-south-1 bucket configured with all three encryption algo.
> HADOOP-17167 Skipping ITestS3AEncryptionWithDefaultS3Settings.testEncryptionOverRename

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/tools/MarkerTool.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/directory_markers.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/AbstractS3ATestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/tools/AbstractMarkerToolTest.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/tools/ITestMarkerTool.java
* move from -expect to -min and -max; easier for CLI testing. Plus works
* in -nonauth mode, even when policy == keep, files not in an auth path
count as failure.
* bucket-info option also prints out the authoritative path, so you have
more idea what is happening
* reporting of command failure more informative
The reason for change #2 is a workflow where you want to audit a dir, even
though you are in keep mode, and you don't have any auth path. You'd expect
-nonauth to say "no auth path", but instead it treats the whole dir as
auth.
[https://issues.apache.org/jira/browse/HADOOP-17227](https://issues.apache.org/jira/browse/HADOOP-17227)
> HADOOP-17227. Marker Tool tuning

- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
Add RootedOzoneFs to core-default similar to other filesystems.
Added o3fs also which is missing.
https://issues.apache.org/jira/browse/HADOOP-17245
> HADOOP-17245. Add OzoneFileSystem classes to core-default.xml.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseRecovery.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15558
> HDFS-15558: ViewDistributedFileSystem#recoverLease should call super.recoverLease when there are no mounts configured

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsInputStream.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsInputStreamStatistics.java
Tested by: mvn -T 1C -Dparallel-tests=abfs clean verify
Region: East US.
```
[INFO]
```
```
[INFO]
[ERROR] Tests run: 450, Failures: 0, Errors: 12, Skipped: 61
```
[Errors being discussed in HADOOP-17203]
```
[INFO]
[WARNING] Tests run: 206, Failures: 0, Errors: 0, Skipped: 29
```
> HADOOP-17158. Test timeout for ITestAbfsInputStreamStatistics#testReadAheadCounters

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsRestOperation.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAbfsNetworkStatistics.java
After a response failure at the moment, there is an increment to the bytes_received counter value which shouldn't increment.
Test-run: mvn -T 1C -Dparallel-tests=abfs clean verify
```
[INFO]
```
```
[INFO]
[ERROR] Errors:
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR]   ITestAzureBlobFileSystemCheckAccess.<init>:82->setTestUserFs:104 » IllegalArgument
[ERROR] …
```
> HADOOP-17229. No updation of bytes received counter value after response failure occurs in ABFS

- hadoop-project/pom.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/pom.xml
This is backporting [HADOOP-16905](https://issues.apache.org/jira/browse/HADOOP-16905) to branch-2.10. I used the same version of jackson-databind and maven-shade-plugin used in the current trunk.
maven-shade-plugin must be updated to 3.2.0 or above to fix error on creating jar of hadoop-yarn-server-applicationhistoryservice.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project hadoop-yarn-server-applicationhistoryservice: Error creating shaded jar: null: IllegalArgumentException -> [Help 1]
```
> HADOOP-17249. Upgrade jackson-databind to 2.9.10.6 on branch-2.10.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractSeekTest.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractUnbufferTest.java
* Fixes Seek test to readFully
* Doesn't do this to the unbuffer test as it changes the test too much.
Instead just note in error that this may be transient
> HADOOP-17181. Fix transient stream read failures in FileSystem contract tests

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/DecayRpcScheduler.java
- hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
- hadoop-common-project/hadoop-common/src/site/markdown/FairCallQueue.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/conf/TestCommonConfigurationFields.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/ipc/TestDecayRpcScheduler.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17165
This PR is following the [HADOOP-17165](https://issues.apache.org/jira/browse/HADOOP-17165).
Diff from HADOOP-17165.002.patch
* Fixed a failed test of TestCommonConfigurationFields.
* Use Set<String> for return type and field type.
* Save the priorities of service users in cache.
> HADOOP-17165. Implement service-user feature in DecayRPCScheduler.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15563
This may impact clusters with `dfs.namenode.snapshot.trashroot.enabled` is set to `true`.
> HDFS-15563. Incorrect getTrashRoot return value when a non-snapshottable dir prefix matches the path of a snapshottable dir

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetUtils.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/TestNetUtils.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestSecurityUtil.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsClientConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/impl/DfsClientConf.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/tools/TestHdfsConfigFields.java
https://issues.apache.org/jira/browse/HADOOP-17222
Create socket address combined with cache to speed up hdfs client choose DataNode
> HADOOP-17222. Create socket address combined with URI cache

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DeadNodeDetector.java
[JIRA URL](https://issues.apache.org/jira/browse/HDFS-15551)
1. add or improve some logs for adding local & global deadnodes
2. logic improve
3. fix typo
> HDFS-15551. Tiny Improve for DeadNode detector

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsLinkFallback.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystemContract.java
https://issues.apache.org/jira/browse/HDFS-15532
> HDFS-15532: listFiles on root/InternalDir will fail if fallback root has file.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15539
I initially intended to put the logic in `SnapshotManager#resetSnapshottable`.
But later I figured it makes more sense to put the check on the client side instead:
1. Trash is more of a client-side concept.
2. As a result of (1), it is much cleaner to add the check on the client than on the server side.
> HDFS-15539. When disallowing snapshot on a dir, throw exception if its trash root is not empty	

- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
When I build the docker-build image under macOS, it failed caused by:
```
----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vKHcWu/isort/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-odL0bY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vKHcWu/isort/
You are using pip version 8.1.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/bash -o pipefail -c pip2 install     configparser==4.0.2     pylint==1.9.2' returned a non-zero code: 1
``` …
> HADOOP-17246. Fix build the hadoop-build Docker image failed

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectorySnapshottableFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestSnapshotManager.java
please see https://issues.apache.org/jira/browse/HDFS-15568
> HDFS-15568. namenode start failed to start when dfs.namenode.max.snapshot.limit set.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestViewDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15585
> HDFS-15585: ViewDFS#getDelegationToken should not throw UnsupportedOperationException.

- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/filesystem.md
https://issues.apache.org/jira/browse/HADOOP-15136
> HADOOP-15136. Correct typos in filesystem.md

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/constants/FileSystemConfigurations.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemCheckAccess.java
This reverts commit a2610e21ed5289323d8a6f6359477a8ceb2db2eb.
> HADOOP-17203: Revert "HADOOP-17183. ABFS: Enabling checkaccess on ABFS"

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/main/java/org/apache/hadoop/mapreduce/v2/app/job/impl/JobImpl.java
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/test/java/org/apache/hadoop/mapreduce/v2/app/job/impl/TestJobImpl.java
- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/Job.java
…esource to yarn shared cache manager.
> MAPREDUCE-7294. Fix the bug to make sure only application master upload resource to Yarn Shared Cache

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Listing.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AUtils.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3Guard.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AFileOperationCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/S3ATestUtils.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/TestPartialDeleteFailures.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/OperationCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/TestS3Guard.java
S3AFileSystem.listStatus() to perform list operations
directly and then fallback to head checks for files
Tested using ap-south-1 bucket in following modes along with scale tests:
1) Raw s3.
2) Auth S3guard.
3) Non auth s3guard. 
All good.
> HADOOP-17023 Tune S3AFileSystem.listStatus() api.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/RenameOperation.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/troubleshooting_s3a.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/ITestPartialRenamesDeletes.java
Stop using the versionId when building the list of files
to delete as the rename progresses
Testing: manual. For anyone wishing to replicate the problem on an unpatched release
1. Have a versioned bucket.
1. Latest version of cloudstore now allows you to create a set of session keys from an IAM role and json file, printing them as env vars and hadoop config options
1.  You need S3Guard enabled and the files to have been created individually by a client through S3Guard (i.e. the entries not discovered through listing). Then S3Guard caches the version ID in the DB, which is then used when deleting the object.
1. mkdir src/; touchz src/file1 file2
2. mv src dst
if that works, try renaming back.
> HADOOP-17261. s3a rename() needs s3:deleteObjectVersion permission

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/util/AtomicFileOutputStream.java
https://issues.apache.org/jira/browse/HDFS-15557
> HDFS-15557. Log the reason why a storage log file can't be deleted

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/DirectorySnapshottableFeature.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/snapshot/SnapshotManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSnapshotCommands.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestOrderedSnapshotDeletion.java
please see https://issues.apache.org/jira/browse/HDFS-15590
> HDFS-15590. namenode fails to start when ordered snapshot deletion feature is disabled

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/StorageType.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/Count.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/shell/TestCount.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsConstants.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelperClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/hdfs.proto
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockStoragePolicySuite.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/FsVolumeSpi.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsVolumeImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DFSAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/ArchivalStorage.md
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/HdfsQuotaAdminGuide.md
- hadoop-hdfs-project/hadoop-hdfs/src/site/markdown/WebHDFS.md
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestBlockStoragePolicy.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/net/TestDFSNetworkTopology.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/protocolPB/TestPBHelper.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/security/token/block/TestBlockToken.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockStatsMXBean.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestDatanodeManager.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/SimulatedFSDataset.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDataDirs.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDirectoryScanner.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/extdataset/ExternalVolumeImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestFsVolumeList.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestReservedSpaceCalculator.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNamenodeStorageDirectives.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/sps/TestExternalStoragePolicySatisfier.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHDFS.java
The non-volatile memory NVDIMM is faster than SSD,
it can be used simultaneously with RAM, DISK and SSD.
Storing the data of HDFS on NVDIMM directly will get
better response rate and reliability.
> HDFS-15025. Applying NVDIMM storage media to HDFS

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15596
> HDFS-15596: ViewHDFS#create(f, permission, cflags, bufferSize, replication, blockSize, progress, checksumOpt) should not be restricted to DFS only.

- dev-support/docker/Dockerfile
- dev-support/docker/Dockerfile_aarch64
libzstd1-dev is a transitional package on Ubuntu 18.04. It is better to use libzstd-dev instead of libzstd1-dev in the Dockerfile (dev-support/docker/Dockerfile).
I have tested this patch in a docker container, and the results are as follows:
1. zstd version
```
hadoop@ac937c1afb72:~/hadoop$ sudo apt search libzstd
Sorting... Done
Full Text Search... Done
libzstd-dev/bionic-updates,bionic-security,now 1.3.3+dfsg-2ubuntu1.1 amd64 [installed]
fast lossless compression algorithm -- development files
libzstd1/bionic-updates,bionic-security,now 1.3.3+dfsg-2ubuntu1.1 amd64 [installed]
fast lossless compression algorithm
libzstd1-dev/bionic-updates,bionic-security 1.3.3+dfsg-2ubuntu1.1 amd64
transitional package for libzstd-dev
```
2. Is zstd enabled?
The result of `cd …
> HADOOP-17282. libzstd-dev should be used instead of libzstd1-dev on Ubuntu 18.04 or higher.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ClientRMService.java
Link to JIRA: https://issues.apache.org/jira/browse/YARN-10438
Error Message:
java.lang.NullPointerException
at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getContainerReport(ClientRMService.java:473)
at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getContainerReport(ApplicationClientProtocolPBServiceImpl.java:453)
at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:591)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822) …
> YARN-10438. Handle null containerId in ClientRMService#getContainerReport()

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManagerSafeMode.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockManagerSafeMode.java
https://issues.apache.org/jira/browse/HDFS-15594
> HDFS-15594. Lazy calculate live datanodes in safe mode tip

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
HDFS reuses the same cached FileSystem object across the file system. If the client calls FileSystem.close(), closeAllForUgi(), or closeAll() (if it applies to the instance) anywhere in the system it purges the cache of that FS instance, and trying to use the instance results in an IOException: FileSystem closed.
It would be a great help to clients to see where and when a given FS instance was closed. I.e. in close(), closeAllForUgi(), or closeAll(), it would be great to see a DEBUG-level log of
- calling method name, class, file name/line number
- FileSystem object's identity hash (FileSystem.close() only)
> HADOOP-17267: Add debug-level logs in Filesystem#close

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterQuota.java
After "NVDIMM" adding, we have six storage types. This
fixes the related test.
> HDFS-15600 Fix TestRouterQuota#testStorageTypeQuota

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/AbstractJavaKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/BouncyCastleFipsKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/JavaKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/KeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/LocalBouncyCastleFipsKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/LocalJavaKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/LocalKeyStoreProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/alias/package-info.java
- hadoop-common-project/hadoop-common/src/main/resources/META-INF/services/org.apache.hadoop.security.alias.CredentialProviderFactory
- hadoop-common-project/hadoop-common/src/site/markdown/CredentialProviderAPI.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/alias/TestCredentialProviderFactory.java
https://issues.apache.org/jira/browse/HADOOP-17284
Adding support for Bouncy Castle FIPS keystore type for Hadoop Credential Provider. 
This is a compatible change that support bcfks and localbcfks similar to jceks and localjceks. Test has been done manually with FIPS enabled OS/JDK.
`hadoop credential create pass1 -value changeit -provider localbcfks://file/tmp/test.bcfks
pass1 has been successfully created.
Provider localbcfks://file/tmp/test.bcfks was updated.
hadoop credential list -provider localbcfks://file/tmp/test.bcfks
Listing aliases for CredentialProvider: localbcfks://file/tmp/test.bcfks
pass1
root@xyao-fips-1 jars]# hadoop credential delete pass1 -provider bcfks://file/tmp/test.bcfks.2
You are about to DELETE the credential pass1 from CredentialProvider …
> HADOOP-17284. Support BCFKS keystores for Hadoop Credential Provider.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/ViewDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DFSAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestDFSAdmin.java
https://issues.apache.org/jira/browse/HDFS-15607
- Snapshottable directory trash root will be automatically provisioned (with permission 777 and sticky bit) when allowing snapshot via DFSAdmin command, if `dfs.namenode.snapshot.trashroot.enabled` is set to `true` on the NameNode.
- Note that calling `DistributedFileSystem#allowSnapshot` directly will NOT provision trash root at all. This behavior is aligned with `DistributedFileSystem#createEncryptionZone`.
```bash
$ hdfs dfsadmin -allowSnapshot /ssdir3/
Allowing snapshot on /ssdir3/ succeeded
$ hdfs dfs -ls /ssdir3
Found 1 items
drwxrwxrwt   - smeng supergroup          0 2020-09-30 00:00 /ssdir3/.Trash
```
- Added new dfsadmin command `-provisionSnapshotTrash`. Admins can use this new command to provision trash roots when the cluster is …
> HDFS-15607. Create trash dir when allowing snapshottable dir

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNameNodeRetryCacheMetrics.java
> HDFS-15458. TestNameNodeRetryCacheMetrics fails intermittently

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/main/java/org/apache/hadoop/mapreduce/jobhistory/JobHistoryEventHandler.java
- hadoop-tools/hadoop-archive-logs/src/site/markdown/HadoopArchiveLogs.md
> HADOOP-17294. Fix typos existance to existence

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-common-project/hadoop-common/src/site/markdown/filesystem/filesystem.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractGetFileStatusTest.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractRootDirectoryTest.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/ContractTestUtils.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/scale/ITestS3ADirectoryPerformance.java
Ran the new test using ap-south-1 bucket. 
O/P- 
`(ContractTestUtils.java:end(1847)) - Duration of listing 1000 files using listFiles() api with batch size of 10 including 10ms of processing time for each file: 12,223,848,028 nS
2020-10-01 12:19:28,811 [JUnit-testMultiPagesListingPerformanceAndCorrectness] INFO  contract.ContractTestUtils (ContractTestUtils.java:end(1847)) - Duration of listing 1000 files using listStatus() api with batch size of 10 including 10ms of processing time for each file: 15,988,037,357 nS
2020-10-01 12:19:41,050 [JUnit-testMultiPagesListingPerformanceAndCorrectness] INFO  contract.ContractTestUtils (ContractTestUtils.java:end(1847)) - Duration of listing 1000 files using listStatusIterator() api with batch size of 10 including 10ms of processing time for each …
> HADOOP-17281 Implement FileSystem.listStatusIterator() in S3AFileSystem

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
Apache jira:
https://issues.apache.org/jira/browse/HDFS-15610
Description:
There is a kernel overhead on datanode upgrade. If datanode with millions of blocks and 10+ disks then block-layout migration will be super expensive during its hardlink operation.  Slowness is observed when running with large hardlink threads(dfs.datanode.block.id.layout.upgrade.threads, default is 12 thread for each disk) and its runs for 2+ hours. 
I.e 10*12=120 threads (for 10 disks)
Small test:
RHEL7, 32 cores, 20 GB RAM, 8 GB DN heap
dfs.datanode.block.id.layout.upgrade.threads | Blocks | Disks | Time taken
12 | 3.3 Million | 1 | 2 minutes and 59 seconds
6 | 3.3 Million | 1 | 2 minutes and 35 seconds
3 | 3.3 Million | 1 | 2 minutes and 51 seconds
Tried same test twice and 95% is accurate (only a few sec …
> HDFS-15610 Reduced datanode upgrade/hardlink thread from 12 to 6

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/Concat.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/FsCommand.java
- hadoop-common-project/hadoop-common/src/site/markdown/FileSystemShell.md
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/shell/TestFsShellConcat.java
We should add one concat fs command for ease of use. It concatenates existing source files into the target file using FileSystem.concat().
> HADOOP-17021. Add concat fs command

- hadoop-project/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17269
Manually tested with Java 11.0.7
```
$ mvn install -DskipTests -DskipShade
$ mvn findbugs:findbugs -pl hadoop-common-project/hadoop-common
(snip)
[INFO] Fork Value is true
[java] SLF4J: No SLF4J providers were found.
[java] SLF4J: Defaulting to no-operation (NOP) logger implementation
[java] SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[INFO] Done FindBugs Analysis....
```
> HADOOP-17269. [JDK 11] Upgrade SpotBugs to 4.1.3 to fix false-positive warnings

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/sps/TestExternalStoragePolicySatisfier.java
One-liner fix of this UT.
Ignore datanode load so block placement can successfully pick fallback storage type.
> HDFS-15456. TestExternalStoragePolicySatisfier fails intermittently

- hadoop-hdfs-project/hadoop-hdfs-rbf/pom.xml
- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractRootDirectory.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15620
* Add assertj to test dependency
* Skip testSimpleRootListing in TestRouterWebHDFSContractRootDirectory
> HDFS-15620. RBF: Fix test failures after HADOOP-17281

- hadoop-project/pom.xml
Update the dependencies for org.apache.httpcomponent
- org.apache.httpcomponents:httpclient from 4.5.6 to 4.5.12
- org.apache.httpcomponents:httpcore from 4.4.10 to 4.4.13
Jira - https://issues.apache.org/jira/browse/HADOOP-17223
> HADOOP-17223 update org.apache.httpcomponents:httpclient to 4.5.12 and httpcore to 4.4.13

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileUtil.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFsShellCopy.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
Change-Id: Ibaa6e8a23ba575d0092b6d67989dc58c93a3a2d7
> HADOOP-16878. FileUtil.copy() to throw IOException if the source and destination are the same

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/MiniDFSCluster.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
https://issues.apache.org/jira/browse/HDFS-15614
Added `checkAndProvisionSnapshotTrashRoots` in `FSNamesystem`. Triggered in `NameNode` on startup if `dfs.namenode.snapshot.trashroot.enabled` set to `true`.
UT added in `TestDistributedFileSystem`.
The logic is ready for review.
~~I am considering adding another UT for HA case.~~ Now that we put the check in `startActiveServices()` it shouldn't be a problem anymore. Thanks @bshashikant for the suggestion.
> HDFS-15614. Initialize snapshot trash root during NameNode startup if enabled

- hadoop-project/pom.xml
Set doclint option explicitly in maven-javadoc-plugin.
JIRA: https://issues.apache.org/jira/browse/HADOOP-17309
> HADOOP-17309. Javadoc warnings and errors are ignored in the precommit jobs

- hadoop-build-tools/src/main/resources/checkstyle/checkstyle.xml
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ClientCache.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17315
- Ran "mvn clean process-sources" to update the source code via maven-replacer-plugin.
> HADOOP-17315. Use shaded guava in ClientCache.java

- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/auth/ITestCustomSigner.java
Re ran the failing test with s3 and gcs endpoints. All good.
> HADOOP-17305 Fix ITestCustomSigner to work with s3 compatible endpoints

- hadoop-common-project/hadoop-common/pom.xml
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileUtil.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/PartialListing.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/impl/FutureIOSupport.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/Constants.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/HCFSMountTableConfigLoader.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ClientCache.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ProxyCombiner.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/WeightedTimeCostProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/DomainNameResolverFactory.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/Groups.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/DelegatingSSLSocketFactory.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17175
> HADOOP-17175. [JDK 11] Fix javadoc errors in hadoop-common module.

- hadoop-build-tools/src/main/resources/checkstyle/checkstyle.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17319
> HADOOP-17319. Update the checkstyle config to ban some guava functions.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CommandWithDestination.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFsShellCopy.java
https://issues.apache.org/jira/browse/HADOOP-17328
> HADOOP-17328. LazyPersist Overwrite fails in direct write mode.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestFsDatasetImpl.java
> HDFS-15457. TestFsDatasetImpl fails intermittently.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java
> HDFS-15460. TestFileCreation#testServerDefaultsWithMinimalCaching fails intermittently.

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouter.java
- Use any available port to avoid BindException (main fix)
- Use try-with-resources for Router
- ~According to the javadoc, this test case is to verify the default behavior. Don't set the default value (true) explicitly to verify the default behavior.~
JIRA: https://issues.apache.org/jira/browse/HDFS-15657
> HDFS-15657. RBF: TestRouter#testNamenodeHeartBeatEnableDefault fails by BindException

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBPOfferService.java
> HDFS-15654. TestBPOfferService#testMissBlocksWhenReregister fails intermittently

- hadoop-client-modules/hadoop-client-minicluster/pom.xml
- hadoop-client-modules/hadoop-client-runtime/pom.xml
https://issues.apache.org/jira/browse/YARN-10314
This PR aims to backport YARN-10314 to branch-3.2.
> YARN-10472. [branch-3.2] Backport YARN-10314. YarnClient throws NoClassDefFoundError for WebSocketException with only shaded client jars

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/app/components/app-usage-donut-chart.js
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/app/components/queue-usage-donut-chart.js
JIRA: https://issues.apache.org/jira/browse/YARN-10469
Ensure the accuracy of the percentage values in the same chart on the YARN 'Cluster OverView' page are consistent
just a small improvement.
**before modified, the cluster overview page shows like this:**
**After modified, the manual test results are as follows:**
> YARN-10469.  YARN-UI2 The accuracy of the percentage values in the same chart on the YARN 'Cluster OverView' page are inconsistent

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/crypto/key/JavaKeyStoreProvider.java
Use the new rename API in JavaKeyStoreProvider#renameOrFail.
JIRA: https://issues.apache.org/jira/browse/HADOOP-17255
> HADOOP-17255. JavaKeyStoreProvider fails to create a new key if the keystore is HDFS

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/erasurecode/StripedBlockChecksumReconstructor.java
https://issues.apache.org/jira/browse/HDFS-15643
This is the reason for failure of TestFileChecksum when ISA-L is loaded
> HDFS-15643. EC: Fix checksum computation in case of native encoders.

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/TestLdapGroupsMapping.java
Because this looks like a JVM error string issue, changed to a slightly less brittle assert which should work across versions with different formatting.
> HADOOP-17340. TestLdapGroupsMapping failing -string mismatch in exception validation.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelperClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/server/protocol/StorageReport.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/hdfs.proto
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeDescriptor.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/BlockPoolSlice.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsVolumeImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsVolumeList.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/MountVolumeInfo.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/MountVolumeMap.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestFsDatasetImpl.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestFsVolumeList.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNamenodeCapacityReport.java
> HDFS-15548. Allow configuring DISK/ARCHIVE storage types on same device mount

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAuditLoggerWithCommands.java
https://issues.apache.org/jira/browse/HDFS-15667
The file disallow to be deleted, but record a `allowed=true` into auditlog, that is confusing me.
> HDFS-15667. Audit log record the unexpected allowed result when delete

- hadoop-project/pom.xml
https://issues.apache.org/jira/browse/HADOOP-17369
> HADOOP-17369. Bump up snappy-java to 1.1.8.1.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/pom.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/src/test/java/org/apache/hadoop/yarn/csi/adaptor/TestCsiAdaptorService.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/src/test/java/org/apache/hadoop/yarn/csi/adaptor/TestValidateVolumeCapabilityRequest.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi/src/test/java/org/apache/hadoop/yarn/csi/client/TestCsiClient.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17344
- Use hadoop-shaded-guava
- Remove skip replace-guava setting from yarn-csi pom.xml
> HADOOP-17344. Harmonize guava version and shade guava in yarn-csi.

- hadoop-client-modules/hadoop-client-api/pom.xml
- hadoop-client-modules/hadoop-client-check-test-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hadoop-client-modules/hadoop-client-integration-tests/pom.xml
- hadoop-client-modules/hadoop-client-integration-tests/src/test/java/org/apache/hadoop/example/ITUseMiniCluster.java
- hadoop-client-modules/hadoop-client-minicluster/pom.xml
- hadoop-client-modules/hadoop-client-runtime/pom.xml
In [HADOOP-15832](https://issues.apache.org/jira/browse/HADOOP-15832) we excluded org.bouncycastle from the shaded client jars but still relocate them to `org.apache.hadoop.shaded`. This breaks any downstream application that wants to use `MiniYARNCluster` from `hadoop-client-minicluster` since there is no way to bring its own org.bouncycastle test dependency. 
```
Error:  Caused by: sbt.ForkMain$ForkError: java.lang.ClassNotFoundException: org.apache.hadoop.shaded.org.bouncycastle.operator.OperatorCreationException
Error:  	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
Error:  	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
Error:  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
Error:  	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) …
```
> HADOOP-17324. Don't relocate org.bouncycastle in shaded client jars

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp/src/main/webapp/partials/details.html
replace href tags with ng-href
According to [angularjs docs](https://docs.angularjs.org/api/ng/directive/ngHref), it is better to use ng-href attributes instead of the default href one.
This prevent angularjs to give broken links to the user, if the evaluation of the link expression takes too long
> YARN-10480. replace href tags with ng-href

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/compress/zstd/ZStandardCompressor.java
- hadoop-common-project/hadoop-common/src/main/native/src/org/apache/hadoop/io/compress/zstd/ZStandardCompressor.c
This contribution is on behalf of Stripe, and I believe we already have a corporate CLA with ASF.
> HADOOP-17096. Fix ZStandardCompressor input buffer offset

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
This is an addendum to [HDFS-15607](https://issues.apache.org/jira/browse/HDFS-15607)'s https://github.com/apache/hadoop/pull/2352.
Pre HDFS-15607, when admin disallows snapshot on a **file**, it throws `PathIsNotDirectoryException`:
```
org.apache.hadoop.fs.PathIsNotDirectoryException: `/ssdir1/file1': Is not a directory
at org.apache.hadoop.hdfs.server.namenode.INodeDirectory.valueOf(INodeDirectory.java:65)
at org.apache.hadoop.hdfs.server.namenode.snapshot.SnapshotManager.resetSnapshottable(SnapshotManager.java:289)
at org.apache.hadoop.hdfs.server.namenode.FSDirSnapshotOp.disallowSnapshot(FSDirSnapshotOp.java:76)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.disallowSnapshot(FSNamesystem.java:6933)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.disallowSnapshot(Na …
```
> HDFS-15607. Addendum: Create trash dir when allowing snapshottable dir

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsClientConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/datatransfer/PacketReceiver.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/protocol/datatransfer/TestPacketReceiver.java
> HDFS-15469. Dynamically configure the size of PacketReceiver#MAX_PACKET_SIZE.

- hadoop-client-modules/hadoop-client-integration-tests/pom.xml
> HADOOP-17373. hadoop-client-integration-tests doesn't work when building with skipShade

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/conf/TestConfigurationSubclass.java
> HADOOP-17358. Improve excessive reloading of Configurations

- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/AbstractContractRenameTest.java
Add some assertions to make sure the result of `rename()` over existing file
more closely matches expectations defined by contract options
`rename-returns-false-if-dest-exists` and `rename-overwrites-dest`.
https://issues.apache.org/jira/browse/HADOOP-17365
Ran related contract tests in Hadoop project:
```
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.025 s - in org.apache.hadoop.fs.contract.rawlocal.TestRawlocalContractRename
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.993 s - in org.apache.hadoop.fs.contract.localfs.TestLocalFSContractRename
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.654 s - in org.apache.hadoop.fs.contract.hdfs.TestHDFSContractRename
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: …
```
> HADOOP-17365. Contract test for renaming over existing file is too lenient

- hadoop-project/pom.xml
Reverts apache/hadoop#2374
Reverting this because SpotBugs 4.1.0+ has the JSON license in its dependency.
> Revert "HADOOP-17269. [JDK 11] Upgrade SpotBugs to 4.1.3 to fix false-positive warnings"

- hadoop-tools/hadoop-aws/src/test/resources/contract/s3a.xml
Fix ITestS3AContractRename failure:
```
[ERROR] testRenameFileOverExistingFile[auth=false](org.apache.hadoop.fs.contract.s3a.ITestS3AContractRename)  Time elapsed: 2.805 s  <<< FAILURE!
java.lang.AssertionError: expected rename(s3a://rename/test/source-256.txt, s3a://rename/test/dest-512.txt) to be rejected with exception, but got false
at org.junit.Assert.fail(Assert.java:88)
at org.apache.hadoop.fs.contract.AbstractContractRenameTest.testRenameFileOverExistingFile(AbstractContractRenameTest.java:131)
```
by declaring `rename-returns-false-if-dest-exists=true` in the contract.
https://issues.apache.org/jira/browse/HADOOP-17376
Ran `ITestS3AContractRename` against Ozone S3 Gateway.
1. Download, build and run Ozone:
```
git clone https://github.com/apache/ozone
cd ozone
git checkout …
```
> HADOOP-17376. ITestS3AContractRename failing against stricter tests

- .dockerignore
- .gitignore
- Dockerfile
- build.sh
- config
1. Update to Hadoop 3.3.0 release.
2. And some misc updates/improvements for the docker build:
* Use current Apache Rat 0.13 in `build.sh` as 0.12 is now available only in archive.
* Add `.dockerignore` to speed up build (avoid sending `.git` etc. to the Docker daemon).
* Let git ignore `build` dir (created by `build.sh`).
* Add some MapReduce-related env to docker config to allow running MR examples.
https://issues.apache.org/jira/browse/HADOOP-17320
Built the new image locally:
```
$ ./build.sh
...
Successfully built 2adf1981fb31
Successfully tagged apache/hadoop:3
```
and tested it with the included sample Docker Compose cluster:
```
$ docker-compose up -d --scale datanode=3 --scale nodemanager=3
$ docker-compose exec resourcemanager yarn jar …
```
> HADOOP-17320. Update apache/hadoop:3 to 3.3.0 release

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/pom.xml
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/client/api/impl/TimelineConnector.java
I touched {{hadoop-yarn-common/pom.xml}} to trigger testing the entire module.
> YARN-10485. TimelineConnector swallows InterruptedException

- hadoop-hdfs-project/hadoop-hdfs-client/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestConfiguredFailoverProxyProvider.java
JIRA: https://issues.apache.org/jira/browse/HDFS-15685
Manually tested in JDK 13, 14, and 16-ea.
> HDFS-15685. [JDK 14] TestConfiguredFailoverProxyProvider#testResolveDomainNameUsingDNS fails.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/AbstractS3ATokenIdentifier.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/auth/delegation/TestS3ADelegationTokenSupport.java
This patch ensures that all token identifiers extending AbstractS3ATokenIdentifier to have issue date as the time the identifier instance is created.
> HADOOP-17379. AbstractS3ATokenIdentifier to set issue date == now.

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapreduce/v2/TestMRJobsWithProfiler.java
JIRA: https://issues.apache.org/jira/browse/MAPREDUCE-7305
Use Java Flight Recorder if the Java version >= 9.
Manually tested with AdoptOpenJDK 11.0.9:
```
[INFO] Running org.apache.hadoop.mapreduce.v2.TestMRJobsWithProfiler
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 55.928 s - in org.apache.hadoop.mapreduce.v2.TestMRJobsWithProfiler
[INFO] 
[INFO] 
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1
```
> MAPREDUCE-7305. [JDK 11] TestMRJobsWithProfiler fails.

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBPOfferService.java
https://issues.apache.org/jira/browse/HDFS-15674
The test intermittently fails if count of blocks reported by IBR does not reached to expected value(4000).
```
[ERROR] Failures:
[ERROR]   TestBPOfferService.testMissBlocksWhenReregister:341 Timed out wait for IBR counts FBRCount = 2441, IBRCount = 3999; expected = 4000. Exception: Timed out waiting for condition. Thread diagnostics:
Timestamp: 2020-11-16 12:45:57,425
{noformat}
```
This waiting condition does not make sense because pending IBRs are possible to be deleted by `clearIBRs()` in `BPServiceActor#reRegister`. It is ok because succeeding full block report covers them based on the discussion of [HDFS-15113](https://issues.apache.org/jira/browse/HDFS-15113).
The tests should check that all blocks are reported rather than counting …
> HDFS-15674. TestBPOfferService#testMissBlocksWhenReregister fails on trunk.

- hadoop-common-project/hadoop-common/pom.xml
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/authorize/DefaultImpersonationProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/authorize/ImpersonationProvider.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/authorize/ProxyUsers.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/MachineList.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/authorize/TestProxyUsers.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/util/TestMachineList.java
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra/src/main/java/org/apache/hadoop/tools/dynamometer/AllowAllImpersonationProvider.java
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload/src/test/java/org/apache/hadoop/tools/dynamometer/workloadgenerator/TestWorkloadGenerator.java
> HADOOP-17367. Add InetAddress api to ProxyUsers.authorize

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/Constants.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/viewfs/ViewFileSystemOverloadScheme.java
Link to [HDFS-15635](https://issues.apache.org/jira/browse/HDFS-15635)
> HDFS-15635. ViewFileSystemOverloadScheme support specifying mount table loader imp through conf

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/delegation/AbstractS3ATokenIdentifier.java
In HADOOP-17379, I missed to set issue date as local timezone sensitive, whereas we actually set issue date in UTC.
https://github.com/apache/hadoop/blob/07050339e0a41a7d4b89b852ffdd7aa315a9184b/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/delegation/AbstractDelegationTokenSecretManager.java#L418-L439
This PR fixes the issue.
> HADOOP-17388. AbstractS3ATokenIdentifier to issue date in UTC

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/MiniDFSCluster.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/ReadStripedFileWithDecodingHelper.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSClientRetries.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDecommissionWithStriped.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestEncryptedTransfer.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileChecksum.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseRecoveryStriped.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestReconstructStripedFile.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestReplication.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestWriteReadStripedFile.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestReconstructStripedBlocks.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestStripedINodeFile.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestHAAppend.java
This PR does the following:
- MiniDFSCluster.Builder  sets `dfs.namenode.redundancy.considerLoad ` to false by default.
- a new method `Builder.setNNRedundancyConsiderLoad()` can be used to overwrite the default value in the conf.
- removed explicit disabling of the flag in some Junits. Those were safe place to remove the disabling the flag, as the MiniDFSCluster is initialized directly after setting the configuration.
- supercede changes done in #2410 #2404 
> HDFS-15659. MiniDFSCluster dfs.namenode.redundancy.considerLoad default to false

- hadoop-hdfs-project/hadoop-hdfs/pom.xml
See https://issues.apache.org/jira/browse/HDFS-15690 for details.
` TestFSImage.testNativeCompression` failed with `java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Factory`:
https://ci-hadoop.apache.org/job/PreCommit-HDFS-Build/305/testReport/junit/org.apache.hadoop.hdfs.server.namenode/TestFSImage/testNativeCompression/
We need to have lz4-java as test dependency.
> HDFS-15690. Add lz4-java as test dependency

- LICENSE-binary
- hadoop-project/pom.xml
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/testing.md
Upgrade the AWS SDK to the latest release
Includes the changes to the manual steps of the regression testing needed to test directory marker support
Tested AWS London (v4 signing only, BTW)
* Integration tests ( -Dparallel-tests -DtestsThreadCount=4 -Dmarkers=keep -Ds3guard -Ddynamo  -Dfs.s3a.directory.marker.audit=true) with review of all output files. 
* Downstream spark build and run through spark-cloud-integration suite
* Manual commands from the testing document
> HADOOP-17343. Upgrade AWS SDK to 1.11.901

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/tools/MarkerTool.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/tools/ITestMarkerTool.java
This patch
* fixes the inversion
* adds a precondition check
* if the commands are supplied inverted, swaps them with a warning.
This is to stop breaking any tests written to cope with the existing
behavior.
* adds tests for all this
Tested (IMarkerTool tests): S3 london
> HADOOP-17332. S3A MarkerTool -min and -max are inverted.

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AFileOperationCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/OperationCost.java
Ran ITestS3AFileOperationCost in raw mode using ap-south-1 bucket. Saw no failures.
> HADOOP-17323 Skipping IO for root directory when empty directory flag is not required.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/TestNodeStatusUpdater.java
This PR tries to address several problems in the test class:
- In case of nodeManager failure, some loops will keep looping for ever without timeouts. The following examples was replaced by a limit that has a timeouts.
```java
while(heartBeadID < 12) {
Thread.Sleep();
}
```
- heartBeatID is volatile which does not guarantee atomic updates. This has been replaced with AtomicInteger.
- Loop on heartBeatID values, was not checking whether the NM has failed. In that case, the test case will keep looping using resources and CPU in vain. This has been replaced by checks on the NM service status.
- NM was closed twice: Once in the test method and a second time in the tearDown()
- Several tests did not wait for the NM to start after calling nm.start()
- stopping a service did not properly wait …
> YARN-10468. Fix TestNodeStatusUpdater timeouts and broken conditions

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/FSAppAttempt.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/MaxRunningAppsEnforcer.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/QueueManager.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/VisitedResourceRequestTracker.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/policies/DominantResourceFairnessPolicy.java
What? :: Fixing typos in package: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair
https://issues.apache.org/jira/browse/YARN-10488
@szilard-nemeth Can you please review this?
Thanks!
> [YARN-10488] - Several typos in package: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/contracts/exceptions/AbfsRestOperationException.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsHttpOperation.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsIoUtils.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsRestOperation.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemDelegationSAS.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsHttpOperation.java
Masking SAS signatures from logs
HNS-OAuth
========================
[INFO] 
[INFO] Tests run: 88, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Tests run: 459, Failures: 0, Errors: 0, Skipped: 66
[INFO] 
[WARNING] Tests run: 208, Failures: 0, Errors: 0, Skipped: 24
HNS-SharedKey
========================
[INFO] 
[INFO] Tests run: 88, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Tests run: 459, Failures: 0, Errors: 0, Skipped: 24
[INFO] 
[WARNING] Tests run: 208, Failures: 0, Errors: 0, Skipped: 16
NonHNS-SharedKey
========================
[INFO] 
[INFO] Tests run: 88, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Tests run: 459, Failures: 0, …
> HADOOP-17311. ABFS: Logs should redact SAS signature

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFileSystemCaching.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/performance.md
This adds a semaphore to throttle the number of FileSystem instances which
can becreated simultaneously, set in "fs.creation.parallel.count".
This is designed to reduce the impact of many threads in an application calling
FileSystem.get() on a filesystem which takes time to instantiate -for example
to an object where HTTPS connections are set up during initialization.
Many threads trying to do this may create spurious delays by conflicting
for access to synchronized blocks, when simply limiting the parallelism
diminishes the conflict, so speeds up all threads trying to access
the store.
The default value, 64, is larger than is likely to deliver any speedup -but
it does mean that there should be no adverse effects from the change.
If a service appears to be blocking on all threads …
> HADOOP-17313. FileSystem.get to support slow-to-instantiate FS clients.

- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java
- hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/client/HdfsAdmin.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/TestDFSAdmin.java
https://issues.apache.org/jira/browse/HDFS-15689
See the jira description for details.
Will add UT in `TestDFSAdmin` later. Maybe also in `TestEncryptionZones`.
> HDFS-15689. allow/disallowSnapshot on EZ roots shouldn't fail due to trash provisioning/emptiness check

- hadoop-common-project/hadoop-auth/pom.xml
- hadoop-hdfs-project/hadoop-hdfs-httpfs/pom.xml
- hadoop-mapreduce-project/hadoop-mapreduce-client/pom.xml
- hadoop-project-dist/pom.xml
- hadoop-yarn-project/hadoop-yarn/pom.xml
JIRA: https://issues.apache.org/jira/browse/HADOOP-17394
Manually tested. The following command passed with AdoptOpenJDK 11.0.9:
```
$ mvn clean package -Pdist,docs -DskipTests -DskipShade
```
> HADOOP-17394. [JDK 11] mvn package -Pdocs fails

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/contract/ITestAbfsFileSystemContractRename.java
- hadoop-tools/hadoop-azure/src/test/resources/azure-test.xml
Post updates to rename on existing file test, ABFS contract test is having failure. Updates were made in the AbstractContractTest class in https://issues.apache.org/jira/browse/HADOOP-17365.
To align to test expectation of no exception but a false return from rename, ABFS tests need config "fs.contract.rename-returns-false-if-dest-exists" set to true. 
Also the abstract class was reusing a static test folder path.  Hence on test re-run, where same storage container is used, source and destination path creations will fail with FileAlreadyExists, leading to test failures. This is also fixed.
[Test results pasted at the end of conversation tab].
> HADOOP-17396. ABFS: testRenameFileOverExistingFile Fails after Contract test update

- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/utils/DelegationSASGenerator.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/utils/ServiceSASGenerator.java
Below updates are made:
1. Upgrading the SAS version in Service SAS generator to Feb20 which is the latest server supported version (test code)
2. Updating the permission in Delegation SAS to "op" from "p" for ACL operation as identities added as suoid/saoid added by tests are not owners of test path (Again test code).
Relevant public documentation: https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-a-signed-object-id-for-a-security-principal-preview
Tests were re-run. Test results posted at end of conversation tab.
> HADOOP-17397. ABFS: SAS Test updates for version and permission update

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/contract/s3a/S3AContract.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/AbstractS3ATestBase.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/AbstractS3ACostTest.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/performance/ITestS3ADeleteCost.java
The addition of deprecated S3A configuration options in HADOOP-17318
triggered a reload of default (xml resource) configurations, which breaks
tests which fail if there's a per-bucket setting inconsistent with test
setup.
Creating an S3AFS instance before creating the Configuration() instance
for test runs gets that reload out the way before test setup takes
place.
Along with the fix, extra changes in the failing test suite to fail
fast when marker policy isn't as expected, and to log FS state better.
Testing: S3 London with marker policy forced to override (which is why this specific test failed)
> HADOOP-17385. ITestS3ADeleteCost.testDirMarkersFileCreation failure

- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/tools/MarkerTool.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ABucketExistence.java
Re-ran failed tests. No failures.
Ran tests using ap-south-1 bucket for raw and s3guard config. No failures.
CC @steveloughran
> HADOOP-17398. Skipping network I/O in S3A getFileStatus(/) breaks some tests

- hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html
> HDFS-15698. Fix the typo of dfshealth.html after HDFS-15358

- hadoop-common-project/hadoop-common/src/main/native/native.vcxproj
* The sources for lz4 do not exist for native
vcxproj for Visual Studio on the Windows
platform. Hence, removing the corresponding
source references.
> HADOOP-17399. lz4 sources missing for native Visual Studio project

- hadoop-hdfs-project/hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterRpc.java
https://issues.apache.org/jira/browse/HDFS-15677
Since heartbeatExpireInterval and assertion timeout of DN removal has the same value (5000 ms), the test fails intermittently. Updating the heartbeatExpireInterval and assertion timeout worked for me.
> HDFS-15677. TestRouterRpcMultiDestination#testGetCachedDatanodeReportfails on trunk.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeDescriptor.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestDatanodeDescriptor.java
> HDFS-15694. Avoid calling UpdateHeartBeatState inside DataNodeDescriptor

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirAttrOp.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSDirAttrOp.java
> HDFS-15703. Don't generate edits for set operations that are no-op

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/balancer/Balancer.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/balancer/BalancerParameters.java
- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/balancer/TestBalancer.java
Normally the most important purpose for HDFS balancer is to reduce the top used node to prevent datanode usage from being too high.
Currently, balancer almost randomly picks nodes as sources regardless of usage, which makes it slow to bring down the top used datanodes in the cluster, when there are less underutilized nodes in the cluster (consider expansion).
We can add an option to prefer top used nodes first in each iteration.
> HDFS-14904. Option to let Balancer prefer top used nodes in each iteration.

- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/HttpFSExceptionProvider.java
> HDFS-15706. HttpFS: Log more information on request failures.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/BlockingThreadPoolExecutorService.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/SemaphoredDelegatingExecutor.java
- hadoop-tools/hadoop-aliyun/src/main/java/org/apache/hadoop/fs/aliyun/oss/AliyunOSSFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/FailureInjectionPolicy.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/InconsistentAmazonS3Client.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AMultipartUploader.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AReadOpContext.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AUtils.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/WriteOperationHelper.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/auth/RoleModel.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/staging/StagingCommitter.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DirListingMetadata.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStore.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/PathMetadataDynamoDBTranslation.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/S3GuardTool.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestBlockingThreadPoolExecutorService.java
This does the following:
- removes `ListenableFuture` as well as `ListeningExecutorService` from `SemaphoredDelegatingExecutor`, so that modules such as `hadoop-aws` and `hadoop-aliyun` can consume the class from `hadoop-client-api` without running into Guava conflicts.
- replaces error message template usages in `checkArgument/checkState/checkNotNull` with `String.format`. The former is generally not available in Guava version < 20 so this is to eliminate potential conflicts.
> HADOOP-16080. hadoop-aws does not work with hadoop-client-api 

- hadoop-common-project/hadoop-kms/src/main/java/org/apache/hadoop/crypto/key/kms/server/KMSAudit.java
- hadoop-common-project/hadoop-kms/src/main/java/org/apache/hadoop/crypto/key/kms/server/KMSAuditLogger.java
- hadoop-common-project/hadoop-kms/src/test/java/org/apache/hadoop/crypto/key/kms/server/TestKMSAudit.java
Daryn Sharp reported that the kms-audit log only logs the short username:
```
OK[op=GENERATE_EEK, key=key1, user=hdfs, accessCount=4206, interval=10427ms]
```
In this example, it's impossible to tell which NN(s) requested EDEKs when they are all lumped together.
> HADOOP-17389. KMS should log full UGI principal.

- hadoop-hdfs-project/hadoop-hdfs-client/pom.xml
Include `org.bouncycastle` as test dependency for `hadoop-hdfs-client`.
> HDFS-15708. TestURLConnectionFactory fails by NoClassDefFoundError in branch-3.3 and branch-3.2

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestUpgradeDomainBlockPlacementPolicy.java
In some slow runs `TestUpgradeDomainBlockPlacementPolicy#testPlacement` and `TestUpgradeDomainBlockPlacementPolicy#testPlacementAfterDecommission` fail.
On branch-2.10, this was fixed by waiting for the replication to be complete.
> HDFS-15716. WaitforReplication in TestUpgradeDomainBlockPlacementPolicy

- hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/web/SLSWebApp.java
- hadoop-tools/hadoop-sls/src/test/java/org/apache/hadoop/yarn/sls/web/TestSLSWebApp.java
What? :: Fix deprecation warnings in SLSWebApp.java & TestSLSWebApp.java
------
toString(URI uri) Deprecated. 
> Use toString(URI, Charset) instead.
------
readFileToString(File file) Deprecated. 
> Use readFileToString(File, Charset) instead.
------
@aajisaka Can you please review this?
Thanks!
> YARN-10491: Fix deprecation warnings in SLSWebApp.java

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/ClusterNodeTracker.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/CapacityScheduler.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestCapacitySchedulerAsyncScheduling.java
##For  YARN-10380 issue
Import logic of multi-node allocation in CapacityScheduler.
> YARN-10380: Import logic of multi-node allocation in CapacityScheduler

- hadoop-project/pom.xml
https://issues.apache.org/jira/browse/HADOOP-17425
1.1.8.2 includes:
- Support Apple Silicon (M1, Mac-aarch64)
- Fixed the pure-java Snappy fallback logic when no native library for your platform is found.
> HADOOP-17425. Bump up snappy-java to 1.1.8.2

- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/FSOperations.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/HttpFSServerWebApp.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/metrics/HttpFSServerMetrics.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/server/metrics/package-info.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/lib/wsrs/InputStreamEntity.java
- hadoop-hdfs-project/hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/server/TestHttpFSServer.java
> HDFS-15711. Add Metrics to HttpFS Server.

- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
https://issues.apache.org/jira/browse/HDFS-15720
Hadoop project use log4j 1.2.x, we can't config some properties of logger in log4j.properties file , For example, AsyncAppender BufferSize and Blocking see https://logging.apache.org/log4j/1.2/apidocs/index.html.
Namenode  should add some audit async logger log4j config In order to facilitate the adjustment of log4j usage and audit log output performance adjustment. 
The new configuration is as follows
dfs.namenode.audit.log.async.blocking false
dfs.namenode.audit.log.async.buffer.size 128
no test.
> HDFS-15720 namenode audit async logger should add some log4j config

- hadoop-cloud-storage-project/hadoop-cos/src/main/java/org/apache/hadoop/fs/cosn/CosNFileSystem.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/BlockingThreadPoolExecutorService.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/SemaphoredDelegatingExecutor.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestFileSystemCaching.java
- hadoop-tools/hadoop-aliyun/src/main/java/org/apache/hadoop/fs/aliyun/oss/AliyunOSSFileSystem.java
- hadoop-tools/hadoop-aws/dev-support/findbugs-exclude.xml
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/DeleteOperation.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/StoreContext.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/StoreContextBuilder.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/s3guard/DynamoDBMetadataStore.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestBlockingThreadPoolExecutorService.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/ITestPartialRenamesDeletes.java
(This is a backport from #2510)
This does the following:
- removes `ListenableFuture` as well as `ListeningExecutorService` from public interfaces, so that modules such as `hadoop-aws` and `hadoop-aliyun` can consume the class from hadoop-client-api without running into Guava conflicts.
> HADOOP-16080. hadoop-aws does not work with hadoop-client-api

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsOutputStream.java
Each AbfsOutputStream holds on to an instance of elastic bytebuffer pool. This instance needs to be released so that the memory can be given back to JVM's available memory pool. 
For testing, existing tests were re-run.
> HADOOP-17413. ABFS: Release elastic byte buffer pool at close

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/placement/CSMappingPlacementRule.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-router/src/test/java/org/apache/hadoop/yarn/server/router/webapp/TestRouterWebServicesREST.java
JIRA: https://issues.apache.org/jira/browse/YARN-10499
In the test, the groupSet is empty and `it.next()` throws NoSuchElementException.
If the groupSet is empty, skip checking the set.
> YARN-10499. TestRouterWebServiceREST fails (#2490). Contributed by Akira Ajisaka

- hadoop-tools/hadoop-azure/.gitignore
- hadoop-tools/hadoop-azure/dev-support/testrun-scripts/runtests.sh
- hadoop-tools/hadoop-azure/dev-support/testrun-scripts/testsupport.sh
- hadoop-tools/hadoop-azure/src/site/markdown/testing_azure.md
- hadoop-tools/hadoop-azure/src/test/resources/azure-auth-keys.xml.template
- hadoop-tools/hadoop-azure/src/test/resources/azure-test.xml
ADLS Gen 2 supports accounts with and without hierarchical namespace support. ABFS driver supports various authorization mechanisms like OAuth, haredKey, Shared Access Signature. The integration tests need to be executed against accounts with and without hierarchical namespace support using various authorization mechanisms.
Currently the developer has to manually run the tests with different combinations of configurations.
The expectation is to automate these runs with different combinations.
The PR introduces a shell script with which the developer can specify the configuration variants and get different combinations of tests executed.
> HADOOP-17191. ABFS: Run the tests with various combinations of configurations and publish a consolidated results

- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsClient.java
- hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/services/AbfsHttpOperation.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemDelete.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsClient.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/services/TestAbfsPerfTracker.java
- hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/utils/TestMockHelpers.java
Delete idempotency code returns success with a dummy success HttpOperation. the calling code that checks continuation token throws NPE as the dummy success instance does not have any response headers.
In case of non-HNS account, server could return continuation token.  Dummy success response code is modified to not fail while accessing response headers.
Existing test for delete idempotency was modified to reproduce the NPE and test the fix.
> HADOOP-17407. ABFS: Fix NPE on delete idempotency flow

- hadoop-client-modules/hadoop-client-minicluster/pom.xml
- hadoop-common-project/hadoop-auth/pom.xml
- hadoop-common-project/hadoop-auth/src/main/java/org/apache/hadoop/security/authentication/server/AuthenticationFilter.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/http/RestCsrfPreventionFilter.java
- hadoop-common-project/hadoop-kms/src/main/java/org/apache/hadoop/crypto/key/kms/server/KMSAuthenticationFilter.java
- hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ImageServlet.java
- hadoop-project/pom.xml
> HADOOP-17371. Bump Jetty to the latest version 9.4.34. Contributed by Wei-Chiu Chuang.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/HttpServer2.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/FileBasedKeyStoresFactory.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/FileMonitoringTimerTask.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509KeystoreManager.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509TrustManager.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509KeyManager.java
- hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509TrustManager.java
Addresses https://issues.apache.org/jira/browse/HADOOP-16524, in addition covering the DataNode use case. 
- Following the existing ReloadingX509TrustManager, a new ReloadingX509KeystoreManager was created.
- Existing code slightly refactored so both trust manager and keystore reloading managers share the monitoring logic within a single java.util.Timer (and therefore a single thread). 
- In HttpServer2, the same strategy as a previously proposed patch (see above) is used with SSLContextFactory.reload, but with the addition of cleanup upon stopping the server.
- A new config parameter which applies to all of the above FileBasedKeyStoresFactory.SSL_STORES_RELOAD_INTERVAL_TPL_KEY supersedes the existing FileBasedKeyStoresFactory.SSL_TRUSTSTORE_RELOAD_INTERVAL_TPL_KEY which only applies to …
> HADOOP-16524. Reloading SSL keystore for both DataNode and NameNode

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDecommission.java
https://issues.apache.org/jira/browse/HDFS-15702
dfs.blockreport.intervalMsec is set to 1000 in the TestDecommission. While the testAllocAndIBRWhileDecommission tries to stop IBRs by DataNodeTestUtils#pauseIBR, IBR still can be sent in the code path of FBR (BPServiceActor#blockReport). Avoiding FBR (except for the 1st BR) by setting dfs.blockreport.intervalMsec to enough long value should fix the issue. The testAllocAndIBRWhileDecommission does not depend on FBR.
The test failure can not be reproduced in 100 runs after applying the patch on my local.
```
for i in `seq 100` ; do echo $i && mvn test -DignoreTestFailure=false -Dtest=TestDecommission#testAllocAndIBRWhileDecommission || break ; done
```
> HDFS-15702. Fix intermittent falilure of TestDecommission#testAllocAndIBRWhileDecommission.

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/test/java/org/apache/hadoop/mapreduce/jobhistory/TestJobHistoryEventHandler.java
The test `org.apache.hadoop.mapreduce.jobhistory.TestJobHistoryEventHandler.testSigTermedFunctionality` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Details
---
Running `TestJobHistoryEventHandler.testSigTermedFunctionality` twice would result in the second run failing due to `NullPointerException`shown in the following:
```
java.lang.NullPointerException
at org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler.serviceStop(JobHistoryEventHandler.java:460)
at org.apache.hadoop.service.AbstractService.stop(AbstractService.java:221)
at …
```
> MAPREDUCE-7310. Clear the fileMap in JHEventHandlerForSigtermTest

- hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/balancer/TestBalancerWithMultipleNameNodes.java
https://issues.apache.org/jira/browse/HDFS-15672
The setting of testBalancingBlockpoolsWithBlockPoolPolicy is
* 2 NameNodes (2 name spaces)
* 4 DataNodes (with 500 bytes capacity per node)
* blocksize = 100, replication factor = 2
* creating 300 bytes file on both name spaces (6 blocks total)
* add 2 DataNodes (with 500 bytes capacity per node)
* running balancer
If one of the DataNode is chosen for all 6 blocks, no free space is available. The error causes retry of block creation.
```
2020-11-18 06:01:36,648 [DataXceiver for client DFSClient_NONMAPREDUCE_1983766438_12 at /127.0.0.1:46158 [Receiving block BP-631108559-172.31.197.233-1605679293748:blk_1073741827_1003]] ERROR datanode.DataNode (DataXceiver.java:run(324)) - host1.foo.com:43495:DataXceiver error processing WRITE_BLOCK …
```
> HDFS-15672. TestBalancerWithMultipleNameNodes#testBalancingBlockpoolsWithBlockPoolPolicy fails on trunk.

- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/statistics/DurationTrackerFactory.java
- hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/statistics/StoreStatisticNames.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInstrumentation.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Statistic.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/WriteOperationHelper.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/WriteOperations.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/CommitConstants.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/CommitOperations.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/commit/magic/MagicCommitTracker.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/ContextAccessors.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/HeaderProcessing.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/statistics/CountersAndGauges.java
- hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/statistics/impl/BondedS3AStatisticsContext.java
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/committer_architecture.md
- hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/committers.md
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3AMiscOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/ITestS3ARemoteFileChanged.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/AbstractITCommitProtocol.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/ITestCommitOperations.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/magic/ITestMagicCommitProtocol.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/commit/staging/integration/ITestStagingCommitProtocol.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/ITestXAttrCost.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/TestHeaderProcessing.java
- hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/TestPartialDeleteFailures.java
* Add getXAttr and listXAttr API calls to S3AFileSystem
* Returns all S3 object headers as XAttr attributes prefixed "header." That's custom and standard (e.g header.Content-Length).
The setXAttr call isn't implemented, so for correctness the FS doesn't
declare its support for the API in hasPathCapability().
The magic commit file write sets the custom header 
set the length of the data final data in the header
x-hadoop-s3a-magic-data-length in the marker file.
A matching patch in Spark will look for the XAttr
"header.x-hadoop-s3a-magic-data-length" when the file
being probed for output data is zero byte long. 
As a result, the job tracking statistics will report the
bytes written but yet to be manifest.
Example from the debug log of a run
```
2020-12-10 14:56:16,760 [Executor task launch …
```
> HADOOP-17414. Magic committer files don't have the count of bytes written collected by spark

- hadoop-common-project/hadoop-auth/src/main/java/org/apache/hadoop/security/authentication/util/KerberosUtil.java
- hadoop-common-project/hadoop-auth/src/test/java/org/apache/hadoop/security/authentication/server/TestKerberosAuthenticationHandler.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core/src/main/java/org/apache/hadoop/yarn/service/utils/HttpUtil.java
- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client/src/main/java/org/apache/hadoop/yarn/client/util/YarnClientUtils.java
JIRA: https://issues.apache.org/jira/browse/HADOOP-17432
- Removed the use of JDK internal APIs
- Deprecated KerberosUtil#getOidInstance
- Use the default OID in Hadoop
TestAltKerberosAuthenticationHandler passed in JDK 16-ea+28.
```
[INFO] Running org.apache.hadoop.security.authentication.server.TestAltKerberosAuthenticationHandler
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.761 s - in org.apache.hadoop.security.authentication.server.TestAltKerberosAuthenticationHandler
```
> HADOOP-17432. [JDK 16] KerberosUtil#getOidInstance is broken by JEP 396

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/test/java/org/apache/hadoop/mapreduce/jobhistory/TestHistoryViewerPrinter.java
> MAPREDUCE-7270. TestHistoryViewerPrinter could be failed when the locale isn't English.

- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra/src/main/java/org/apache/hadoop/tools/dynamometer/AllowAllImpersonationProvider.java
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra/src/main/java/org/apache/hadoop/tools/dynamometer/DynoInfraUtils.java
- hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra/src/test/java/org/apache/hadoop/tools/dynamometer/TestDynamometerInfra.java
> HADOOP-17375. Fix the error of TestDynamometerInfra.

- hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/app/templates/yarn-app/info.hbs
fix this 
https://issues.apache.org/jira/browse/YARN-10545
manual test works well:
> [YARN-10545] Improve the readability of diagnostics log in yarn-ui2 web page.

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs/src/site/markdown/HistoryServerRest.md
The API https://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-hs/HistoryServerRest.html#Task_Counters_API, modify jobTaskCounters's itemName from taskcounterGroup to taskCounterGroup.
> MAPREDUCE-7258. HistoryServerRest.html#Task_Counters_API, modify the jobTaskCounters's itemName from taskcounterGroup to taskCounterGroup

- hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/test/java/org/apache/hadoop/mapred/TestTaskProgressReporter.java
The test `org.apache.hadoop.mapred.TestTaskProgressReporter.testBytesWrittenRespectingLimit` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Details
---
Running `TestTaskProgressReporter.testBytesWrittenRespectingLimit` twice would result in the second run failing with the following assertion:
```
Assert.assertEquals(failFast, threadExited)
```
The root cause for this is that when`testBytesWrittenRespectingLimit` writes some bytes on the local file system, some counters are being incremented. The problem is that, after the test is done, the counter is not reset. With this polluted shared …
> MAPREDUCE-7311. Clear filesystem statistics after tests in TestTaskProgressReporter

- hadoop-project/pom.xml
Upgrading the Gson library to 2.8.9 (latest version at the moment).
> HADOOP-13464. Upgrade Gson to 2.8.9
